package main

import (
	"bytes"
	"strings"
	"testing"
)

// emitFor parses src, runs discovery, and returns the emitter's output.
// Intentionally goes through the same pipeline `godot-go` uses at runtime
// — that way the test catches regressions anywhere along the pipe, not
// just in emit.go.
func emitFor(t *testing.T, src string) string {
	t.Helper()
	d, fset := mustDiscoverWithFset(t, src)
	var buf bytes.Buffer
	if err := emit(&buf, fset, d); err != nil {
		t.Fatalf("emit: %v", err)
	}
	return buf.String()
}

func TestEmitMainClassWithMethod(t *testing.T) {
	src := `package mypkg
import "github.com/legendary-code/godot-go/core"
// @class
type MyNode struct {
	// @extends
	core.Node
}
func (n *MyNode) Hello() {}
`
	out := emitFor(t, src)

	mustContain(t, out, "package mypkg")
	mustContain(t, out, "// Code generated by godot-go; DO NOT EDIT.")
	mustContain(t, out, `Name:      "MyNode",`)
	mustContain(t, out, `Parent:    "Node",`)
	// Side-table helpers must use the lowercased class prefix.
	mustContain(t, out, "myNodeInstancesMu")
	mustContain(t, out, "myNodeInstances   = map[uintptr]*MyNode{}")
	// Method registration: Go name `Hello`, Godot name `hello`.
	mustContain(t, out, `Name:  "hello",`)
	mustContain(t, out, "self.Hello()")
	// Auto-init wiring at SCENE level.
	mustContain(t, out, "RegisterInitCallback(gdextension.InitLevelScene, registerMyNode)")
	mustContain(t, out, `UnregisterClass("MyNode")`)
}

func TestEmitNoMethods(t *testing.T) {
	src := `package x
import "github.com/legendary-code/godot-go/core"
// @class
type Lonely struct {
	// @extends
	core.Node
}
`
	out := emitFor(t, src)
	if strings.Contains(out, "RegisterClassMethod") {
		t.Errorf("class with no methods shouldn't emit RegisterClassMethod call:\n%s", out)
	}
	mustContain(t, out, "registerLonely")
}

func TestEmitStaticMethod(t *testing.T) {
	src := `package x
import "github.com/legendary-code/godot-go/core"
// @class
type N struct {
	// @extends
	core.Node
}
// @static
func (N) Origin() int64 { return 42 }
`
	out := emitFor(t, src)

	// Static methods skip the per-instance side-table lookup and call on a
	// zero value — and must register MethodFlagStatic so GDScript can use
	// `N.origin()` syntax.
	mustContain(t, out, "_ = instance")
	mustContain(t, out, "var self N")
	mustContain(t, out, "self.Origin()")
	// gofmt may pad the field column; check the value, not the column.
	mustContain(t, out, "gdextension.MethodFlagsDefault | gdextension.MethodFlagStatic,")
	// The instance-handle lookup pattern must NOT appear for a static-only class.
	if strings.Contains(out, "lookupNInstance(instance)") {
		t.Errorf("static method body should not perform instance lookup:\n%s", out)
	}
}

func TestEmitOverrideMethod(t *testing.T) {
	src := `package x
import "github.com/legendary-code/godot-go/core"
// @class
type N struct {
	// @extends
	core.Node
}
// @override
func (n *N) process(delta float64) {}
`
	out := emitFor(t, src)

	// Overrides route through RegisterClassVirtual (no Call/Args/Return
	// metadata) and the engine name carries the leading underscore Godot
	// expects (`process` → `_process`).
	mustContain(t, out, "RegisterClassVirtual(gdextension.ClassVirtualDef{")
	mustContain(t, out, `Name:  "_process",`)
	mustContain(t, out, "self.process(arg0)")
	mustContain(t, out, "arg0 := *(*float64)(gdextension.PtrCallArg(args, 0))")
	// An override must NOT appear as a regular method.
	if strings.Contains(out, `RegisterClassMethod(gdextension.ClassMethodDef{
		Class: "N",
		Name:  "_process"`) {
		t.Errorf("override should not also register as a regular method:\n%s", out)
	}
}

func TestEmitOverrideExportedReceiver(t *testing.T) {
	// Capitalized Go method + @override — the case decision is independent
	// of override status; the leading underscore is added because it's an
	// override, not because of case.
	src := `package x
import "github.com/legendary-code/godot-go/core"
// @class
type N struct {
	// @extends
	core.Node
}
// @override
func (n *N) Process(delta float64) {}
`
	out := emitFor(t, src)
	mustContain(t, out, "RegisterClassVirtual(gdextension.ClassVirtualDef{")
	mustContain(t, out, `Name:  "_process",`)
	mustContain(t, out, "self.Process(arg0)")
}

func TestEmitOverrideWithExplicitName(t *testing.T) {
	src := `package x
import "github.com/legendary-code/godot-go/core"
// @class
type N struct {
	// @extends
	core.Node
}
// @override
// @name _physics_process
func (n *N) PhysicsTick(delta float64) {}
`
	out := emitFor(t, src)

	// @name with leading underscore is taken verbatim — no double prefix.
	mustContain(t, out, `Name:  "_physics_process",`)
}

func TestEmitMethodWithIntArgsAndReturn(t *testing.T) {
	src := `package mypkg
import "github.com/legendary-code/godot-go/core"
// @class
type MyNode struct {
	// @extends
	core.Node
}
func (n *MyNode) Add(a, b int64) int64 { return a + b }
`
	out := emitFor(t, src)

	// Variant import is needed once a method touches a primitive.
	mustContain(t, out, `core "github.com/legendary-code/godot-go/core"`)
	// Both bodies should read both args and store the result.
	mustContain(t, out, "arg0 := *(*int64)(gdextension.PtrCallArg(args, 0))")
	mustContain(t, out, "arg1 := *(*int64)(gdextension.PtrCallArg(args, 1))")
	mustContain(t, out, "*(*int64)(ret) = result")
	mustContain(t, out, "arg0 := core.VariantAsInt64(args[0])")
	mustContain(t, out, "core.VariantSetInt64(ret, result)")
	// Dispatch must thread arg0/arg1 through.
	mustContain(t, out, "self.Add(arg0, arg1)")
	// Registration metadata: HasReturn + parallel arg slices.
	mustContain(t, out, "HasReturn:      true,")
	mustContain(t, out, "ReturnType:     gdextension.VariantTypeInt,")
	mustContain(t, out, "ReturnMetadata: gdextension.ArgMetaIntIsInt64,")
	mustContain(t, out, "ArgTypes: []gdextension.VariantType{")
	mustContain(t, out, "ArgMetadata: []gdextension.MethodArgumentMetadata{")
}

func TestEmitMethodWithMixedPrimitives(t *testing.T) {
	src := `package x
import "github.com/legendary-code/godot-go/core"
// @class
type N struct {
	// @extends
	core.Node
}
func (n *N) Mix(b bool, i int32, f float32, s string) string { return s }
`
	out := emitFor(t, src)

	// Each primitive gets the right wire conversion / extractor.
	mustContain(t, out, "arg0 := *(*bool)(gdextension.PtrCallArg(args, 0))")
	mustContain(t, out, "arg1 := int32(*(*int64)(gdextension.PtrCallArg(args, 1)))")
	mustContain(t, out, "arg2 := float32(*(*float64)(gdextension.PtrCallArg(args, 2)))")
	mustContain(t, out, "arg3 := core.PtrCallArgString(args, 3)")
	mustContain(t, out, "core.PtrCallStoreString(ret, result)")
	// Variant-side metadata reflects the narrower types.
	mustContain(t, out, "gdextension.ArgMetaIntIsInt32,")
	mustContain(t, out, "gdextension.ArgMetaRealIsFloat,")
}

func TestEmitRejectsUnsupportedType(t *testing.T) {
	src := `package x
import "github.com/legendary-code/godot-go/core"
// @class
type N struct {
	// @extends
	core.Node
}
func (n *N) Foo(xs []int) {}
`
	d, fset := mustDiscoverWithFset(t, src)
	var buf bytes.Buffer
	err := emit(&buf, fset, d)
	if err == nil {
		t.Fatalf("expected emit to reject slice arg")
	}
	if !strings.Contains(err.Error(), "unsupported type") {
		t.Errorf("unexpected error: %v", err)
	}
}

func TestEmitNameOverride(t *testing.T) {
	src := `package x
import "github.com/legendary-code/godot-go/core"
// @class
type N struct {
	// @extends
	core.Node
}
// @name shout
func (n *N) Hello() {}
`
	out := emitFor(t, src)
	mustContain(t, out, `Name:  "shout",`)
}

func TestEmitPropertyFieldForm(t *testing.T) {
	src := `package x
import "github.com/legendary-code/godot-go/core"
// @class
type N struct {
	// @extends
	core.Node
	// @property
	Health int64
}
`
	out := emitFor(t, src)

	// Synthesized accessor methods land in the bindings file as plain Go.
	mustContain(t, out, "func (n *N) GetHealth() int64 { return n.Health }")
	mustContain(t, out, "func (n *N) SetHealth(v int64) { n.Health = v }")
	// The synthesized methods are registered through the regular method
	// path, by their snake-case names.
	mustContain(t, out, `Name:  "get_health",`)
	mustContain(t, out, `Name:  "set_health",`)
	// Property registration links the property to those method names.
	mustContain(t, out, "RegisterClassProperty(gdextension.ClassPropertyDef{")
	mustContain(t, out, `Name:   "health",`)
	mustContain(t, out, `Setter: "set_health",`)
	mustContain(t, out, `Getter: "get_health",`)
}

func TestEmitPropertyFieldFormReadOnly(t *testing.T) {
	src := `package x
import "github.com/legendary-code/godot-go/core"
// @class
type N struct {
	// @extends
	core.Node
	// @readonly
	// @property
	Health int64
}
`
	out := emitFor(t, src)

	// Read-only: getter is synthesized but the setter must NOT be.
	mustContain(t, out, "func (n *N) GetHealth() int64 { return n.Health }")
	if strings.Contains(out, "func (n *N) SetHealth") {
		t.Errorf("read-only property must not synthesize a setter:\n%s", out)
	}
	if strings.Contains(out, `"set_health"`) {
		t.Errorf("read-only property must not register a setter method:\n%s", out)
	}
	mustContain(t, out, `Getter: "get_health",`)
	if strings.Contains(out, "Setter:") {
		t.Errorf("read-only property registration must omit Setter field:\n%s", out)
	}
}

func TestEmitPropertyMethodForm(t *testing.T) {
	src := `package x
import "github.com/legendary-code/godot-go/core"
// @class
type N struct {
	// @extends
	core.Node
}
// @property
func (n *N) GetHealth() int64 { return 0 }
// @property
func (n *N) SetHealth(v int64) {}
`
	out := emitFor(t, src)

	// Method form: codegen does NOT synthesize accessors — the user
	// already wrote them. We just register the property.
	if strings.Contains(out, "{ return n.Health }") {
		t.Errorf("method-form property must not re-synthesize the user's getter:\n%s", out)
	}
	mustContain(t, out, "RegisterClassProperty(gdextension.ClassPropertyDef{")
	mustContain(t, out, `Setter: "set_health",`)
	mustContain(t, out, `Getter: "get_health",`)
}

func TestEmitSignals(t *testing.T) {
	src := `package x
import "github.com/legendary-code/godot-go/core"
// @class
type N struct {
	// @extends
	core.Node
}

// @signals
type Signals interface {
	Damaged(amount int64)
	LeveledUp()
	Tagged(label string)
}
`
	out := emitFor(t, src)

	// Synthesized emit methods on *N — name = signal name, args
	// preserved from the interface declaration.
	mustContain(t, out, "func (n *N) Damaged(amount int64) {")
	mustContain(t, out, "func (n *N) LeveledUp() {")
	mustContain(t, out, "func (n *N) Tagged(label string) {")

	// Per-arg Variant construction + dispatch.
	mustContain(t, out, "arg0 := core.NewVariantInt(amount)")
	mustContain(t, out, "arg0 := core.NewVariantString(label)")
	mustContain(t, out, `gdextension.EmitSignal(n.Ptr(), gdextension.InternStringName("damaged"), args)`)
	mustContain(t, out, `gdextension.EmitSignal(n.Ptr(), gdextension.InternStringName("leveled_up"), nil)`)

	// RegisterClassSignal at SCENE init.
	mustContain(t, out, "RegisterClassSignal(gdextension.ClassSignalDef{")
	mustContain(t, out, `Name:  "damaged",`)
	mustContain(t, out, `Name:  "leveled_up",`)
	mustContain(t, out, `Name:  "tagged",`)

	// The synthesized emit method is Go-only — NOT registered with
	// ClassDB. GDScript callers that want to trigger emission from
	// outside the class use the standard emit_signal API.
	if strings.Contains(out, `Name:  "damaged",
		Call: func(`) {
		t.Errorf("synthesized signal-emit methods must not be ClassDB-registered:\n%s", out)
	}
}

func TestEmitPropertyGroupAndHints(t *testing.T) {
	src := `package x
import "github.com/legendary-code/godot-go/core"
// @class
type N struct {
	// @extends
	core.Node

	// @group("Combat")
	// @export_range(0, 100, 5)
	// @property
	Damage int64

	// @group("Combat")
	// @export_enum("Idle", "Run")
	// @property
	Mode int64

	// @group("Visuals")
	// @subgroup("Texture")
	// @export_file("*.png")
	// @property
	Skin string
}
`
	out := emitFor(t, src)

	// One group registration per group transition; subgroup follows
	// the group it nests under.
	mustContain(t, out, "RegisterClassPropertyGroup(gdextension.ClassPropertyGroupDef{")
	mustContain(t, out, `Name:  "Combat",`)
	mustContain(t, out, `Name:  "Visuals",`)
	mustContain(t, out, "RegisterClassPropertySubgroup(gdextension.ClassPropertyGroupDef{")
	mustContain(t, out, `Name:  "Texture",`)

	// Hints render with the right enum const + payload.
	mustContain(t, out, "Hint:       gdextension.PropertyHintRange,")
	mustContain(t, out, `HintString: "0,100,5",`)
	mustContain(t, out, "Hint:       gdextension.PropertyHintEnum,")
	mustContain(t, out, `HintString: "Idle,Run",`)
	mustContain(t, out, "Hint:       gdextension.PropertyHintFile,")
	mustContain(t, out, `HintString: "*.png",`)
}

func TestEmitDefaultInitLevelIsScene(t *testing.T) {
	src := `package x
import "github.com/legendary-code/godot-go/core"
// @class
type N struct {
	// @extends
	core.Node
}
`
	out := emitFor(t, src)
	mustContain(t, out, "RegisterInitCallback(gdextension.InitLevelScene, registerN)")
	mustContain(t, out, "RegisterDeinitCallback(gdextension.InitLevelScene,")
}

func TestEmitEditorClassUsesEditorInitLevel(t *testing.T) {
	src := `package x
import "github.com/legendary-code/godot-go/core"
// @editor
// @class
type N struct {
	// @extends
	core.Node
}
`
	out := emitFor(t, src)
	mustContain(t, out, "RegisterInitCallback(gdextension.InitLevelEditor, registerN)")
	mustContain(t, out, "RegisterDeinitCallback(gdextension.InitLevelEditor,")
	if strings.Contains(out, "InitLevelScene") {
		t.Errorf("@editor class should not reference InitLevelScene at all:\n%s", out)
	}
}

func mustContain(t *testing.T, haystack, needle string) {
	t.Helper()
	if !strings.Contains(haystack, needle) {
		t.Errorf("output missing %q\n--- output ---\n%s", needle, haystack)
	}
}
