// Code generated by godot-go-bindgen. DO NOT EDIT.

package core

import (
	"runtime"
	"sync"
	"unsafe"

	"github.com/legendary-code/godot-go/internal/gdextension"
	"github.com/legendary-code/godot-go/variant"
)

// AStar2D mirrors the Godot engine class AStar2D.
type AStar2D struct {
	RefCounted
}

// AStar2DFromPtr wraps an existing host-allocated GDExtensionObjectPtr in a
// *AStar2D. Returns nil on a nil input. AStar2D descends from RefCounted, so the
// returned wrapper carries a Go finalizer that drops one engine
// reference (via Unreference, dispatched on the main thread) when
// Go's GC determines the wrapper is unreachable. Users who want
// deterministic free can call ret.Unreference() directly — the
// finalizer is harmless after the refcount hits zero.
func AStar2DFromPtr(p gdextension.ObjectPtr) *AStar2D {
	if p == nil {
		return nil
	}
	ret := &AStar2D{}
	ret.BindPtr(p)
	runtime.SetFinalizer(ret, func(r *AStar2D) {
		gdextension.RunOnMain(func() { r.Unreference() })
	})
	return ret
}

var (
	aStar2DMethodGetAvailablePointId = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AStar2D"),
			gdextension.InternStringName("get_available_point_id"),
			3905245786,
		)
	})
	aStar2DMethodAddPoint = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AStar2D"),
			gdextension.InternStringName("add_point"),
			4074201818,
		)
	})
	aStar2DMethodGetPointPosition = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AStar2D"),
			gdextension.InternStringName("get_point_position"),
			2299179447,
		)
	})
	aStar2DMethodSetPointPosition = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AStar2D"),
			gdextension.InternStringName("set_point_position"),
			163021252,
		)
	})
	aStar2DMethodGetPointWeightScale = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AStar2D"),
			gdextension.InternStringName("get_point_weight_scale"),
			2339986948,
		)
	})
	aStar2DMethodSetPointWeightScale = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AStar2D"),
			gdextension.InternStringName("set_point_weight_scale"),
			1602489585,
		)
	})
	aStar2DMethodRemovePoint = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AStar2D"),
			gdextension.InternStringName("remove_point"),
			1286410249,
		)
	})
	aStar2DMethodHasPoint = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AStar2D"),
			gdextension.InternStringName("has_point"),
			1116898809,
		)
	})
	aStar2DMethodGetPointConnections = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AStar2D"),
			gdextension.InternStringName("get_point_connections"),
			2865087369,
		)
	})
	aStar2DMethodGetPointIds = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AStar2D"),
			gdextension.InternStringName("get_point_ids"),
			3851388692,
		)
	})
	aStar2DMethodSetNeighborFilterEnabled = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AStar2D"),
			gdextension.InternStringName("set_neighbor_filter_enabled"),
			2586408642,
		)
	})
	aStar2DMethodIsNeighborFilterEnabled = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AStar2D"),
			gdextension.InternStringName("is_neighbor_filter_enabled"),
			36873697,
		)
	})
	aStar2DMethodSetPointDisabled = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AStar2D"),
			gdextension.InternStringName("set_point_disabled"),
			972357352,
		)
	})
	aStar2DMethodIsPointDisabled = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AStar2D"),
			gdextension.InternStringName("is_point_disabled"),
			1116898809,
		)
	})
	aStar2DMethodConnectPoints = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AStar2D"),
			gdextension.InternStringName("connect_points"),
			3710494224,
		)
	})
	aStar2DMethodDisconnectPoints = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AStar2D"),
			gdextension.InternStringName("disconnect_points"),
			3710494224,
		)
	})
	aStar2DMethodArePointsConnected = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AStar2D"),
			gdextension.InternStringName("are_points_connected"),
			2288175859,
		)
	})
	aStar2DMethodGetPointCount = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AStar2D"),
			gdextension.InternStringName("get_point_count"),
			3905245786,
		)
	})
	aStar2DMethodGetPointCapacity = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AStar2D"),
			gdextension.InternStringName("get_point_capacity"),
			3905245786,
		)
	})
	aStar2DMethodReserveSpace = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AStar2D"),
			gdextension.InternStringName("reserve_space"),
			1286410249,
		)
	})
	aStar2DMethodClear = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AStar2D"),
			gdextension.InternStringName("clear"),
			3218959716,
		)
	})
	aStar2DMethodGetClosestPoint = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AStar2D"),
			gdextension.InternStringName("get_closest_point"),
			2300324924,
		)
	})
	aStar2DMethodGetClosestPositionInSegment = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AStar2D"),
			gdextension.InternStringName("get_closest_position_in_segment"),
			2656412154,
		)
	})
	aStar2DMethodGetPointPath = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AStar2D"),
			gdextension.InternStringName("get_point_path"),
			3427490392,
		)
	})
	aStar2DMethodGetIdPath = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AStar2D"),
			gdextension.InternStringName("get_id_path"),
			3136199648,
		)
	})
)

// GetAvailablePointId mirrors the Godot AStar2D.get_available_point_id method.
func (self *AStar2D) GetAvailablePointId() int64 {
	var ret int64
	gdextension.CallMethodBindPtrCall(aStar2DMethodGetAvailablePointId(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// AddPoint mirrors the Godot AStar2D.add_point method.
func (self *AStar2D) AddPoint(id int64, position variant.Vector2, weight_scale float32) {
	tmp_weight_scale := float64(weight_scale)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&id)),
		gdextension.TypePtr(unsafe.Pointer(&position)),
		gdextension.TypePtr(unsafe.Pointer(&tmp_weight_scale)),
	}
	gdextension.CallMethodBindPtrCall(aStar2DMethodAddPoint(), self.Ptr(), args[:], nil)
}

// GetPointPosition mirrors the Godot AStar2D.get_point_position method.
func (self *AStar2D) GetPointPosition(id int64) variant.Vector2 {
	var ret variant.Vector2
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&id)),
	}
	gdextension.CallMethodBindPtrCall(aStar2DMethodGetPointPosition(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetPointPosition mirrors the Godot AStar2D.set_point_position method.
func (self *AStar2D) SetPointPosition(id int64, position variant.Vector2) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&id)),
		gdextension.TypePtr(unsafe.Pointer(&position)),
	}
	gdextension.CallMethodBindPtrCall(aStar2DMethodSetPointPosition(), self.Ptr(), args[:], nil)
}

// GetPointWeightScale mirrors the Godot AStar2D.get_point_weight_scale method.
func (self *AStar2D) GetPointWeightScale(id int64) float32 {
	var raw float64
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&id)),
	}
	gdextension.CallMethodBindPtrCall(aStar2DMethodGetPointWeightScale(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}

// SetPointWeightScale mirrors the Godot AStar2D.set_point_weight_scale method.
func (self *AStar2D) SetPointWeightScale(id int64, weight_scale float32) {
	tmp_weight_scale := float64(weight_scale)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&id)),
		gdextension.TypePtr(unsafe.Pointer(&tmp_weight_scale)),
	}
	gdextension.CallMethodBindPtrCall(aStar2DMethodSetPointWeightScale(), self.Ptr(), args[:], nil)
}

// RemovePoint mirrors the Godot AStar2D.remove_point method.
func (self *AStar2D) RemovePoint(id int64) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&id)),
	}
	gdextension.CallMethodBindPtrCall(aStar2DMethodRemovePoint(), self.Ptr(), args[:], nil)
}

// HasPoint mirrors the Godot AStar2D.has_point method.
func (self *AStar2D) HasPoint(id int64) bool {
	var ret bool
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&id)),
	}
	gdextension.CallMethodBindPtrCall(aStar2DMethodHasPoint(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// GetPointConnections mirrors the Godot AStar2D.get_point_connections method.
func (self *AStar2D) GetPointConnections(id int64) variant.PackedInt64Array {
	var ret variant.PackedInt64Array
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&id)),
	}
	gdextension.CallMethodBindPtrCall(aStar2DMethodGetPointConnections(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// GetPointIds mirrors the Godot AStar2D.get_point_ids method.
func (self *AStar2D) GetPointIds() variant.PackedInt64Array {
	var ret variant.PackedInt64Array
	gdextension.CallMethodBindPtrCall(aStar2DMethodGetPointIds(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetNeighborFilterEnabled mirrors the Godot AStar2D.set_neighbor_filter_enabled method.
func (self *AStar2D) SetNeighborFilterEnabled(enabled bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&enabled)),
	}
	gdextension.CallMethodBindPtrCall(aStar2DMethodSetNeighborFilterEnabled(), self.Ptr(), args[:], nil)
}

// IsNeighborFilterEnabled mirrors the Godot AStar2D.is_neighbor_filter_enabled method.
func (self *AStar2D) IsNeighborFilterEnabled() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(aStar2DMethodIsNeighborFilterEnabled(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetPointDisabled mirrors the Godot AStar2D.set_point_disabled method.
func (self *AStar2D) SetPointDisabled(id int64, disabled bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&id)),
		gdextension.TypePtr(unsafe.Pointer(&disabled)),
	}
	gdextension.CallMethodBindPtrCall(aStar2DMethodSetPointDisabled(), self.Ptr(), args[:], nil)
}

// IsPointDisabled mirrors the Godot AStar2D.is_point_disabled method.
func (self *AStar2D) IsPointDisabled(id int64) bool {
	var ret bool
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&id)),
	}
	gdextension.CallMethodBindPtrCall(aStar2DMethodIsPointDisabled(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// ConnectPoints mirrors the Godot AStar2D.connect_points method.
func (self *AStar2D) ConnectPoints(id int64, to_id int64, bidirectional bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&id)),
		gdextension.TypePtr(unsafe.Pointer(&to_id)),
		gdextension.TypePtr(unsafe.Pointer(&bidirectional)),
	}
	gdextension.CallMethodBindPtrCall(aStar2DMethodConnectPoints(), self.Ptr(), args[:], nil)
}

// DisconnectPoints mirrors the Godot AStar2D.disconnect_points method.
func (self *AStar2D) DisconnectPoints(id int64, to_id int64, bidirectional bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&id)),
		gdextension.TypePtr(unsafe.Pointer(&to_id)),
		gdextension.TypePtr(unsafe.Pointer(&bidirectional)),
	}
	gdextension.CallMethodBindPtrCall(aStar2DMethodDisconnectPoints(), self.Ptr(), args[:], nil)
}

// ArePointsConnected mirrors the Godot AStar2D.are_points_connected method.
func (self *AStar2D) ArePointsConnected(id int64, to_id int64, bidirectional bool) bool {
	var ret bool
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&id)),
		gdextension.TypePtr(unsafe.Pointer(&to_id)),
		gdextension.TypePtr(unsafe.Pointer(&bidirectional)),
	}
	gdextension.CallMethodBindPtrCall(aStar2DMethodArePointsConnected(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// GetPointCount mirrors the Godot AStar2D.get_point_count method.
func (self *AStar2D) GetPointCount() int64 {
	var ret int64
	gdextension.CallMethodBindPtrCall(aStar2DMethodGetPointCount(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// GetPointCapacity mirrors the Godot AStar2D.get_point_capacity method.
func (self *AStar2D) GetPointCapacity() int64 {
	var ret int64
	gdextension.CallMethodBindPtrCall(aStar2DMethodGetPointCapacity(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// ReserveSpace mirrors the Godot AStar2D.reserve_space method.
func (self *AStar2D) ReserveSpace(num_nodes int64) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&num_nodes)),
	}
	gdextension.CallMethodBindPtrCall(aStar2DMethodReserveSpace(), self.Ptr(), args[:], nil)
}

// Clear mirrors the Godot AStar2D.clear method.
func (self *AStar2D) Clear() {
	gdextension.CallMethodBindPtrCall(aStar2DMethodClear(), self.Ptr(), nil, nil)
}

// GetClosestPoint mirrors the Godot AStar2D.get_closest_point method.
func (self *AStar2D) GetClosestPoint(to_position variant.Vector2, include_disabled bool) int64 {
	var ret int64
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&to_position)),
		gdextension.TypePtr(unsafe.Pointer(&include_disabled)),
	}
	gdextension.CallMethodBindPtrCall(aStar2DMethodGetClosestPoint(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// GetClosestPositionInSegment mirrors the Godot AStar2D.get_closest_position_in_segment method.
func (self *AStar2D) GetClosestPositionInSegment(to_position variant.Vector2) variant.Vector2 {
	var ret variant.Vector2
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&to_position)),
	}
	gdextension.CallMethodBindPtrCall(aStar2DMethodGetClosestPositionInSegment(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// GetPointPath mirrors the Godot AStar2D.get_point_path method.
func (self *AStar2D) GetPointPath(from_id int64, to_id int64, allow_partial_path bool) variant.PackedVector2Array {
	var ret variant.PackedVector2Array
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&from_id)),
		gdextension.TypePtr(unsafe.Pointer(&to_id)),
		gdextension.TypePtr(unsafe.Pointer(&allow_partial_path)),
	}
	gdextension.CallMethodBindPtrCall(aStar2DMethodGetPointPath(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// GetIdPath mirrors the Godot AStar2D.get_id_path method.
func (self *AStar2D) GetIdPath(from_id int64, to_id int64, allow_partial_path bool) variant.PackedInt64Array {
	var ret variant.PackedInt64Array
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&from_id)),
		gdextension.TypePtr(unsafe.Pointer(&to_id)),
		gdextension.TypePtr(unsafe.Pointer(&allow_partial_path)),
	}
	gdextension.CallMethodBindPtrCall(aStar2DMethodGetIdPath(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}
