// Code generated by godot-go-bindgen. DO NOT EDIT.

package core

import (
	"sync"
	"unsafe"

	"github.com/legendary-code/godot-go/gdextension"
	"github.com/legendary-code/godot-go/variant"
)

// AudioServer mirrors the Godot engine class AudioServer.
type AudioServer struct {
	Object
}

// AudioServerFromPtr wraps an existing host-allocated GDExtensionObjectPtr in a
// *AudioServer. Returns nil on a nil input.
func AudioServerFromPtr(p gdextension.ObjectPtr) *AudioServer {
	if p == nil {
		return nil
	}
	ret := &AudioServer{}
	ret.BindPtr(p)
	return ret
}

// AudioServerSpeakerMode is the Godot AudioServerSpeakerMode enum.
type AudioServerSpeakerMode int64

const (
	AudioServer_SPEAKER_MODE_STEREO AudioServerSpeakerMode = 0
	AudioServer_SPEAKER_SURROUND_31 AudioServerSpeakerMode = 1
	AudioServer_SPEAKER_SURROUND_51 AudioServerSpeakerMode = 2
	AudioServer_SPEAKER_SURROUND_71 AudioServerSpeakerMode = 3
)

// AudioServerPlaybackType is the Godot AudioServerPlaybackType enum.
type AudioServerPlaybackType int64

const (
	AudioServer_PLAYBACK_TYPE_DEFAULT AudioServerPlaybackType = 0
	AudioServer_PLAYBACK_TYPE_STREAM  AudioServerPlaybackType = 1
	AudioServer_PLAYBACK_TYPE_SAMPLE  AudioServerPlaybackType = 2
	AudioServer_PLAYBACK_TYPE_MAX     AudioServerPlaybackType = 3
)

var (
	audioServerMethodSetBusCount = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("set_bus_count"),
			1286410249,
		)
	})
	audioServerMethodGetBusCount = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("get_bus_count"),
			3905245786,
		)
	})
	audioServerMethodRemoveBus = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("remove_bus"),
			1286410249,
		)
	})
	audioServerMethodAddBus = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("add_bus"),
			1025054187,
		)
	})
	audioServerMethodMoveBus = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("move_bus"),
			3937882851,
		)
	})
	audioServerMethodSetBusName = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("set_bus_name"),
			501894301,
		)
	})
	audioServerMethodGetBusName = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("get_bus_name"),
			844755477,
		)
	})
	audioServerMethodGetBusIndex = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("get_bus_index"),
			2458036349,
		)
	})
	audioServerMethodGetBusChannels = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("get_bus_channels"),
			923996154,
		)
	})
	audioServerMethodSetBusVolumeDb = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("set_bus_volume_db"),
			1602489585,
		)
	})
	audioServerMethodGetBusVolumeDb = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("get_bus_volume_db"),
			2339986948,
		)
	})
	audioServerMethodSetBusVolumeLinear = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("set_bus_volume_linear"),
			1602489585,
		)
	})
	audioServerMethodGetBusVolumeLinear = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("get_bus_volume_linear"),
			2339986948,
		)
	})
	audioServerMethodSetBusSend = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("set_bus_send"),
			3780747571,
		)
	})
	audioServerMethodGetBusSend = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("get_bus_send"),
			659327637,
		)
	})
	audioServerMethodSetBusSolo = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("set_bus_solo"),
			300928843,
		)
	})
	audioServerMethodIsBusSolo = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("is_bus_solo"),
			1116898809,
		)
	})
	audioServerMethodSetBusMute = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("set_bus_mute"),
			300928843,
		)
	})
	audioServerMethodIsBusMute = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("is_bus_mute"),
			1116898809,
		)
	})
	audioServerMethodSetBusBypassEffects = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("set_bus_bypass_effects"),
			300928843,
		)
	})
	audioServerMethodIsBusBypassingEffects = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("is_bus_bypassing_effects"),
			1116898809,
		)
	})
	audioServerMethodAddBusEffect = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("add_bus_effect"),
			4068819785,
		)
	})
	audioServerMethodRemoveBusEffect = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("remove_bus_effect"),
			3937882851,
		)
	})
	audioServerMethodGetBusEffectCount = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("get_bus_effect_count"),
			3744713108,
		)
	})
	audioServerMethodGetBusEffect = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("get_bus_effect"),
			726064442,
		)
	})
	audioServerMethodGetBusEffectInstance = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("get_bus_effect_instance"),
			1829771234,
		)
	})
	audioServerMethodSwapBusEffects = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("swap_bus_effects"),
			1649997291,
		)
	})
	audioServerMethodSetBusEffectEnabled = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("set_bus_effect_enabled"),
			1383440665,
		)
	})
	audioServerMethodIsBusEffectEnabled = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("is_bus_effect_enabled"),
			2522259332,
		)
	})
	audioServerMethodGetBusPeakVolumeLeftDb = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("get_bus_peak_volume_left_db"),
			3085491603,
		)
	})
	audioServerMethodGetBusPeakVolumeRightDb = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("get_bus_peak_volume_right_db"),
			3085491603,
		)
	})
	audioServerMethodSetPlaybackSpeedScale = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("set_playback_speed_scale"),
			373806689,
		)
	})
	audioServerMethodGetPlaybackSpeedScale = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("get_playback_speed_scale"),
			1740695150,
		)
	})
	audioServerMethodLock = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("lock"),
			3218959716,
		)
	})
	audioServerMethodUnlock = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("unlock"),
			3218959716,
		)
	})
	audioServerMethodGetSpeakerMode = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("get_speaker_mode"),
			2549190337,
		)
	})
	audioServerMethodGetMixRate = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("get_mix_rate"),
			1740695150,
		)
	})
	audioServerMethodGetInputMixRate = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("get_input_mix_rate"),
			1740695150,
		)
	})
	audioServerMethodGetDriverName = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("get_driver_name"),
			201670096,
		)
	})
	audioServerMethodGetOutputDeviceList = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("get_output_device_list"),
			2981934095,
		)
	})
	audioServerMethodGetOutputDevice = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("get_output_device"),
			2841200299,
		)
	})
	audioServerMethodSetOutputDevice = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("set_output_device"),
			83702148,
		)
	})
	audioServerMethodGetTimeToNextMix = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("get_time_to_next_mix"),
			1740695150,
		)
	})
	audioServerMethodGetTimeSinceLastMix = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("get_time_since_last_mix"),
			1740695150,
		)
	})
	audioServerMethodGetOutputLatency = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("get_output_latency"),
			1740695150,
		)
	})
	audioServerMethodGetInputDeviceList = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("get_input_device_list"),
			2981934095,
		)
	})
	audioServerMethodGetInputDevice = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("get_input_device"),
			2841200299,
		)
	})
	audioServerMethodSetInputDevice = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("set_input_device"),
			83702148,
		)
	})
	audioServerMethodSetInputDeviceActive = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("set_input_device_active"),
			1413768114,
		)
	})
	audioServerMethodGetInputFramesAvailable = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("get_input_frames_available"),
			2455072627,
		)
	})
	audioServerMethodGetInputBufferLengthFrames = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("get_input_buffer_length_frames"),
			2455072627,
		)
	})
	audioServerMethodGetInputFrames = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("get_input_frames"),
			2649534757,
		)
	})
	audioServerMethodSetBusLayout = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("set_bus_layout"),
			3319058824,
		)
	})
	audioServerMethodGenerateBusLayout = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("generate_bus_layout"),
			3769973890,
		)
	})
	audioServerMethodSetEnableTaggingUsedAudioStreams = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("set_enable_tagging_used_audio_streams"),
			2586408642,
		)
	})
	audioServerMethodIsStreamRegisteredAsSample = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("is_stream_registered_as_sample"),
			500225754,
		)
	})
	audioServerMethodRegisterStreamAsSample = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioServer"),
			gdextension.InternStringName("register_stream_as_sample"),
			2210767741,
		)
	})
)

// AudioServerSingleton returns the global AudioServer singleton registered under "AudioServer".
// The host owns the lifetime; do not call any destructor on it.
var AudioServerSingleton = sync.OnceValue(func() *AudioServer {
	return AudioServerFromPtr(gdextension.GetSingleton(gdextension.InternStringName("AudioServer")))
})

// SetBusCount mirrors the Godot AudioServer.set_bus_count method.
func (self *AudioServer) SetBusCount(amount int64) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&amount)),
	}
	gdextension.CallMethodBindPtrCall(audioServerMethodSetBusCount(), self.Ptr(), args[:], nil)
}

// GetBusCount mirrors the Godot AudioServer.get_bus_count method.
func (self *AudioServer) GetBusCount() int64 {
	var ret int64
	gdextension.CallMethodBindPtrCall(audioServerMethodGetBusCount(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// RemoveBus mirrors the Godot AudioServer.remove_bus method.
func (self *AudioServer) RemoveBus(index int64) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&index)),
	}
	gdextension.CallMethodBindPtrCall(audioServerMethodRemoveBus(), self.Ptr(), args[:], nil)
}

// AddBus mirrors the Godot AudioServer.add_bus method.
func (self *AudioServer) AddBus(at_position int64) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&at_position)),
	}
	gdextension.CallMethodBindPtrCall(audioServerMethodAddBus(), self.Ptr(), args[:], nil)
}

// MoveBus mirrors the Godot AudioServer.move_bus method.
func (self *AudioServer) MoveBus(index int64, to_index int64) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&index)),
		gdextension.TypePtr(unsafe.Pointer(&to_index)),
	}
	gdextension.CallMethodBindPtrCall(audioServerMethodMoveBus(), self.Ptr(), args[:], nil)
}

// SetBusName mirrors the Godot AudioServer.set_bus_name method.
func (self *AudioServer) SetBusName(bus_idx int64, name string) {
	tmp_name := variant.NewStringFromString(name)
	defer tmp_name.Destroy()

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&bus_idx)),
		gdextension.TypePtr(unsafe.Pointer(&tmp_name)),
	}
	gdextension.CallMethodBindPtrCall(audioServerMethodSetBusName(), self.Ptr(), args[:], nil)
}

// GetBusName mirrors the Godot AudioServer.get_bus_name method.
func (self *AudioServer) GetBusName(bus_idx int64) string {
	var raw variant.String
	defer raw.Destroy()
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&bus_idx)),
	}
	gdextension.CallMethodBindPtrCall(audioServerMethodGetBusName(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&raw)))
	return variant.StringToGo(&raw)
}

// GetBusIndex mirrors the Godot AudioServer.get_bus_index method.
func (self *AudioServer) GetBusIndex(bus_name string) int64 {
	var ret int64
	tmp_bus_name := variant.NewStringNameFromString(bus_name)
	defer tmp_bus_name.Destroy()

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_bus_name)),
	}
	gdextension.CallMethodBindPtrCall(audioServerMethodGetBusIndex(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// GetBusChannels mirrors the Godot AudioServer.get_bus_channels method.
func (self *AudioServer) GetBusChannels(bus_idx int64) int64 {
	var ret int64
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&bus_idx)),
	}
	gdextension.CallMethodBindPtrCall(audioServerMethodGetBusChannels(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetBusVolumeDb mirrors the Godot AudioServer.set_bus_volume_db method.
func (self *AudioServer) SetBusVolumeDb(bus_idx int64, volume_db float32) {
	tmp_volume_db := float64(volume_db)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&bus_idx)),
		gdextension.TypePtr(unsafe.Pointer(&tmp_volume_db)),
	}
	gdextension.CallMethodBindPtrCall(audioServerMethodSetBusVolumeDb(), self.Ptr(), args[:], nil)
}

// GetBusVolumeDb mirrors the Godot AudioServer.get_bus_volume_db method.
func (self *AudioServer) GetBusVolumeDb(bus_idx int64) float32 {
	var raw float64
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&bus_idx)),
	}
	gdextension.CallMethodBindPtrCall(audioServerMethodGetBusVolumeDb(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}

// SetBusVolumeLinear mirrors the Godot AudioServer.set_bus_volume_linear method.
func (self *AudioServer) SetBusVolumeLinear(bus_idx int64, volume_linear float32) {
	tmp_volume_linear := float64(volume_linear)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&bus_idx)),
		gdextension.TypePtr(unsafe.Pointer(&tmp_volume_linear)),
	}
	gdextension.CallMethodBindPtrCall(audioServerMethodSetBusVolumeLinear(), self.Ptr(), args[:], nil)
}

// GetBusVolumeLinear mirrors the Godot AudioServer.get_bus_volume_linear method.
func (self *AudioServer) GetBusVolumeLinear(bus_idx int64) float32 {
	var raw float64
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&bus_idx)),
	}
	gdextension.CallMethodBindPtrCall(audioServerMethodGetBusVolumeLinear(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}

// SetBusSend mirrors the Godot AudioServer.set_bus_send method.
func (self *AudioServer) SetBusSend(bus_idx int64, send string) {
	tmp_send := variant.NewStringNameFromString(send)
	defer tmp_send.Destroy()

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&bus_idx)),
		gdextension.TypePtr(unsafe.Pointer(&tmp_send)),
	}
	gdextension.CallMethodBindPtrCall(audioServerMethodSetBusSend(), self.Ptr(), args[:], nil)
}

// GetBusSend mirrors the Godot AudioServer.get_bus_send method.
func (self *AudioServer) GetBusSend(bus_idx int64) string {
	var raw variant.StringName
	defer raw.Destroy()
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&bus_idx)),
	}
	gdextension.CallMethodBindPtrCall(audioServerMethodGetBusSend(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&raw)))
	return variant.StringNameToGo(&raw)
}

// SetBusSolo mirrors the Godot AudioServer.set_bus_solo method.
func (self *AudioServer) SetBusSolo(bus_idx int64, enable bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&bus_idx)),
		gdextension.TypePtr(unsafe.Pointer(&enable)),
	}
	gdextension.CallMethodBindPtrCall(audioServerMethodSetBusSolo(), self.Ptr(), args[:], nil)
}

// IsBusSolo mirrors the Godot AudioServer.is_bus_solo method.
func (self *AudioServer) IsBusSolo(bus_idx int64) bool {
	var ret bool
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&bus_idx)),
	}
	gdextension.CallMethodBindPtrCall(audioServerMethodIsBusSolo(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetBusMute mirrors the Godot AudioServer.set_bus_mute method.
func (self *AudioServer) SetBusMute(bus_idx int64, enable bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&bus_idx)),
		gdextension.TypePtr(unsafe.Pointer(&enable)),
	}
	gdextension.CallMethodBindPtrCall(audioServerMethodSetBusMute(), self.Ptr(), args[:], nil)
}

// IsBusMute mirrors the Godot AudioServer.is_bus_mute method.
func (self *AudioServer) IsBusMute(bus_idx int64) bool {
	var ret bool
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&bus_idx)),
	}
	gdextension.CallMethodBindPtrCall(audioServerMethodIsBusMute(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetBusBypassEffects mirrors the Godot AudioServer.set_bus_bypass_effects method.
func (self *AudioServer) SetBusBypassEffects(bus_idx int64, enable bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&bus_idx)),
		gdextension.TypePtr(unsafe.Pointer(&enable)),
	}
	gdextension.CallMethodBindPtrCall(audioServerMethodSetBusBypassEffects(), self.Ptr(), args[:], nil)
}

// IsBusBypassingEffects mirrors the Godot AudioServer.is_bus_bypassing_effects method.
func (self *AudioServer) IsBusBypassingEffects(bus_idx int64) bool {
	var ret bool
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&bus_idx)),
	}
	gdextension.CallMethodBindPtrCall(audioServerMethodIsBusBypassingEffects(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// AddBusEffect mirrors the Godot AudioServer.add_bus_effect method.
func (self *AudioServer) AddBusEffect(bus_idx int64, effect *AudioEffect, at_position int64) {
	var tmp_effect gdextension.ObjectPtr
	if effect != nil {
		tmp_effect = effect.Ptr()
	}

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&bus_idx)),
		gdextension.TypePtr(unsafe.Pointer(&tmp_effect)),
		gdextension.TypePtr(unsafe.Pointer(&at_position)),
	}
	gdextension.CallMethodBindPtrCall(audioServerMethodAddBusEffect(), self.Ptr(), args[:], nil)
}

// RemoveBusEffect mirrors the Godot AudioServer.remove_bus_effect method.
func (self *AudioServer) RemoveBusEffect(bus_idx int64, effect_idx int64) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&bus_idx)),
		gdextension.TypePtr(unsafe.Pointer(&effect_idx)),
	}
	gdextension.CallMethodBindPtrCall(audioServerMethodRemoveBusEffect(), self.Ptr(), args[:], nil)
}

// GetBusEffectCount mirrors the Godot AudioServer.get_bus_effect_count method.
func (self *AudioServer) GetBusEffectCount(bus_idx int64) int64 {
	var ret int64
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&bus_idx)),
	}
	gdextension.CallMethodBindPtrCall(audioServerMethodGetBusEffectCount(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// GetBusEffect mirrors the Godot AudioServer.get_bus_effect method.
func (self *AudioServer) GetBusEffect(bus_idx int64, effect_idx int64) *AudioEffect {
	var ret gdextension.ObjectPtr
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&bus_idx)),
		gdextension.TypePtr(unsafe.Pointer(&effect_idx)),
	}
	gdextension.CallMethodBindPtrCall(audioServerMethodGetBusEffect(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return AudioEffectFromPtr(ret)
}

// GetBusEffectInstance mirrors the Godot AudioServer.get_bus_effect_instance method.
func (self *AudioServer) GetBusEffectInstance(bus_idx int64, effect_idx int64, channel int64) *AudioEffectInstance {
	var ret gdextension.ObjectPtr
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&bus_idx)),
		gdextension.TypePtr(unsafe.Pointer(&effect_idx)),
		gdextension.TypePtr(unsafe.Pointer(&channel)),
	}
	gdextension.CallMethodBindPtrCall(audioServerMethodGetBusEffectInstance(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return AudioEffectInstanceFromPtr(ret)
}

// SwapBusEffects mirrors the Godot AudioServer.swap_bus_effects method.
func (self *AudioServer) SwapBusEffects(bus_idx int64, effect_idx int64, by_effect_idx int64) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&bus_idx)),
		gdextension.TypePtr(unsafe.Pointer(&effect_idx)),
		gdextension.TypePtr(unsafe.Pointer(&by_effect_idx)),
	}
	gdextension.CallMethodBindPtrCall(audioServerMethodSwapBusEffects(), self.Ptr(), args[:], nil)
}

// SetBusEffectEnabled mirrors the Godot AudioServer.set_bus_effect_enabled method.
func (self *AudioServer) SetBusEffectEnabled(bus_idx int64, effect_idx int64, enabled bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&bus_idx)),
		gdextension.TypePtr(unsafe.Pointer(&effect_idx)),
		gdextension.TypePtr(unsafe.Pointer(&enabled)),
	}
	gdextension.CallMethodBindPtrCall(audioServerMethodSetBusEffectEnabled(), self.Ptr(), args[:], nil)
}

// IsBusEffectEnabled mirrors the Godot AudioServer.is_bus_effect_enabled method.
func (self *AudioServer) IsBusEffectEnabled(bus_idx int64, effect_idx int64) bool {
	var ret bool
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&bus_idx)),
		gdextension.TypePtr(unsafe.Pointer(&effect_idx)),
	}
	gdextension.CallMethodBindPtrCall(audioServerMethodIsBusEffectEnabled(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// GetBusPeakVolumeLeftDb mirrors the Godot AudioServer.get_bus_peak_volume_left_db method.
func (self *AudioServer) GetBusPeakVolumeLeftDb(bus_idx int64, channel int64) float32 {
	var raw float64
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&bus_idx)),
		gdextension.TypePtr(unsafe.Pointer(&channel)),
	}
	gdextension.CallMethodBindPtrCall(audioServerMethodGetBusPeakVolumeLeftDb(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}

// GetBusPeakVolumeRightDb mirrors the Godot AudioServer.get_bus_peak_volume_right_db method.
func (self *AudioServer) GetBusPeakVolumeRightDb(bus_idx int64, channel int64) float32 {
	var raw float64
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&bus_idx)),
		gdextension.TypePtr(unsafe.Pointer(&channel)),
	}
	gdextension.CallMethodBindPtrCall(audioServerMethodGetBusPeakVolumeRightDb(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}

// SetPlaybackSpeedScale mirrors the Godot AudioServer.set_playback_speed_scale method.
func (self *AudioServer) SetPlaybackSpeedScale(scale float32) {
	tmp_scale := float64(scale)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_scale)),
	}
	gdextension.CallMethodBindPtrCall(audioServerMethodSetPlaybackSpeedScale(), self.Ptr(), args[:], nil)
}

// GetPlaybackSpeedScale mirrors the Godot AudioServer.get_playback_speed_scale method.
func (self *AudioServer) GetPlaybackSpeedScale() float32 {
	var raw float64
	gdextension.CallMethodBindPtrCall(audioServerMethodGetPlaybackSpeedScale(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}

// Lock mirrors the Godot AudioServer.lock method.
func (self *AudioServer) Lock() {
	gdextension.CallMethodBindPtrCall(audioServerMethodLock(), self.Ptr(), nil, nil)
}

// Unlock mirrors the Godot AudioServer.unlock method.
func (self *AudioServer) Unlock() {
	gdextension.CallMethodBindPtrCall(audioServerMethodUnlock(), self.Ptr(), nil, nil)
}

// GetSpeakerMode mirrors the Godot AudioServer.get_speaker_mode method.
func (self *AudioServer) GetSpeakerMode() AudioServerSpeakerMode {
	var ret int64
	gdextension.CallMethodBindPtrCall(audioServerMethodGetSpeakerMode(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return AudioServerSpeakerMode(ret)
}

// GetMixRate mirrors the Godot AudioServer.get_mix_rate method.
func (self *AudioServer) GetMixRate() float32 {
	var raw float64
	gdextension.CallMethodBindPtrCall(audioServerMethodGetMixRate(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}

// GetInputMixRate mirrors the Godot AudioServer.get_input_mix_rate method.
func (self *AudioServer) GetInputMixRate() float32 {
	var raw float64
	gdextension.CallMethodBindPtrCall(audioServerMethodGetInputMixRate(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}

// GetDriverName mirrors the Godot AudioServer.get_driver_name method.
func (self *AudioServer) GetDriverName() string {
	var raw variant.String
	defer raw.Destroy()
	gdextension.CallMethodBindPtrCall(audioServerMethodGetDriverName(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return variant.StringToGo(&raw)
}

// GetOutputDeviceList mirrors the Godot AudioServer.get_output_device_list method.
func (self *AudioServer) GetOutputDeviceList() variant.PackedStringArray {
	var ret variant.PackedStringArray
	gdextension.CallMethodBindPtrCall(audioServerMethodGetOutputDeviceList(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// GetOutputDevice mirrors the Godot AudioServer.get_output_device method.
func (self *AudioServer) GetOutputDevice() string {
	var raw variant.String
	defer raw.Destroy()
	gdextension.CallMethodBindPtrCall(audioServerMethodGetOutputDevice(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return variant.StringToGo(&raw)
}

// SetOutputDevice mirrors the Godot AudioServer.set_output_device method.
func (self *AudioServer) SetOutputDevice(name string) {
	tmp_name := variant.NewStringFromString(name)
	defer tmp_name.Destroy()

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_name)),
	}
	gdextension.CallMethodBindPtrCall(audioServerMethodSetOutputDevice(), self.Ptr(), args[:], nil)
}

// GetTimeToNextMix mirrors the Godot AudioServer.get_time_to_next_mix method.
func (self *AudioServer) GetTimeToNextMix() float32 {
	var raw float64
	gdextension.CallMethodBindPtrCall(audioServerMethodGetTimeToNextMix(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}

// GetTimeSinceLastMix mirrors the Godot AudioServer.get_time_since_last_mix method.
func (self *AudioServer) GetTimeSinceLastMix() float32 {
	var raw float64
	gdextension.CallMethodBindPtrCall(audioServerMethodGetTimeSinceLastMix(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}

// GetOutputLatency mirrors the Godot AudioServer.get_output_latency method.
func (self *AudioServer) GetOutputLatency() float32 {
	var raw float64
	gdextension.CallMethodBindPtrCall(audioServerMethodGetOutputLatency(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}

// GetInputDeviceList mirrors the Godot AudioServer.get_input_device_list method.
func (self *AudioServer) GetInputDeviceList() variant.PackedStringArray {
	var ret variant.PackedStringArray
	gdextension.CallMethodBindPtrCall(audioServerMethodGetInputDeviceList(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// GetInputDevice mirrors the Godot AudioServer.get_input_device method.
func (self *AudioServer) GetInputDevice() string {
	var raw variant.String
	defer raw.Destroy()
	gdextension.CallMethodBindPtrCall(audioServerMethodGetInputDevice(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return variant.StringToGo(&raw)
}

// SetInputDevice mirrors the Godot AudioServer.set_input_device method.
func (self *AudioServer) SetInputDevice(name string) {
	tmp_name := variant.NewStringFromString(name)
	defer tmp_name.Destroy()

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_name)),
	}
	gdextension.CallMethodBindPtrCall(audioServerMethodSetInputDevice(), self.Ptr(), args[:], nil)
}

// SetInputDeviceActive mirrors the Godot AudioServer.set_input_device_active method.
func (self *AudioServer) SetInputDeviceActive(active bool) int64 {
	var ret int64
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&active)),
	}
	gdextension.CallMethodBindPtrCall(audioServerMethodSetInputDeviceActive(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// GetInputFramesAvailable mirrors the Godot AudioServer.get_input_frames_available method.
func (self *AudioServer) GetInputFramesAvailable() int64 {
	var ret int64
	gdextension.CallMethodBindPtrCall(audioServerMethodGetInputFramesAvailable(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// GetInputBufferLengthFrames mirrors the Godot AudioServer.get_input_buffer_length_frames method.
func (self *AudioServer) GetInputBufferLengthFrames() int64 {
	var ret int64
	gdextension.CallMethodBindPtrCall(audioServerMethodGetInputBufferLengthFrames(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// GetInputFrames mirrors the Godot AudioServer.get_input_frames method.
func (self *AudioServer) GetInputFrames(frames int64) variant.PackedVector2Array {
	var ret variant.PackedVector2Array
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&frames)),
	}
	gdextension.CallMethodBindPtrCall(audioServerMethodGetInputFrames(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetBusLayout mirrors the Godot AudioServer.set_bus_layout method.
func (self *AudioServer) SetBusLayout(bus_layout *AudioBusLayout) {
	var tmp_bus_layout gdextension.ObjectPtr
	if bus_layout != nil {
		tmp_bus_layout = bus_layout.Ptr()
	}

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_bus_layout)),
	}
	gdextension.CallMethodBindPtrCall(audioServerMethodSetBusLayout(), self.Ptr(), args[:], nil)
}

// GenerateBusLayout mirrors the Godot AudioServer.generate_bus_layout method.
func (self *AudioServer) GenerateBusLayout() *AudioBusLayout {
	var ret gdextension.ObjectPtr
	gdextension.CallMethodBindPtrCall(audioServerMethodGenerateBusLayout(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return AudioBusLayoutFromPtr(ret)
}

// SetEnableTaggingUsedAudioStreams mirrors the Godot AudioServer.set_enable_tagging_used_audio_streams method.
func (self *AudioServer) SetEnableTaggingUsedAudioStreams(enable bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&enable)),
	}
	gdextension.CallMethodBindPtrCall(audioServerMethodSetEnableTaggingUsedAudioStreams(), self.Ptr(), args[:], nil)
}

// IsStreamRegisteredAsSample mirrors the Godot AudioServer.is_stream_registered_as_sample method.
func (self *AudioServer) IsStreamRegisteredAsSample(stream *AudioStream) bool {
	var ret bool
	var tmp_stream gdextension.ObjectPtr
	if stream != nil {
		tmp_stream = stream.Ptr()
	}

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_stream)),
	}
	gdextension.CallMethodBindPtrCall(audioServerMethodIsStreamRegisteredAsSample(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// RegisterStreamAsSample mirrors the Godot AudioServer.register_stream_as_sample method.
func (self *AudioServer) RegisterStreamAsSample(stream *AudioStream) {
	var tmp_stream gdextension.ObjectPtr
	if stream != nil {
		tmp_stream = stream.Ptr()
	}

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_stream)),
	}
	gdextension.CallMethodBindPtrCall(audioServerMethodRegisterStreamAsSample(), self.Ptr(), args[:], nil)
}
