// Code generated by godot-go-bindgen. DO NOT EDIT.

package core

import (
	"github.com/legendary-code/godot-go/internal/gdextension"
)

// AudioStreamPlaybackSynchronized mirrors the Godot engine class AudioStreamPlaybackSynchronized.
type AudioStreamPlaybackSynchronized struct {
	AudioStreamPlayback
}

// AudioStreamPlaybackSynchronizedFromPtr wraps an existing host-allocated GDExtensionObjectPtr in a
// *AudioStreamPlaybackSynchronized. Returns nil on a nil input.
func AudioStreamPlaybackSynchronizedFromPtr(p gdextension.ObjectPtr) *AudioStreamPlaybackSynchronized {
	if p == nil {
		return nil
	}
	ret := &AudioStreamPlaybackSynchronized{}
	ret.BindPtr(p)
	return ret
}
