// Code generated by godot-go-bindgen. DO NOT EDIT.

package core

import (
	"runtime"
	"sync"
	"unsafe"

	"github.com/legendary-code/godot-go/internal/gdextension"
)

// AudioStreamPlaylist mirrors the Godot engine class AudioStreamPlaylist.
type AudioStreamPlaylist struct {
	AudioStream
}

// AudioStreamPlaylistFromPtr wraps an existing host-allocated GDExtensionObjectPtr in a
// *AudioStreamPlaylist. Returns nil on a nil input. AudioStreamPlaylist descends from RefCounted, so the
// returned wrapper carries a Go finalizer that drops one engine
// reference (via Unreference, dispatched on the main thread) when
// Go's GC determines the wrapper is unreachable. Users who want
// deterministic free can call ret.Unreference() directly — the
// finalizer is harmless after the refcount hits zero.
func AudioStreamPlaylistFromPtr(p gdextension.ObjectPtr) *AudioStreamPlaylist {
	if p == nil {
		return nil
	}
	ret := &AudioStreamPlaylist{}
	ret.BindPtr(p)
	runtime.SetFinalizer(ret, func(r *AudioStreamPlaylist) {
		gdextension.RunOnMain(func() { r.Unreference() })
	})
	return ret
}

const (
	AudioStreamPlaylist_MAX_STREAMS = 64
)

var (
	audioStreamPlaylistMethodSetStreamCount = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioStreamPlaylist"),
			gdextension.InternStringName("set_stream_count"),
			1286410249,
		)
	})
	audioStreamPlaylistMethodGetStreamCount = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioStreamPlaylist"),
			gdextension.InternStringName("get_stream_count"),
			3905245786,
		)
	})
	audioStreamPlaylistMethodGetBpm = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioStreamPlaylist"),
			gdextension.InternStringName("get_bpm"),
			1740695150,
		)
	})
	audioStreamPlaylistMethodSetListStream = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioStreamPlaylist"),
			gdextension.InternStringName("set_list_stream"),
			111075094,
		)
	})
	audioStreamPlaylistMethodGetListStream = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioStreamPlaylist"),
			gdextension.InternStringName("get_list_stream"),
			2739380747,
		)
	})
	audioStreamPlaylistMethodSetShuffle = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioStreamPlaylist"),
			gdextension.InternStringName("set_shuffle"),
			2586408642,
		)
	})
	audioStreamPlaylistMethodGetShuffle = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioStreamPlaylist"),
			gdextension.InternStringName("get_shuffle"),
			36873697,
		)
	})
	audioStreamPlaylistMethodSetFadeTime = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioStreamPlaylist"),
			gdextension.InternStringName("set_fade_time"),
			373806689,
		)
	})
	audioStreamPlaylistMethodGetFadeTime = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioStreamPlaylist"),
			gdextension.InternStringName("get_fade_time"),
			1740695150,
		)
	})
	audioStreamPlaylistMethodSetLoop = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioStreamPlaylist"),
			gdextension.InternStringName("set_loop"),
			2586408642,
		)
	})
	audioStreamPlaylistMethodHasLoop = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioStreamPlaylist"),
			gdextension.InternStringName("has_loop"),
			36873697,
		)
	})
)

// SetStreamCount mirrors the Godot AudioStreamPlaylist.set_stream_count method.
func (self *AudioStreamPlaylist) SetStreamCount(stream_count int64) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&stream_count)),
	}
	gdextension.CallMethodBindPtrCall(audioStreamPlaylistMethodSetStreamCount(), self.Ptr(), args[:], nil)
}

// GetStreamCount mirrors the Godot AudioStreamPlaylist.get_stream_count method.
func (self *AudioStreamPlaylist) GetStreamCount() int64 {
	var ret int64
	gdextension.CallMethodBindPtrCall(audioStreamPlaylistMethodGetStreamCount(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// GetBpm mirrors the Godot AudioStreamPlaylist.get_bpm method.
func (self *AudioStreamPlaylist) GetBpm() float32 {
	var raw float64
	gdextension.CallMethodBindPtrCall(audioStreamPlaylistMethodGetBpm(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}

// SetListStream mirrors the Godot AudioStreamPlaylist.set_list_stream method.
func (self *AudioStreamPlaylist) SetListStream(stream_index int64, audio_stream *AudioStream) {
	var tmp_audio_stream gdextension.ObjectPtr
	if audio_stream != nil {
		tmp_audio_stream = audio_stream.Ptr()
	}

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&stream_index)),
		gdextension.TypePtr(unsafe.Pointer(&tmp_audio_stream)),
	}
	gdextension.CallMethodBindPtrCall(audioStreamPlaylistMethodSetListStream(), self.Ptr(), args[:], nil)
}

// GetListStream mirrors the Godot AudioStreamPlaylist.get_list_stream method.
func (self *AudioStreamPlaylist) GetListStream(stream_index int64) *AudioStream {
	var ret gdextension.ObjectPtr
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&stream_index)),
	}
	gdextension.CallMethodBindPtrCall(audioStreamPlaylistMethodGetListStream(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return AudioStreamFromPtr(ret)
}

// SetShuffle mirrors the Godot AudioStreamPlaylist.set_shuffle method.
func (self *AudioStreamPlaylist) SetShuffle(shuffle bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&shuffle)),
	}
	gdextension.CallMethodBindPtrCall(audioStreamPlaylistMethodSetShuffle(), self.Ptr(), args[:], nil)
}

// GetShuffle mirrors the Godot AudioStreamPlaylist.get_shuffle method.
func (self *AudioStreamPlaylist) GetShuffle() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(audioStreamPlaylistMethodGetShuffle(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetFadeTime mirrors the Godot AudioStreamPlaylist.set_fade_time method.
func (self *AudioStreamPlaylist) SetFadeTime(dec float32) {
	tmp_dec := float64(dec)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_dec)),
	}
	gdextension.CallMethodBindPtrCall(audioStreamPlaylistMethodSetFadeTime(), self.Ptr(), args[:], nil)
}

// GetFadeTime mirrors the Godot AudioStreamPlaylist.get_fade_time method.
func (self *AudioStreamPlaylist) GetFadeTime() float32 {
	var raw float64
	gdextension.CallMethodBindPtrCall(audioStreamPlaylistMethodGetFadeTime(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}

// SetLoop mirrors the Godot AudioStreamPlaylist.set_loop method.
func (self *AudioStreamPlaylist) SetLoop(loop bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&loop)),
	}
	gdextension.CallMethodBindPtrCall(audioStreamPlaylistMethodSetLoop(), self.Ptr(), args[:], nil)
}

// HasLoop mirrors the Godot AudioStreamPlaylist.has_loop method.
func (self *AudioStreamPlaylist) HasLoop() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(audioStreamPlaylistMethodHasLoop(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}
