// Code generated by godot-go-bindgen. DO NOT EDIT.

package core

import (
	"sync"
	"unsafe"

	"github.com/legendary-code/godot-go/gdextension"
)

// AudioListener2D mirrors the Godot engine class AudioListener2D.
type AudioListener2D struct {
	Node2D
}

// AudioListener2DFromPtr wraps an existing host-allocated GDExtensionObjectPtr in a
// *AudioListener2D. Returns nil on a nil input.
func AudioListener2DFromPtr(p gdextension.ObjectPtr) *AudioListener2D {
	if p == nil {
		return nil
	}
	ret := &AudioListener2D{}
	ret.BindPtr(p)
	return ret
}

var (
	audioListener2DMethodMakeCurrent = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioListener2D"),
			gdextension.InternStringName("make_current"),
			3218959716,
		)
	})
	audioListener2DMethodClearCurrent = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioListener2D"),
			gdextension.InternStringName("clear_current"),
			3218959716,
		)
	})
	audioListener2DMethodIsCurrent = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("AudioListener2D"),
			gdextension.InternStringName("is_current"),
			36873697,
		)
	})
)

// MakeCurrent mirrors the Godot AudioListener2D.make_current method.
func (self *AudioListener2D) MakeCurrent() {
	gdextension.CallMethodBindPtrCall(audioListener2DMethodMakeCurrent(), self.Ptr(), nil, nil)
}

// ClearCurrent mirrors the Godot AudioListener2D.clear_current method.
func (self *AudioListener2D) ClearCurrent() {
	gdextension.CallMethodBindPtrCall(audioListener2DMethodClearCurrent(), self.Ptr(), nil, nil)
}

// IsCurrent mirrors the Godot AudioListener2D.is_current method.
func (self *AudioListener2D) IsCurrent() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(audioListener2DMethodIsCurrent(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}
