// Code generated by godot-go-bindgen. DO NOT EDIT.

package core

import (
	"sync"
	"unsafe"

	"github.com/legendary-code/godot-go/gdextension"
	"github.com/legendary-code/godot-go/variant"
)

// Button mirrors the Godot engine class Button.
type Button struct {
	BaseButton
}

// ButtonFromPtr wraps an existing host-allocated GDExtensionObjectPtr in a
// *Button. Returns nil on a nil input.
func ButtonFromPtr(p gdextension.ObjectPtr) *Button {
	if p == nil {
		return nil
	}
	ret := &Button{}
	ret.BindPtr(p)
	return ret
}

var (
	buttonMethodSetText = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("Button"),
			gdextension.InternStringName("set_text"),
			83702148,
		)
	})
	buttonMethodGetText = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("Button"),
			gdextension.InternStringName("get_text"),
			201670096,
		)
	})
	buttonMethodSetTextOverrunBehavior = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("Button"),
			gdextension.InternStringName("set_text_overrun_behavior"),
			1008890932,
		)
	})
	buttonMethodGetTextOverrunBehavior = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("Button"),
			gdextension.InternStringName("get_text_overrun_behavior"),
			3779142101,
		)
	})
	buttonMethodSetAutowrapMode = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("Button"),
			gdextension.InternStringName("set_autowrap_mode"),
			3289138044,
		)
	})
	buttonMethodGetAutowrapMode = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("Button"),
			gdextension.InternStringName("get_autowrap_mode"),
			1549071663,
		)
	})
	buttonMethodSetAutowrapTrimFlags = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("Button"),
			gdextension.InternStringName("set_autowrap_trim_flags"),
			2809697122,
		)
	})
	buttonMethodGetAutowrapTrimFlags = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("Button"),
			gdextension.InternStringName("get_autowrap_trim_flags"),
			2340632602,
		)
	})
	buttonMethodSetTextDirection = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("Button"),
			gdextension.InternStringName("set_text_direction"),
			119160795,
		)
	})
	buttonMethodGetTextDirection = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("Button"),
			gdextension.InternStringName("get_text_direction"),
			797257663,
		)
	})
	buttonMethodSetLanguage = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("Button"),
			gdextension.InternStringName("set_language"),
			83702148,
		)
	})
	buttonMethodGetLanguage = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("Button"),
			gdextension.InternStringName("get_language"),
			201670096,
		)
	})
	buttonMethodSetButtonIcon = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("Button"),
			gdextension.InternStringName("set_button_icon"),
			4051416890,
		)
	})
	buttonMethodGetButtonIcon = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("Button"),
			gdextension.InternStringName("get_button_icon"),
			3635182373,
		)
	})
	buttonMethodSetFlat = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("Button"),
			gdextension.InternStringName("set_flat"),
			2586408642,
		)
	})
	buttonMethodIsFlat = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("Button"),
			gdextension.InternStringName("is_flat"),
			36873697,
		)
	})
	buttonMethodSetClipText = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("Button"),
			gdextension.InternStringName("set_clip_text"),
			2586408642,
		)
	})
	buttonMethodGetClipText = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("Button"),
			gdextension.InternStringName("get_clip_text"),
			36873697,
		)
	})
	buttonMethodSetTextAlignment = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("Button"),
			gdextension.InternStringName("set_text_alignment"),
			2312603777,
		)
	})
	buttonMethodGetTextAlignment = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("Button"),
			gdextension.InternStringName("get_text_alignment"),
			341400642,
		)
	})
	buttonMethodSetIconAlignment = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("Button"),
			gdextension.InternStringName("set_icon_alignment"),
			2312603777,
		)
	})
	buttonMethodGetIconAlignment = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("Button"),
			gdextension.InternStringName("get_icon_alignment"),
			341400642,
		)
	})
	buttonMethodSetVerticalIconAlignment = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("Button"),
			gdextension.InternStringName("set_vertical_icon_alignment"),
			1796458609,
		)
	})
	buttonMethodGetVerticalIconAlignment = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("Button"),
			gdextension.InternStringName("get_vertical_icon_alignment"),
			3274884059,
		)
	})
	buttonMethodSetExpandIcon = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("Button"),
			gdextension.InternStringName("set_expand_icon"),
			2586408642,
		)
	})
	buttonMethodIsExpandIcon = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("Button"),
			gdextension.InternStringName("is_expand_icon"),
			36873697,
		)
	})
)

// SetText mirrors the Godot Button.set_text method.
func (self *Button) SetText(text string) {
	tmp_text := variant.NewStringFromString(text)
	defer tmp_text.Destroy()

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_text)),
	}
	gdextension.CallMethodBindPtrCall(buttonMethodSetText(), self.Ptr(), args[:], nil)
}

// GetText mirrors the Godot Button.get_text method.
func (self *Button) GetText() string {
	var raw variant.String
	defer raw.Destroy()
	gdextension.CallMethodBindPtrCall(buttonMethodGetText(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return variant.StringToGo(&raw)
}

// SetTextOverrunBehavior mirrors the Godot Button.set_text_overrun_behavior method.
func (self *Button) SetTextOverrunBehavior(overrun_behavior TextServerOverrunBehavior) {
	tmp_overrun_behavior := int64(overrun_behavior)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_overrun_behavior)),
	}
	gdextension.CallMethodBindPtrCall(buttonMethodSetTextOverrunBehavior(), self.Ptr(), args[:], nil)
}

// GetTextOverrunBehavior mirrors the Godot Button.get_text_overrun_behavior method.
func (self *Button) GetTextOverrunBehavior() TextServerOverrunBehavior {
	var ret int64
	gdextension.CallMethodBindPtrCall(buttonMethodGetTextOverrunBehavior(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return TextServerOverrunBehavior(ret)
}

// SetAutowrapMode mirrors the Godot Button.set_autowrap_mode method.
func (self *Button) SetAutowrapMode(autowrap_mode TextServerAutowrapMode) {
	tmp_autowrap_mode := int64(autowrap_mode)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_autowrap_mode)),
	}
	gdextension.CallMethodBindPtrCall(buttonMethodSetAutowrapMode(), self.Ptr(), args[:], nil)
}

// GetAutowrapMode mirrors the Godot Button.get_autowrap_mode method.
func (self *Button) GetAutowrapMode() TextServerAutowrapMode {
	var ret int64
	gdextension.CallMethodBindPtrCall(buttonMethodGetAutowrapMode(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return TextServerAutowrapMode(ret)
}

// SetAutowrapTrimFlags mirrors the Godot Button.set_autowrap_trim_flags method.
func (self *Button) SetAutowrapTrimFlags(autowrap_trim_flags TextServerLineBreakFlag) {
	tmp_autowrap_trim_flags := int64(autowrap_trim_flags)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_autowrap_trim_flags)),
	}
	gdextension.CallMethodBindPtrCall(buttonMethodSetAutowrapTrimFlags(), self.Ptr(), args[:], nil)
}

// GetAutowrapTrimFlags mirrors the Godot Button.get_autowrap_trim_flags method.
func (self *Button) GetAutowrapTrimFlags() TextServerLineBreakFlag {
	var ret int64
	gdextension.CallMethodBindPtrCall(buttonMethodGetAutowrapTrimFlags(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return TextServerLineBreakFlag(ret)
}

// SetTextDirection mirrors the Godot Button.set_text_direction method.
func (self *Button) SetTextDirection(direction ControlTextDirection) {
	tmp_direction := int64(direction)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_direction)),
	}
	gdextension.CallMethodBindPtrCall(buttonMethodSetTextDirection(), self.Ptr(), args[:], nil)
}

// GetTextDirection mirrors the Godot Button.get_text_direction method.
func (self *Button) GetTextDirection() ControlTextDirection {
	var ret int64
	gdextension.CallMethodBindPtrCall(buttonMethodGetTextDirection(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ControlTextDirection(ret)
}

// SetLanguage mirrors the Godot Button.set_language method.
func (self *Button) SetLanguage(language string) {
	tmp_language := variant.NewStringFromString(language)
	defer tmp_language.Destroy()

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_language)),
	}
	gdextension.CallMethodBindPtrCall(buttonMethodSetLanguage(), self.Ptr(), args[:], nil)
}

// GetLanguage mirrors the Godot Button.get_language method.
func (self *Button) GetLanguage() string {
	var raw variant.String
	defer raw.Destroy()
	gdextension.CallMethodBindPtrCall(buttonMethodGetLanguage(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return variant.StringToGo(&raw)
}

// SetButtonIcon mirrors the Godot Button.set_button_icon method.
func (self *Button) SetButtonIcon(texture *Texture2D) {
	var tmp_texture gdextension.ObjectPtr
	if texture != nil {
		tmp_texture = texture.Ptr()
	}

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_texture)),
	}
	gdextension.CallMethodBindPtrCall(buttonMethodSetButtonIcon(), self.Ptr(), args[:], nil)
}

// GetButtonIcon mirrors the Godot Button.get_button_icon method.
func (self *Button) GetButtonIcon() *Texture2D {
	var ret gdextension.ObjectPtr
	gdextension.CallMethodBindPtrCall(buttonMethodGetButtonIcon(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return Texture2DFromPtr(ret)
}

// SetFlat mirrors the Godot Button.set_flat method.
func (self *Button) SetFlat(enabled bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&enabled)),
	}
	gdextension.CallMethodBindPtrCall(buttonMethodSetFlat(), self.Ptr(), args[:], nil)
}

// IsFlat mirrors the Godot Button.is_flat method.
func (self *Button) IsFlat() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(buttonMethodIsFlat(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetClipText mirrors the Godot Button.set_clip_text method.
func (self *Button) SetClipText(enabled bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&enabled)),
	}
	gdextension.CallMethodBindPtrCall(buttonMethodSetClipText(), self.Ptr(), args[:], nil)
}

// GetClipText mirrors the Godot Button.get_clip_text method.
func (self *Button) GetClipText() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(buttonMethodGetClipText(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetTextAlignment mirrors the Godot Button.set_text_alignment method.
func (self *Button) SetTextAlignment(alignment int64) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&alignment)),
	}
	gdextension.CallMethodBindPtrCall(buttonMethodSetTextAlignment(), self.Ptr(), args[:], nil)
}

// GetTextAlignment mirrors the Godot Button.get_text_alignment method.
func (self *Button) GetTextAlignment() int64 {
	var ret int64
	gdextension.CallMethodBindPtrCall(buttonMethodGetTextAlignment(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetIconAlignment mirrors the Godot Button.set_icon_alignment method.
func (self *Button) SetIconAlignment(icon_alignment int64) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&icon_alignment)),
	}
	gdextension.CallMethodBindPtrCall(buttonMethodSetIconAlignment(), self.Ptr(), args[:], nil)
}

// GetIconAlignment mirrors the Godot Button.get_icon_alignment method.
func (self *Button) GetIconAlignment() int64 {
	var ret int64
	gdextension.CallMethodBindPtrCall(buttonMethodGetIconAlignment(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetVerticalIconAlignment mirrors the Godot Button.set_vertical_icon_alignment method.
func (self *Button) SetVerticalIconAlignment(vertical_icon_alignment int64) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&vertical_icon_alignment)),
	}
	gdextension.CallMethodBindPtrCall(buttonMethodSetVerticalIconAlignment(), self.Ptr(), args[:], nil)
}

// GetVerticalIconAlignment mirrors the Godot Button.get_vertical_icon_alignment method.
func (self *Button) GetVerticalIconAlignment() int64 {
	var ret int64
	gdextension.CallMethodBindPtrCall(buttonMethodGetVerticalIconAlignment(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetExpandIcon mirrors the Godot Button.set_expand_icon method.
func (self *Button) SetExpandIcon(enabled bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&enabled)),
	}
	gdextension.CallMethodBindPtrCall(buttonMethodSetExpandIcon(), self.Ptr(), args[:], nil)
}

// IsExpandIcon mirrors the Godot Button.is_expand_icon method.
func (self *Button) IsExpandIcon() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(buttonMethodIsExpandIcon(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}
