// Code generated by godot-go-bindgen. DO NOT EDIT.

package core

import (
	"runtime"
	"sync"
	"unsafe"

	"github.com/legendary-code/godot-go/internal/gdextension"
)

// CallbackTweener mirrors the Godot engine class CallbackTweener.
type CallbackTweener struct {
	Tweener
}

// CallbackTweenerFromPtr wraps an existing host-allocated GDExtensionObjectPtr in a
// *CallbackTweener. Returns nil on a nil input. CallbackTweener descends from RefCounted, so the
// returned wrapper carries a Go finalizer that drops one engine
// reference (via Unreference, dispatched on the main thread) when
// Go's GC determines the wrapper is unreachable. Users who want
// deterministic free can call ret.Unreference() directly — the
// finalizer is harmless after the refcount hits zero.
func CallbackTweenerFromPtr(p gdextension.ObjectPtr) *CallbackTweener {
	if p == nil {
		return nil
	}
	ret := &CallbackTweener{}
	ret.BindPtr(p)
	runtime.SetFinalizer(ret, func(r *CallbackTweener) {
		gdextension.RunOnMain(func() { r.Unreference() })
	})
	return ret
}

var (
	callbackTweenerMethodSetDelay = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CallbackTweener"),
			gdextension.InternStringName("set_delay"),
			3008182292,
		)
	})
)

// SetDelay mirrors the Godot CallbackTweener.set_delay method.
func (self *CallbackTweener) SetDelay(delay float32) *CallbackTweener {
	var ret gdextension.ObjectPtr
	tmp_delay := float64(delay)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_delay)),
	}
	gdextension.CallMethodBindPtrCall(callbackTweenerMethodSetDelay(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return CallbackTweenerFromPtr(ret)
}
