// Code generated by godot-go-bindgen. DO NOT EDIT.

package core

import (
	"runtime"
	"sync"
	"unsafe"

	"github.com/legendary-code/godot-go/internal/gdextension"
)

// CameraAttributesPractical mirrors the Godot engine class CameraAttributesPractical.
type CameraAttributesPractical struct {
	CameraAttributes
}

// CameraAttributesPracticalFromPtr wraps an existing host-allocated GDExtensionObjectPtr in a
// *CameraAttributesPractical. Returns nil on a nil input. CameraAttributesPractical descends from RefCounted, so the
// returned wrapper carries a Go finalizer that drops one engine
// reference (via Unreference, dispatched on the main thread) when
// Go's GC determines the wrapper is unreachable. Users who want
// deterministic free can call ret.Unreference() directly — the
// finalizer is harmless after the refcount hits zero.
func CameraAttributesPracticalFromPtr(p gdextension.ObjectPtr) *CameraAttributesPractical {
	if p == nil {
		return nil
	}
	ret := &CameraAttributesPractical{}
	ret.BindPtr(p)
	runtime.SetFinalizer(ret, func(r *CameraAttributesPractical) {
		gdextension.RunOnMain(func() { r.Unreference() })
	})
	return ret
}

var (
	cameraAttributesPracticalMethodSetDofBlurFarEnabled = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CameraAttributesPractical"),
			gdextension.InternStringName("set_dof_blur_far_enabled"),
			2586408642,
		)
	})
	cameraAttributesPracticalMethodIsDofBlurFarEnabled = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CameraAttributesPractical"),
			gdextension.InternStringName("is_dof_blur_far_enabled"),
			36873697,
		)
	})
	cameraAttributesPracticalMethodSetDofBlurFarDistance = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CameraAttributesPractical"),
			gdextension.InternStringName("set_dof_blur_far_distance"),
			373806689,
		)
	})
	cameraAttributesPracticalMethodGetDofBlurFarDistance = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CameraAttributesPractical"),
			gdextension.InternStringName("get_dof_blur_far_distance"),
			1740695150,
		)
	})
	cameraAttributesPracticalMethodSetDofBlurFarTransition = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CameraAttributesPractical"),
			gdextension.InternStringName("set_dof_blur_far_transition"),
			373806689,
		)
	})
	cameraAttributesPracticalMethodGetDofBlurFarTransition = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CameraAttributesPractical"),
			gdextension.InternStringName("get_dof_blur_far_transition"),
			1740695150,
		)
	})
	cameraAttributesPracticalMethodSetDofBlurNearEnabled = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CameraAttributesPractical"),
			gdextension.InternStringName("set_dof_blur_near_enabled"),
			2586408642,
		)
	})
	cameraAttributesPracticalMethodIsDofBlurNearEnabled = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CameraAttributesPractical"),
			gdextension.InternStringName("is_dof_blur_near_enabled"),
			36873697,
		)
	})
	cameraAttributesPracticalMethodSetDofBlurNearDistance = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CameraAttributesPractical"),
			gdextension.InternStringName("set_dof_blur_near_distance"),
			373806689,
		)
	})
	cameraAttributesPracticalMethodGetDofBlurNearDistance = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CameraAttributesPractical"),
			gdextension.InternStringName("get_dof_blur_near_distance"),
			1740695150,
		)
	})
	cameraAttributesPracticalMethodSetDofBlurNearTransition = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CameraAttributesPractical"),
			gdextension.InternStringName("set_dof_blur_near_transition"),
			373806689,
		)
	})
	cameraAttributesPracticalMethodGetDofBlurNearTransition = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CameraAttributesPractical"),
			gdextension.InternStringName("get_dof_blur_near_transition"),
			1740695150,
		)
	})
	cameraAttributesPracticalMethodSetDofBlurAmount = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CameraAttributesPractical"),
			gdextension.InternStringName("set_dof_blur_amount"),
			373806689,
		)
	})
	cameraAttributesPracticalMethodGetDofBlurAmount = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CameraAttributesPractical"),
			gdextension.InternStringName("get_dof_blur_amount"),
			1740695150,
		)
	})
	cameraAttributesPracticalMethodSetAutoExposureMaxSensitivity = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CameraAttributesPractical"),
			gdextension.InternStringName("set_auto_exposure_max_sensitivity"),
			373806689,
		)
	})
	cameraAttributesPracticalMethodGetAutoExposureMaxSensitivity = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CameraAttributesPractical"),
			gdextension.InternStringName("get_auto_exposure_max_sensitivity"),
			1740695150,
		)
	})
	cameraAttributesPracticalMethodSetAutoExposureMinSensitivity = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CameraAttributesPractical"),
			gdextension.InternStringName("set_auto_exposure_min_sensitivity"),
			373806689,
		)
	})
	cameraAttributesPracticalMethodGetAutoExposureMinSensitivity = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CameraAttributesPractical"),
			gdextension.InternStringName("get_auto_exposure_min_sensitivity"),
			1740695150,
		)
	})
)

// SetDofBlurFarEnabled mirrors the Godot CameraAttributesPractical.set_dof_blur_far_enabled method.
func (self *CameraAttributesPractical) SetDofBlurFarEnabled(enabled bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&enabled)),
	}
	gdextension.CallMethodBindPtrCall(cameraAttributesPracticalMethodSetDofBlurFarEnabled(), self.Ptr(), args[:], nil)
}

// IsDofBlurFarEnabled mirrors the Godot CameraAttributesPractical.is_dof_blur_far_enabled method.
func (self *CameraAttributesPractical) IsDofBlurFarEnabled() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(cameraAttributesPracticalMethodIsDofBlurFarEnabled(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetDofBlurFarDistance mirrors the Godot CameraAttributesPractical.set_dof_blur_far_distance method.
func (self *CameraAttributesPractical) SetDofBlurFarDistance(distance float32) {
	tmp_distance := float64(distance)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_distance)),
	}
	gdextension.CallMethodBindPtrCall(cameraAttributesPracticalMethodSetDofBlurFarDistance(), self.Ptr(), args[:], nil)
}

// GetDofBlurFarDistance mirrors the Godot CameraAttributesPractical.get_dof_blur_far_distance method.
func (self *CameraAttributesPractical) GetDofBlurFarDistance() float32 {
	var raw float64
	gdextension.CallMethodBindPtrCall(cameraAttributesPracticalMethodGetDofBlurFarDistance(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}

// SetDofBlurFarTransition mirrors the Godot CameraAttributesPractical.set_dof_blur_far_transition method.
func (self *CameraAttributesPractical) SetDofBlurFarTransition(distance float32) {
	tmp_distance := float64(distance)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_distance)),
	}
	gdextension.CallMethodBindPtrCall(cameraAttributesPracticalMethodSetDofBlurFarTransition(), self.Ptr(), args[:], nil)
}

// GetDofBlurFarTransition mirrors the Godot CameraAttributesPractical.get_dof_blur_far_transition method.
func (self *CameraAttributesPractical) GetDofBlurFarTransition() float32 {
	var raw float64
	gdextension.CallMethodBindPtrCall(cameraAttributesPracticalMethodGetDofBlurFarTransition(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}

// SetDofBlurNearEnabled mirrors the Godot CameraAttributesPractical.set_dof_blur_near_enabled method.
func (self *CameraAttributesPractical) SetDofBlurNearEnabled(enabled bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&enabled)),
	}
	gdextension.CallMethodBindPtrCall(cameraAttributesPracticalMethodSetDofBlurNearEnabled(), self.Ptr(), args[:], nil)
}

// IsDofBlurNearEnabled mirrors the Godot CameraAttributesPractical.is_dof_blur_near_enabled method.
func (self *CameraAttributesPractical) IsDofBlurNearEnabled() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(cameraAttributesPracticalMethodIsDofBlurNearEnabled(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetDofBlurNearDistance mirrors the Godot CameraAttributesPractical.set_dof_blur_near_distance method.
func (self *CameraAttributesPractical) SetDofBlurNearDistance(distance float32) {
	tmp_distance := float64(distance)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_distance)),
	}
	gdextension.CallMethodBindPtrCall(cameraAttributesPracticalMethodSetDofBlurNearDistance(), self.Ptr(), args[:], nil)
}

// GetDofBlurNearDistance mirrors the Godot CameraAttributesPractical.get_dof_blur_near_distance method.
func (self *CameraAttributesPractical) GetDofBlurNearDistance() float32 {
	var raw float64
	gdextension.CallMethodBindPtrCall(cameraAttributesPracticalMethodGetDofBlurNearDistance(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}

// SetDofBlurNearTransition mirrors the Godot CameraAttributesPractical.set_dof_blur_near_transition method.
func (self *CameraAttributesPractical) SetDofBlurNearTransition(distance float32) {
	tmp_distance := float64(distance)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_distance)),
	}
	gdextension.CallMethodBindPtrCall(cameraAttributesPracticalMethodSetDofBlurNearTransition(), self.Ptr(), args[:], nil)
}

// GetDofBlurNearTransition mirrors the Godot CameraAttributesPractical.get_dof_blur_near_transition method.
func (self *CameraAttributesPractical) GetDofBlurNearTransition() float32 {
	var raw float64
	gdextension.CallMethodBindPtrCall(cameraAttributesPracticalMethodGetDofBlurNearTransition(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}

// SetDofBlurAmount mirrors the Godot CameraAttributesPractical.set_dof_blur_amount method.
func (self *CameraAttributesPractical) SetDofBlurAmount(amount float32) {
	tmp_amount := float64(amount)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_amount)),
	}
	gdextension.CallMethodBindPtrCall(cameraAttributesPracticalMethodSetDofBlurAmount(), self.Ptr(), args[:], nil)
}

// GetDofBlurAmount mirrors the Godot CameraAttributesPractical.get_dof_blur_amount method.
func (self *CameraAttributesPractical) GetDofBlurAmount() float32 {
	var raw float64
	gdextension.CallMethodBindPtrCall(cameraAttributesPracticalMethodGetDofBlurAmount(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}

// SetAutoExposureMaxSensitivity mirrors the Godot CameraAttributesPractical.set_auto_exposure_max_sensitivity method.
func (self *CameraAttributesPractical) SetAutoExposureMaxSensitivity(max_sensitivity float32) {
	tmp_max_sensitivity := float64(max_sensitivity)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_max_sensitivity)),
	}
	gdextension.CallMethodBindPtrCall(cameraAttributesPracticalMethodSetAutoExposureMaxSensitivity(), self.Ptr(), args[:], nil)
}

// GetAutoExposureMaxSensitivity mirrors the Godot CameraAttributesPractical.get_auto_exposure_max_sensitivity method.
func (self *CameraAttributesPractical) GetAutoExposureMaxSensitivity() float32 {
	var raw float64
	gdextension.CallMethodBindPtrCall(cameraAttributesPracticalMethodGetAutoExposureMaxSensitivity(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}

// SetAutoExposureMinSensitivity mirrors the Godot CameraAttributesPractical.set_auto_exposure_min_sensitivity method.
func (self *CameraAttributesPractical) SetAutoExposureMinSensitivity(min_sensitivity float32) {
	tmp_min_sensitivity := float64(min_sensitivity)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_min_sensitivity)),
	}
	gdextension.CallMethodBindPtrCall(cameraAttributesPracticalMethodSetAutoExposureMinSensitivity(), self.Ptr(), args[:], nil)
}

// GetAutoExposureMinSensitivity mirrors the Godot CameraAttributesPractical.get_auto_exposure_min_sensitivity method.
func (self *CameraAttributesPractical) GetAutoExposureMinSensitivity() float32 {
	var raw float64
	gdextension.CallMethodBindPtrCall(cameraAttributesPracticalMethodGetAutoExposureMinSensitivity(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}
