// Code generated by godot-go-bindgen. DO NOT EDIT.

package core

import (
	"sync"
	"unsafe"

	"github.com/legendary-code/godot-go/internal/gdextension"
)

// CanvasGroup mirrors the Godot engine class CanvasGroup.
type CanvasGroup struct {
	Node2D
}

// CanvasGroupFromPtr wraps an existing host-allocated GDExtensionObjectPtr in a
// *CanvasGroup. Returns nil on a nil input.
func CanvasGroupFromPtr(p gdextension.ObjectPtr) *CanvasGroup {
	if p == nil {
		return nil
	}
	ret := &CanvasGroup{}
	ret.BindPtr(p)
	return ret
}

var (
	canvasGroupMethodSetFitMargin = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CanvasGroup"),
			gdextension.InternStringName("set_fit_margin"),
			373806689,
		)
	})
	canvasGroupMethodGetFitMargin = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CanvasGroup"),
			gdextension.InternStringName("get_fit_margin"),
			1740695150,
		)
	})
	canvasGroupMethodSetClearMargin = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CanvasGroup"),
			gdextension.InternStringName("set_clear_margin"),
			373806689,
		)
	})
	canvasGroupMethodGetClearMargin = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CanvasGroup"),
			gdextension.InternStringName("get_clear_margin"),
			1740695150,
		)
	})
	canvasGroupMethodSetUseMipmaps = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CanvasGroup"),
			gdextension.InternStringName("set_use_mipmaps"),
			2586408642,
		)
	})
	canvasGroupMethodIsUsingMipmaps = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CanvasGroup"),
			gdextension.InternStringName("is_using_mipmaps"),
			36873697,
		)
	})
)

// SetFitMargin mirrors the Godot CanvasGroup.set_fit_margin method.
func (self *CanvasGroup) SetFitMargin(fit_margin float32) {
	tmp_fit_margin := float64(fit_margin)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_fit_margin)),
	}
	gdextension.CallMethodBindPtrCall(canvasGroupMethodSetFitMargin(), self.Ptr(), args[:], nil)
}

// GetFitMargin mirrors the Godot CanvasGroup.get_fit_margin method.
func (self *CanvasGroup) GetFitMargin() float32 {
	var raw float64
	gdextension.CallMethodBindPtrCall(canvasGroupMethodGetFitMargin(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}

// SetClearMargin mirrors the Godot CanvasGroup.set_clear_margin method.
func (self *CanvasGroup) SetClearMargin(clear_margin float32) {
	tmp_clear_margin := float64(clear_margin)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_clear_margin)),
	}
	gdextension.CallMethodBindPtrCall(canvasGroupMethodSetClearMargin(), self.Ptr(), args[:], nil)
}

// GetClearMargin mirrors the Godot CanvasGroup.get_clear_margin method.
func (self *CanvasGroup) GetClearMargin() float32 {
	var raw float64
	gdextension.CallMethodBindPtrCall(canvasGroupMethodGetClearMargin(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}

// SetUseMipmaps mirrors the Godot CanvasGroup.set_use_mipmaps method.
func (self *CanvasGroup) SetUseMipmaps(use_mipmaps bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&use_mipmaps)),
	}
	gdextension.CallMethodBindPtrCall(canvasGroupMethodSetUseMipmaps(), self.Ptr(), args[:], nil)
}

// IsUsingMipmaps mirrors the Godot CanvasGroup.is_using_mipmaps method.
func (self *CanvasGroup) IsUsingMipmaps() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(canvasGroupMethodIsUsingMipmaps(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}
