// Code generated by godot-go-bindgen. DO NOT EDIT.

package core

import (
	"runtime"
	"sync"
	"unsafe"

	"github.com/legendary-code/godot-go/gdextension"
)

// CapsuleShape3D mirrors the Godot engine class CapsuleShape3D.
type CapsuleShape3D struct {
	Shape3D
}

// CapsuleShape3DFromPtr wraps an existing host-allocated GDExtensionObjectPtr in a
// *CapsuleShape3D. Returns nil on a nil input. CapsuleShape3D descends from RefCounted, so the
// returned wrapper carries a Go finalizer that drops one engine
// reference (via Unreference, dispatched on the main thread) when
// Go's GC determines the wrapper is unreachable. Users who want
// deterministic free can call ret.Unreference() directly — the
// finalizer is harmless after the refcount hits zero.
func CapsuleShape3DFromPtr(p gdextension.ObjectPtr) *CapsuleShape3D {
	if p == nil {
		return nil
	}
	ret := &CapsuleShape3D{}
	ret.BindPtr(p)
	runtime.SetFinalizer(ret, func(r *CapsuleShape3D) {
		gdextension.RunOnMain(func() { r.Unreference() })
	})
	return ret
}

var (
	capsuleShape3DMethodSetRadius = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CapsuleShape3D"),
			gdextension.InternStringName("set_radius"),
			373806689,
		)
	})
	capsuleShape3DMethodGetRadius = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CapsuleShape3D"),
			gdextension.InternStringName("get_radius"),
			1740695150,
		)
	})
	capsuleShape3DMethodSetHeight = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CapsuleShape3D"),
			gdextension.InternStringName("set_height"),
			373806689,
		)
	})
	capsuleShape3DMethodGetHeight = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CapsuleShape3D"),
			gdextension.InternStringName("get_height"),
			1740695150,
		)
	})
	capsuleShape3DMethodSetMidHeight = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CapsuleShape3D"),
			gdextension.InternStringName("set_mid_height"),
			373806689,
		)
	})
	capsuleShape3DMethodGetMidHeight = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CapsuleShape3D"),
			gdextension.InternStringName("get_mid_height"),
			1740695150,
		)
	})
)

// SetRadius mirrors the Godot CapsuleShape3D.set_radius method.
func (self *CapsuleShape3D) SetRadius(radius float32) {
	tmp_radius := float64(radius)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_radius)),
	}
	gdextension.CallMethodBindPtrCall(capsuleShape3DMethodSetRadius(), self.Ptr(), args[:], nil)
}

// GetRadius mirrors the Godot CapsuleShape3D.get_radius method.
func (self *CapsuleShape3D) GetRadius() float32 {
	var raw float64
	gdextension.CallMethodBindPtrCall(capsuleShape3DMethodGetRadius(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}

// SetHeight mirrors the Godot CapsuleShape3D.set_height method.
func (self *CapsuleShape3D) SetHeight(height float32) {
	tmp_height := float64(height)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_height)),
	}
	gdextension.CallMethodBindPtrCall(capsuleShape3DMethodSetHeight(), self.Ptr(), args[:], nil)
}

// GetHeight mirrors the Godot CapsuleShape3D.get_height method.
func (self *CapsuleShape3D) GetHeight() float32 {
	var raw float64
	gdextension.CallMethodBindPtrCall(capsuleShape3DMethodGetHeight(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}

// SetMidHeight mirrors the Godot CapsuleShape3D.set_mid_height method.
func (self *CapsuleShape3D) SetMidHeight(mid_height float32) {
	tmp_mid_height := float64(mid_height)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_mid_height)),
	}
	gdextension.CallMethodBindPtrCall(capsuleShape3DMethodSetMidHeight(), self.Ptr(), args[:], nil)
}

// GetMidHeight mirrors the Godot CapsuleShape3D.get_mid_height method.
func (self *CapsuleShape3D) GetMidHeight() float32 {
	var raw float64
	gdextension.CallMethodBindPtrCall(capsuleShape3DMethodGetMidHeight(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}
