// Code generated by godot-go-bindgen. DO NOT EDIT.

package core

import (
	"sync"
	"unsafe"

	"github.com/legendary-code/godot-go/internal/gdextension"
	"github.com/legendary-code/godot-go/variant"
)

// CodeEdit mirrors the Godot engine class CodeEdit.
type CodeEdit struct {
	TextEdit
}

// CodeEditFromPtr wraps an existing host-allocated GDExtensionObjectPtr in a
// *CodeEdit. Returns nil on a nil input.
func CodeEditFromPtr(p gdextension.ObjectPtr) *CodeEdit {
	if p == nil {
		return nil
	}
	ret := &CodeEdit{}
	ret.BindPtr(p)
	return ret
}

// CodeEditCodeCompletionKind is the Godot CodeEditCodeCompletionKind enum.
type CodeEditCodeCompletionKind int64

const (
	CodeEdit_KIND_CLASS      CodeEditCodeCompletionKind = 0
	CodeEdit_KIND_FUNCTION   CodeEditCodeCompletionKind = 1
	CodeEdit_KIND_SIGNAL     CodeEditCodeCompletionKind = 2
	CodeEdit_KIND_VARIABLE   CodeEditCodeCompletionKind = 3
	CodeEdit_KIND_MEMBER     CodeEditCodeCompletionKind = 4
	CodeEdit_KIND_ENUM       CodeEditCodeCompletionKind = 5
	CodeEdit_KIND_CONSTANT   CodeEditCodeCompletionKind = 6
	CodeEdit_KIND_NODE_PATH  CodeEditCodeCompletionKind = 7
	CodeEdit_KIND_FILE_PATH  CodeEditCodeCompletionKind = 8
	CodeEdit_KIND_PLAIN_TEXT CodeEditCodeCompletionKind = 9
)

// CodeEditCodeCompletionLocation is the Godot CodeEditCodeCompletionLocation enum.
type CodeEditCodeCompletionLocation int64

const (
	CodeEdit_LOCATION_LOCAL           CodeEditCodeCompletionLocation = 0
	CodeEdit_LOCATION_PARENT_MASK     CodeEditCodeCompletionLocation = 256
	CodeEdit_LOCATION_OTHER_USER_CODE CodeEditCodeCompletionLocation = 512
	CodeEdit_LOCATION_OTHER           CodeEditCodeCompletionLocation = 1024
)

var (
	codeEditMethodSetIndentSize = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("set_indent_size"),
			1286410249,
		)
	})
	codeEditMethodGetIndentSize = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("get_indent_size"),
			3905245786,
		)
	})
	codeEditMethodSetIndentUsingSpaces = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("set_indent_using_spaces"),
			2586408642,
		)
	})
	codeEditMethodIsIndentUsingSpaces = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("is_indent_using_spaces"),
			36873697,
		)
	})
	codeEditMethodSetAutoIndentEnabled = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("set_auto_indent_enabled"),
			2586408642,
		)
	})
	codeEditMethodIsAutoIndentEnabled = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("is_auto_indent_enabled"),
			36873697,
		)
	})
	codeEditMethodSetAutoIndentPrefixes = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("set_auto_indent_prefixes"),
			381264803,
		)
	})
	codeEditMethodGetAutoIndentPrefixes = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("get_auto_indent_prefixes"),
			3995934104,
		)
	})
	codeEditMethodDoIndent = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("do_indent"),
			3218959716,
		)
	})
	codeEditMethodIndentLines = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("indent_lines"),
			3218959716,
		)
	})
	codeEditMethodUnindentLines = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("unindent_lines"),
			3218959716,
		)
	})
	codeEditMethodConvertIndent = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("convert_indent"),
			423910286,
		)
	})
	codeEditMethodSetAutoBraceCompletionEnabled = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("set_auto_brace_completion_enabled"),
			2586408642,
		)
	})
	codeEditMethodIsAutoBraceCompletionEnabled = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("is_auto_brace_completion_enabled"),
			36873697,
		)
	})
	codeEditMethodSetHighlightMatchingBracesEnabled = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("set_highlight_matching_braces_enabled"),
			2586408642,
		)
	})
	codeEditMethodIsHighlightMatchingBracesEnabled = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("is_highlight_matching_braces_enabled"),
			36873697,
		)
	})
	codeEditMethodAddAutoBraceCompletionPair = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("add_auto_brace_completion_pair"),
			3186203200,
		)
	})
	codeEditMethodSetAutoBraceCompletionPairs = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("set_auto_brace_completion_pairs"),
			4155329257,
		)
	})
	codeEditMethodGetAutoBraceCompletionPairs = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("get_auto_brace_completion_pairs"),
			3102165223,
		)
	})
	codeEditMethodHasAutoBraceCompletionOpenKey = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("has_auto_brace_completion_open_key"),
			3927539163,
		)
	})
	codeEditMethodHasAutoBraceCompletionCloseKey = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("has_auto_brace_completion_close_key"),
			3927539163,
		)
	})
	codeEditMethodGetAutoBraceCompletionCloseKey = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("get_auto_brace_completion_close_key"),
			3135753539,
		)
	})
	codeEditMethodSetDrawBreakpointsGutter = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("set_draw_breakpoints_gutter"),
			2586408642,
		)
	})
	codeEditMethodIsDrawingBreakpointsGutter = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("is_drawing_breakpoints_gutter"),
			36873697,
		)
	})
	codeEditMethodSetDrawBookmarksGutter = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("set_draw_bookmarks_gutter"),
			2586408642,
		)
	})
	codeEditMethodIsDrawingBookmarksGutter = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("is_drawing_bookmarks_gutter"),
			36873697,
		)
	})
	codeEditMethodSetDrawExecutingLinesGutter = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("set_draw_executing_lines_gutter"),
			2586408642,
		)
	})
	codeEditMethodIsDrawingExecutingLinesGutter = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("is_drawing_executing_lines_gutter"),
			36873697,
		)
	})
	codeEditMethodSetLineAsBreakpoint = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("set_line_as_breakpoint"),
			300928843,
		)
	})
	codeEditMethodIsLineBreakpointed = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("is_line_breakpointed"),
			1116898809,
		)
	})
	codeEditMethodClearBreakpointedLines = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("clear_breakpointed_lines"),
			3218959716,
		)
	})
	codeEditMethodGetBreakpointedLines = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("get_breakpointed_lines"),
			1930428628,
		)
	})
	codeEditMethodSetLineAsBookmarked = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("set_line_as_bookmarked"),
			300928843,
		)
	})
	codeEditMethodIsLineBookmarked = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("is_line_bookmarked"),
			1116898809,
		)
	})
	codeEditMethodClearBookmarkedLines = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("clear_bookmarked_lines"),
			3218959716,
		)
	})
	codeEditMethodGetBookmarkedLines = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("get_bookmarked_lines"),
			1930428628,
		)
	})
	codeEditMethodSetLineAsExecuting = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("set_line_as_executing"),
			300928843,
		)
	})
	codeEditMethodIsLineExecuting = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("is_line_executing"),
			1116898809,
		)
	})
	codeEditMethodClearExecutingLines = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("clear_executing_lines"),
			3218959716,
		)
	})
	codeEditMethodGetExecutingLines = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("get_executing_lines"),
			1930428628,
		)
	})
	codeEditMethodSetDrawLineNumbers = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("set_draw_line_numbers"),
			2586408642,
		)
	})
	codeEditMethodIsDrawLineNumbersEnabled = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("is_draw_line_numbers_enabled"),
			36873697,
		)
	})
	codeEditMethodSetLineNumbersZeroPadded = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("set_line_numbers_zero_padded"),
			2586408642,
		)
	})
	codeEditMethodIsLineNumbersZeroPadded = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("is_line_numbers_zero_padded"),
			36873697,
		)
	})
	codeEditMethodSetLineNumbersMinDigits = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("set_line_numbers_min_digits"),
			1286410249,
		)
	})
	codeEditMethodGetLineNumbersMinDigits = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("get_line_numbers_min_digits"),
			3905245786,
		)
	})
	codeEditMethodSetDrawFoldGutter = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("set_draw_fold_gutter"),
			2586408642,
		)
	})
	codeEditMethodIsDrawingFoldGutter = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("is_drawing_fold_gutter"),
			36873697,
		)
	})
	codeEditMethodSetLineFoldingEnabled = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("set_line_folding_enabled"),
			2586408642,
		)
	})
	codeEditMethodIsLineFoldingEnabled = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("is_line_folding_enabled"),
			36873697,
		)
	})
	codeEditMethodCanFoldLine = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("can_fold_line"),
			1116898809,
		)
	})
	codeEditMethodFoldLine = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("fold_line"),
			1286410249,
		)
	})
	codeEditMethodUnfoldLine = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("unfold_line"),
			1286410249,
		)
	})
	codeEditMethodFoldAllLines = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("fold_all_lines"),
			3218959716,
		)
	})
	codeEditMethodUnfoldAllLines = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("unfold_all_lines"),
			3218959716,
		)
	})
	codeEditMethodToggleFoldableLine = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("toggle_foldable_line"),
			1286410249,
		)
	})
	codeEditMethodToggleFoldableLinesAtCarets = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("toggle_foldable_lines_at_carets"),
			3218959716,
		)
	})
	codeEditMethodIsLineFolded = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("is_line_folded"),
			1116898809,
		)
	})
	codeEditMethodGetFoldedLines = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("get_folded_lines"),
			3995934104,
		)
	})
	codeEditMethodCreateCodeRegion = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("create_code_region"),
			3218959716,
		)
	})
	codeEditMethodGetCodeRegionStartTag = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("get_code_region_start_tag"),
			201670096,
		)
	})
	codeEditMethodGetCodeRegionEndTag = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("get_code_region_end_tag"),
			201670096,
		)
	})
	codeEditMethodSetCodeRegionTags = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("set_code_region_tags"),
			708800718,
		)
	})
	codeEditMethodIsLineCodeRegionStart = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("is_line_code_region_start"),
			1116898809,
		)
	})
	codeEditMethodIsLineCodeRegionEnd = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("is_line_code_region_end"),
			1116898809,
		)
	})
	codeEditMethodAddStringDelimiter = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("add_string_delimiter"),
			3146098955,
		)
	})
	codeEditMethodRemoveStringDelimiter = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("remove_string_delimiter"),
			83702148,
		)
	})
	codeEditMethodHasStringDelimiter = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("has_string_delimiter"),
			3927539163,
		)
	})
	codeEditMethodSetStringDelimiters = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("set_string_delimiters"),
			381264803,
		)
	})
	codeEditMethodClearStringDelimiters = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("clear_string_delimiters"),
			3218959716,
		)
	})
	codeEditMethodGetStringDelimiters = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("get_string_delimiters"),
			3995934104,
		)
	})
	codeEditMethodIsInString = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("is_in_string"),
			688195400,
		)
	})
	codeEditMethodAddCommentDelimiter = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("add_comment_delimiter"),
			3146098955,
		)
	})
	codeEditMethodRemoveCommentDelimiter = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("remove_comment_delimiter"),
			83702148,
		)
	})
	codeEditMethodHasCommentDelimiter = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("has_comment_delimiter"),
			3927539163,
		)
	})
	codeEditMethodSetCommentDelimiters = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("set_comment_delimiters"),
			381264803,
		)
	})
	codeEditMethodClearCommentDelimiters = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("clear_comment_delimiters"),
			3218959716,
		)
	})
	codeEditMethodGetCommentDelimiters = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("get_comment_delimiters"),
			3995934104,
		)
	})
	codeEditMethodIsInComment = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("is_in_comment"),
			688195400,
		)
	})
	codeEditMethodGetDelimiterStartKey = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("get_delimiter_start_key"),
			844755477,
		)
	})
	codeEditMethodGetDelimiterEndKey = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("get_delimiter_end_key"),
			844755477,
		)
	})
	codeEditMethodGetDelimiterStartPosition = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("get_delimiter_start_position"),
			3016396712,
		)
	})
	codeEditMethodGetDelimiterEndPosition = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("get_delimiter_end_position"),
			3016396712,
		)
	})
	codeEditMethodSetCodeHint = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("set_code_hint"),
			83702148,
		)
	})
	codeEditMethodSetCodeHintDrawBelow = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("set_code_hint_draw_below"),
			2586408642,
		)
	})
	codeEditMethodGetTextForCodeCompletion = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("get_text_for_code_completion"),
			201670096,
		)
	})
	codeEditMethodRequestCodeCompletion = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("request_code_completion"),
			107499316,
		)
	})
	codeEditMethodAddCodeCompletionOption = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("add_code_completion_option"),
			3944379502,
		)
	})
	codeEditMethodUpdateCodeCompletionOptions = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("update_code_completion_options"),
			2586408642,
		)
	})
	codeEditMethodGetCodeCompletionOptions = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("get_code_completion_options"),
			3995934104,
		)
	})
	codeEditMethodGetCodeCompletionOption = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("get_code_completion_option"),
			3485342025,
		)
	})
	codeEditMethodGetCodeCompletionSelectedIndex = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("get_code_completion_selected_index"),
			3905245786,
		)
	})
	codeEditMethodSetCodeCompletionSelectedIndex = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("set_code_completion_selected_index"),
			1286410249,
		)
	})
	codeEditMethodConfirmCodeCompletion = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("confirm_code_completion"),
			107499316,
		)
	})
	codeEditMethodCancelCodeCompletion = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("cancel_code_completion"),
			3218959716,
		)
	})
	codeEditMethodSetCodeCompletionEnabled = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("set_code_completion_enabled"),
			2586408642,
		)
	})
	codeEditMethodIsCodeCompletionEnabled = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("is_code_completion_enabled"),
			36873697,
		)
	})
	codeEditMethodSetCodeCompletionPrefixes = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("set_code_completion_prefixes"),
			381264803,
		)
	})
	codeEditMethodGetCodeCompletionPrefixes = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("get_code_completion_prefixes"),
			3995934104,
		)
	})
	codeEditMethodSetLineLengthGuidelines = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("set_line_length_guidelines"),
			381264803,
		)
	})
	codeEditMethodGetLineLengthGuidelines = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("get_line_length_guidelines"),
			3995934104,
		)
	})
	codeEditMethodSetSymbolLookupOnClickEnabled = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("set_symbol_lookup_on_click_enabled"),
			2586408642,
		)
	})
	codeEditMethodIsSymbolLookupOnClickEnabled = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("is_symbol_lookup_on_click_enabled"),
			36873697,
		)
	})
	codeEditMethodGetTextForSymbolLookup = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("get_text_for_symbol_lookup"),
			201670096,
		)
	})
	codeEditMethodGetTextWithCursorChar = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("get_text_with_cursor_char"),
			1391810591,
		)
	})
	codeEditMethodSetSymbolLookupWordAsValid = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("set_symbol_lookup_word_as_valid"),
			2586408642,
		)
	})
	codeEditMethodSetSymbolTooltipOnHoverEnabled = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("set_symbol_tooltip_on_hover_enabled"),
			2586408642,
		)
	})
	codeEditMethodIsSymbolTooltipOnHoverEnabled = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("is_symbol_tooltip_on_hover_enabled"),
			36873697,
		)
	})
	codeEditMethodMoveLinesUp = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("move_lines_up"),
			3218959716,
		)
	})
	codeEditMethodMoveLinesDown = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("move_lines_down"),
			3218959716,
		)
	})
	codeEditMethodDeleteLines = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("delete_lines"),
			3218959716,
		)
	})
	codeEditMethodDuplicateSelection = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("duplicate_selection"),
			3218959716,
		)
	})
	codeEditMethodDuplicateLines = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CodeEdit"),
			gdextension.InternStringName("duplicate_lines"),
			3218959716,
		)
	})
)

// SetIndentSize mirrors the Godot CodeEdit.set_indent_size method.
func (self *CodeEdit) SetIndentSize(size int64) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&size)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodSetIndentSize(), self.Ptr(), args[:], nil)
}

// GetIndentSize mirrors the Godot CodeEdit.get_indent_size method.
func (self *CodeEdit) GetIndentSize() int64 {
	var ret int64
	gdextension.CallMethodBindPtrCall(codeEditMethodGetIndentSize(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetIndentUsingSpaces mirrors the Godot CodeEdit.set_indent_using_spaces method.
func (self *CodeEdit) SetIndentUsingSpaces(use_spaces bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&use_spaces)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodSetIndentUsingSpaces(), self.Ptr(), args[:], nil)
}

// IsIndentUsingSpaces mirrors the Godot CodeEdit.is_indent_using_spaces method.
func (self *CodeEdit) IsIndentUsingSpaces() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(codeEditMethodIsIndentUsingSpaces(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetAutoIndentEnabled mirrors the Godot CodeEdit.set_auto_indent_enabled method.
func (self *CodeEdit) SetAutoIndentEnabled(enable bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&enable)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodSetAutoIndentEnabled(), self.Ptr(), args[:], nil)
}

// IsAutoIndentEnabled mirrors the Godot CodeEdit.is_auto_indent_enabled method.
func (self *CodeEdit) IsAutoIndentEnabled() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(codeEditMethodIsAutoIndentEnabled(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetAutoIndentPrefixes mirrors the Godot CodeEdit.set_auto_indent_prefixes method.
func (self *CodeEdit) SetAutoIndentPrefixes(prefixes variant.Array) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&prefixes)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodSetAutoIndentPrefixes(), self.Ptr(), args[:], nil)
}

// GetAutoIndentPrefixes mirrors the Godot CodeEdit.get_auto_indent_prefixes method.
func (self *CodeEdit) GetAutoIndentPrefixes() variant.Array {
	var ret variant.Array
	gdextension.CallMethodBindPtrCall(codeEditMethodGetAutoIndentPrefixes(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// DoIndent mirrors the Godot CodeEdit.do_indent method.
func (self *CodeEdit) DoIndent() {
	gdextension.CallMethodBindPtrCall(codeEditMethodDoIndent(), self.Ptr(), nil, nil)
}

// IndentLines mirrors the Godot CodeEdit.indent_lines method.
func (self *CodeEdit) IndentLines() {
	gdextension.CallMethodBindPtrCall(codeEditMethodIndentLines(), self.Ptr(), nil, nil)
}

// UnindentLines mirrors the Godot CodeEdit.unindent_lines method.
func (self *CodeEdit) UnindentLines() {
	gdextension.CallMethodBindPtrCall(codeEditMethodUnindentLines(), self.Ptr(), nil, nil)
}

// ConvertIndent mirrors the Godot CodeEdit.convert_indent method.
func (self *CodeEdit) ConvertIndent(from_line int64, to_line int64) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&from_line)),
		gdextension.TypePtr(unsafe.Pointer(&to_line)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodConvertIndent(), self.Ptr(), args[:], nil)
}

// SetAutoBraceCompletionEnabled mirrors the Godot CodeEdit.set_auto_brace_completion_enabled method.
func (self *CodeEdit) SetAutoBraceCompletionEnabled(enable bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&enable)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodSetAutoBraceCompletionEnabled(), self.Ptr(), args[:], nil)
}

// IsAutoBraceCompletionEnabled mirrors the Godot CodeEdit.is_auto_brace_completion_enabled method.
func (self *CodeEdit) IsAutoBraceCompletionEnabled() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(codeEditMethodIsAutoBraceCompletionEnabled(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetHighlightMatchingBracesEnabled mirrors the Godot CodeEdit.set_highlight_matching_braces_enabled method.
func (self *CodeEdit) SetHighlightMatchingBracesEnabled(enable bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&enable)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodSetHighlightMatchingBracesEnabled(), self.Ptr(), args[:], nil)
}

// IsHighlightMatchingBracesEnabled mirrors the Godot CodeEdit.is_highlight_matching_braces_enabled method.
func (self *CodeEdit) IsHighlightMatchingBracesEnabled() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(codeEditMethodIsHighlightMatchingBracesEnabled(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// AddAutoBraceCompletionPair mirrors the Godot CodeEdit.add_auto_brace_completion_pair method.
func (self *CodeEdit) AddAutoBraceCompletionPair(start_key string, end_key string) {
	tmp_start_key := variant.NewStringFromString(start_key)
	defer tmp_start_key.Destroy()

	tmp_end_key := variant.NewStringFromString(end_key)
	defer tmp_end_key.Destroy()

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_start_key)),
		gdextension.TypePtr(unsafe.Pointer(&tmp_end_key)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodAddAutoBraceCompletionPair(), self.Ptr(), args[:], nil)
}

// SetAutoBraceCompletionPairs mirrors the Godot CodeEdit.set_auto_brace_completion_pairs method.
func (self *CodeEdit) SetAutoBraceCompletionPairs(pairs variant.Dictionary) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&pairs)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodSetAutoBraceCompletionPairs(), self.Ptr(), args[:], nil)
}

// GetAutoBraceCompletionPairs mirrors the Godot CodeEdit.get_auto_brace_completion_pairs method.
func (self *CodeEdit) GetAutoBraceCompletionPairs() variant.Dictionary {
	var ret variant.Dictionary
	gdextension.CallMethodBindPtrCall(codeEditMethodGetAutoBraceCompletionPairs(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// HasAutoBraceCompletionOpenKey mirrors the Godot CodeEdit.has_auto_brace_completion_open_key method.
func (self *CodeEdit) HasAutoBraceCompletionOpenKey(open_key string) bool {
	var ret bool
	tmp_open_key := variant.NewStringFromString(open_key)
	defer tmp_open_key.Destroy()

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_open_key)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodHasAutoBraceCompletionOpenKey(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// HasAutoBraceCompletionCloseKey mirrors the Godot CodeEdit.has_auto_brace_completion_close_key method.
func (self *CodeEdit) HasAutoBraceCompletionCloseKey(close_key string) bool {
	var ret bool
	tmp_close_key := variant.NewStringFromString(close_key)
	defer tmp_close_key.Destroy()

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_close_key)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodHasAutoBraceCompletionCloseKey(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// GetAutoBraceCompletionCloseKey mirrors the Godot CodeEdit.get_auto_brace_completion_close_key method.
func (self *CodeEdit) GetAutoBraceCompletionCloseKey(open_key string) string {
	var raw variant.String
	defer raw.Destroy()
	tmp_open_key := variant.NewStringFromString(open_key)
	defer tmp_open_key.Destroy()

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_open_key)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodGetAutoBraceCompletionCloseKey(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&raw)))
	return variant.StringToGo(&raw)
}

// SetDrawBreakpointsGutter mirrors the Godot CodeEdit.set_draw_breakpoints_gutter method.
func (self *CodeEdit) SetDrawBreakpointsGutter(enable bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&enable)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodSetDrawBreakpointsGutter(), self.Ptr(), args[:], nil)
}

// IsDrawingBreakpointsGutter mirrors the Godot CodeEdit.is_drawing_breakpoints_gutter method.
func (self *CodeEdit) IsDrawingBreakpointsGutter() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(codeEditMethodIsDrawingBreakpointsGutter(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetDrawBookmarksGutter mirrors the Godot CodeEdit.set_draw_bookmarks_gutter method.
func (self *CodeEdit) SetDrawBookmarksGutter(enable bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&enable)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodSetDrawBookmarksGutter(), self.Ptr(), args[:], nil)
}

// IsDrawingBookmarksGutter mirrors the Godot CodeEdit.is_drawing_bookmarks_gutter method.
func (self *CodeEdit) IsDrawingBookmarksGutter() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(codeEditMethodIsDrawingBookmarksGutter(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetDrawExecutingLinesGutter mirrors the Godot CodeEdit.set_draw_executing_lines_gutter method.
func (self *CodeEdit) SetDrawExecutingLinesGutter(enable bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&enable)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodSetDrawExecutingLinesGutter(), self.Ptr(), args[:], nil)
}

// IsDrawingExecutingLinesGutter mirrors the Godot CodeEdit.is_drawing_executing_lines_gutter method.
func (self *CodeEdit) IsDrawingExecutingLinesGutter() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(codeEditMethodIsDrawingExecutingLinesGutter(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetLineAsBreakpoint mirrors the Godot CodeEdit.set_line_as_breakpoint method.
func (self *CodeEdit) SetLineAsBreakpoint(line int64, breakpointed bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&line)),
		gdextension.TypePtr(unsafe.Pointer(&breakpointed)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodSetLineAsBreakpoint(), self.Ptr(), args[:], nil)
}

// IsLineBreakpointed mirrors the Godot CodeEdit.is_line_breakpointed method.
func (self *CodeEdit) IsLineBreakpointed(line int64) bool {
	var ret bool
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&line)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodIsLineBreakpointed(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// ClearBreakpointedLines mirrors the Godot CodeEdit.clear_breakpointed_lines method.
func (self *CodeEdit) ClearBreakpointedLines() {
	gdextension.CallMethodBindPtrCall(codeEditMethodClearBreakpointedLines(), self.Ptr(), nil, nil)
}

// GetBreakpointedLines mirrors the Godot CodeEdit.get_breakpointed_lines method.
func (self *CodeEdit) GetBreakpointedLines() variant.PackedInt32Array {
	var ret variant.PackedInt32Array
	gdextension.CallMethodBindPtrCall(codeEditMethodGetBreakpointedLines(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetLineAsBookmarked mirrors the Godot CodeEdit.set_line_as_bookmarked method.
func (self *CodeEdit) SetLineAsBookmarked(line int64, bookmarked bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&line)),
		gdextension.TypePtr(unsafe.Pointer(&bookmarked)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodSetLineAsBookmarked(), self.Ptr(), args[:], nil)
}

// IsLineBookmarked mirrors the Godot CodeEdit.is_line_bookmarked method.
func (self *CodeEdit) IsLineBookmarked(line int64) bool {
	var ret bool
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&line)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodIsLineBookmarked(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// ClearBookmarkedLines mirrors the Godot CodeEdit.clear_bookmarked_lines method.
func (self *CodeEdit) ClearBookmarkedLines() {
	gdextension.CallMethodBindPtrCall(codeEditMethodClearBookmarkedLines(), self.Ptr(), nil, nil)
}

// GetBookmarkedLines mirrors the Godot CodeEdit.get_bookmarked_lines method.
func (self *CodeEdit) GetBookmarkedLines() variant.PackedInt32Array {
	var ret variant.PackedInt32Array
	gdextension.CallMethodBindPtrCall(codeEditMethodGetBookmarkedLines(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetLineAsExecuting mirrors the Godot CodeEdit.set_line_as_executing method.
func (self *CodeEdit) SetLineAsExecuting(line int64, executing bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&line)),
		gdextension.TypePtr(unsafe.Pointer(&executing)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodSetLineAsExecuting(), self.Ptr(), args[:], nil)
}

// IsLineExecuting mirrors the Godot CodeEdit.is_line_executing method.
func (self *CodeEdit) IsLineExecuting(line int64) bool {
	var ret bool
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&line)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodIsLineExecuting(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// ClearExecutingLines mirrors the Godot CodeEdit.clear_executing_lines method.
func (self *CodeEdit) ClearExecutingLines() {
	gdextension.CallMethodBindPtrCall(codeEditMethodClearExecutingLines(), self.Ptr(), nil, nil)
}

// GetExecutingLines mirrors the Godot CodeEdit.get_executing_lines method.
func (self *CodeEdit) GetExecutingLines() variant.PackedInt32Array {
	var ret variant.PackedInt32Array
	gdextension.CallMethodBindPtrCall(codeEditMethodGetExecutingLines(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetDrawLineNumbers mirrors the Godot CodeEdit.set_draw_line_numbers method.
func (self *CodeEdit) SetDrawLineNumbers(enable bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&enable)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodSetDrawLineNumbers(), self.Ptr(), args[:], nil)
}

// IsDrawLineNumbersEnabled mirrors the Godot CodeEdit.is_draw_line_numbers_enabled method.
func (self *CodeEdit) IsDrawLineNumbersEnabled() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(codeEditMethodIsDrawLineNumbersEnabled(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetLineNumbersZeroPadded mirrors the Godot CodeEdit.set_line_numbers_zero_padded method.
func (self *CodeEdit) SetLineNumbersZeroPadded(enable bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&enable)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodSetLineNumbersZeroPadded(), self.Ptr(), args[:], nil)
}

// IsLineNumbersZeroPadded mirrors the Godot CodeEdit.is_line_numbers_zero_padded method.
func (self *CodeEdit) IsLineNumbersZeroPadded() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(codeEditMethodIsLineNumbersZeroPadded(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetLineNumbersMinDigits mirrors the Godot CodeEdit.set_line_numbers_min_digits method.
func (self *CodeEdit) SetLineNumbersMinDigits(count int64) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&count)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodSetLineNumbersMinDigits(), self.Ptr(), args[:], nil)
}

// GetLineNumbersMinDigits mirrors the Godot CodeEdit.get_line_numbers_min_digits method.
func (self *CodeEdit) GetLineNumbersMinDigits() int64 {
	var ret int64
	gdextension.CallMethodBindPtrCall(codeEditMethodGetLineNumbersMinDigits(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetDrawFoldGutter mirrors the Godot CodeEdit.set_draw_fold_gutter method.
func (self *CodeEdit) SetDrawFoldGutter(enable bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&enable)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodSetDrawFoldGutter(), self.Ptr(), args[:], nil)
}

// IsDrawingFoldGutter mirrors the Godot CodeEdit.is_drawing_fold_gutter method.
func (self *CodeEdit) IsDrawingFoldGutter() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(codeEditMethodIsDrawingFoldGutter(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetLineFoldingEnabled mirrors the Godot CodeEdit.set_line_folding_enabled method.
func (self *CodeEdit) SetLineFoldingEnabled(enabled bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&enabled)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodSetLineFoldingEnabled(), self.Ptr(), args[:], nil)
}

// IsLineFoldingEnabled mirrors the Godot CodeEdit.is_line_folding_enabled method.
func (self *CodeEdit) IsLineFoldingEnabled() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(codeEditMethodIsLineFoldingEnabled(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// CanFoldLine mirrors the Godot CodeEdit.can_fold_line method.
func (self *CodeEdit) CanFoldLine(line int64) bool {
	var ret bool
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&line)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodCanFoldLine(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// FoldLine mirrors the Godot CodeEdit.fold_line method.
func (self *CodeEdit) FoldLine(line int64) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&line)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodFoldLine(), self.Ptr(), args[:], nil)
}

// UnfoldLine mirrors the Godot CodeEdit.unfold_line method.
func (self *CodeEdit) UnfoldLine(line int64) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&line)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodUnfoldLine(), self.Ptr(), args[:], nil)
}

// FoldAllLines mirrors the Godot CodeEdit.fold_all_lines method.
func (self *CodeEdit) FoldAllLines() {
	gdextension.CallMethodBindPtrCall(codeEditMethodFoldAllLines(), self.Ptr(), nil, nil)
}

// UnfoldAllLines mirrors the Godot CodeEdit.unfold_all_lines method.
func (self *CodeEdit) UnfoldAllLines() {
	gdextension.CallMethodBindPtrCall(codeEditMethodUnfoldAllLines(), self.Ptr(), nil, nil)
}

// ToggleFoldableLine mirrors the Godot CodeEdit.toggle_foldable_line method.
func (self *CodeEdit) ToggleFoldableLine(line int64) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&line)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodToggleFoldableLine(), self.Ptr(), args[:], nil)
}

// ToggleFoldableLinesAtCarets mirrors the Godot CodeEdit.toggle_foldable_lines_at_carets method.
func (self *CodeEdit) ToggleFoldableLinesAtCarets() {
	gdextension.CallMethodBindPtrCall(codeEditMethodToggleFoldableLinesAtCarets(), self.Ptr(), nil, nil)
}

// IsLineFolded mirrors the Godot CodeEdit.is_line_folded method.
func (self *CodeEdit) IsLineFolded(line int64) bool {
	var ret bool
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&line)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodIsLineFolded(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// GetFoldedLines mirrors the Godot CodeEdit.get_folded_lines method.
func (self *CodeEdit) GetFoldedLines() variant.Array {
	var ret variant.Array
	gdextension.CallMethodBindPtrCall(codeEditMethodGetFoldedLines(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// CreateCodeRegion mirrors the Godot CodeEdit.create_code_region method.
func (self *CodeEdit) CreateCodeRegion() {
	gdextension.CallMethodBindPtrCall(codeEditMethodCreateCodeRegion(), self.Ptr(), nil, nil)
}

// GetCodeRegionStartTag mirrors the Godot CodeEdit.get_code_region_start_tag method.
func (self *CodeEdit) GetCodeRegionStartTag() string {
	var raw variant.String
	defer raw.Destroy()
	gdextension.CallMethodBindPtrCall(codeEditMethodGetCodeRegionStartTag(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return variant.StringToGo(&raw)
}

// GetCodeRegionEndTag mirrors the Godot CodeEdit.get_code_region_end_tag method.
func (self *CodeEdit) GetCodeRegionEndTag() string {
	var raw variant.String
	defer raw.Destroy()
	gdextension.CallMethodBindPtrCall(codeEditMethodGetCodeRegionEndTag(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return variant.StringToGo(&raw)
}

// SetCodeRegionTags mirrors the Godot CodeEdit.set_code_region_tags method.
func (self *CodeEdit) SetCodeRegionTags(start string, end string) {
	tmp_start := variant.NewStringFromString(start)
	defer tmp_start.Destroy()

	tmp_end := variant.NewStringFromString(end)
	defer tmp_end.Destroy()

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_start)),
		gdextension.TypePtr(unsafe.Pointer(&tmp_end)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodSetCodeRegionTags(), self.Ptr(), args[:], nil)
}

// IsLineCodeRegionStart mirrors the Godot CodeEdit.is_line_code_region_start method.
func (self *CodeEdit) IsLineCodeRegionStart(line int64) bool {
	var ret bool
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&line)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodIsLineCodeRegionStart(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// IsLineCodeRegionEnd mirrors the Godot CodeEdit.is_line_code_region_end method.
func (self *CodeEdit) IsLineCodeRegionEnd(line int64) bool {
	var ret bool
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&line)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodIsLineCodeRegionEnd(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// AddStringDelimiter mirrors the Godot CodeEdit.add_string_delimiter method.
func (self *CodeEdit) AddStringDelimiter(start_key string, end_key string, line_only bool) {
	tmp_start_key := variant.NewStringFromString(start_key)
	defer tmp_start_key.Destroy()

	tmp_end_key := variant.NewStringFromString(end_key)
	defer tmp_end_key.Destroy()

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_start_key)),
		gdextension.TypePtr(unsafe.Pointer(&tmp_end_key)),
		gdextension.TypePtr(unsafe.Pointer(&line_only)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodAddStringDelimiter(), self.Ptr(), args[:], nil)
}

// RemoveStringDelimiter mirrors the Godot CodeEdit.remove_string_delimiter method.
func (self *CodeEdit) RemoveStringDelimiter(start_key string) {
	tmp_start_key := variant.NewStringFromString(start_key)
	defer tmp_start_key.Destroy()

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_start_key)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodRemoveStringDelimiter(), self.Ptr(), args[:], nil)
}

// HasStringDelimiter mirrors the Godot CodeEdit.has_string_delimiter method.
func (self *CodeEdit) HasStringDelimiter(start_key string) bool {
	var ret bool
	tmp_start_key := variant.NewStringFromString(start_key)
	defer tmp_start_key.Destroy()

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_start_key)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodHasStringDelimiter(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetStringDelimiters mirrors the Godot CodeEdit.set_string_delimiters method.
func (self *CodeEdit) SetStringDelimiters(string_delimiters variant.Array) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&string_delimiters)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodSetStringDelimiters(), self.Ptr(), args[:], nil)
}

// ClearStringDelimiters mirrors the Godot CodeEdit.clear_string_delimiters method.
func (self *CodeEdit) ClearStringDelimiters() {
	gdextension.CallMethodBindPtrCall(codeEditMethodClearStringDelimiters(), self.Ptr(), nil, nil)
}

// GetStringDelimiters mirrors the Godot CodeEdit.get_string_delimiters method.
func (self *CodeEdit) GetStringDelimiters() variant.Array {
	var ret variant.Array
	gdextension.CallMethodBindPtrCall(codeEditMethodGetStringDelimiters(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// IsInString mirrors the Godot CodeEdit.is_in_string method.
func (self *CodeEdit) IsInString(line int64, column int64) int64 {
	var ret int64
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&line)),
		gdextension.TypePtr(unsafe.Pointer(&column)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodIsInString(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// AddCommentDelimiter mirrors the Godot CodeEdit.add_comment_delimiter method.
func (self *CodeEdit) AddCommentDelimiter(start_key string, end_key string, line_only bool) {
	tmp_start_key := variant.NewStringFromString(start_key)
	defer tmp_start_key.Destroy()

	tmp_end_key := variant.NewStringFromString(end_key)
	defer tmp_end_key.Destroy()

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_start_key)),
		gdextension.TypePtr(unsafe.Pointer(&tmp_end_key)),
		gdextension.TypePtr(unsafe.Pointer(&line_only)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodAddCommentDelimiter(), self.Ptr(), args[:], nil)
}

// RemoveCommentDelimiter mirrors the Godot CodeEdit.remove_comment_delimiter method.
func (self *CodeEdit) RemoveCommentDelimiter(start_key string) {
	tmp_start_key := variant.NewStringFromString(start_key)
	defer tmp_start_key.Destroy()

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_start_key)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodRemoveCommentDelimiter(), self.Ptr(), args[:], nil)
}

// HasCommentDelimiter mirrors the Godot CodeEdit.has_comment_delimiter method.
func (self *CodeEdit) HasCommentDelimiter(start_key string) bool {
	var ret bool
	tmp_start_key := variant.NewStringFromString(start_key)
	defer tmp_start_key.Destroy()

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_start_key)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodHasCommentDelimiter(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetCommentDelimiters mirrors the Godot CodeEdit.set_comment_delimiters method.
func (self *CodeEdit) SetCommentDelimiters(comment_delimiters variant.Array) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&comment_delimiters)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodSetCommentDelimiters(), self.Ptr(), args[:], nil)
}

// ClearCommentDelimiters mirrors the Godot CodeEdit.clear_comment_delimiters method.
func (self *CodeEdit) ClearCommentDelimiters() {
	gdextension.CallMethodBindPtrCall(codeEditMethodClearCommentDelimiters(), self.Ptr(), nil, nil)
}

// GetCommentDelimiters mirrors the Godot CodeEdit.get_comment_delimiters method.
func (self *CodeEdit) GetCommentDelimiters() variant.Array {
	var ret variant.Array
	gdextension.CallMethodBindPtrCall(codeEditMethodGetCommentDelimiters(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// IsInComment mirrors the Godot CodeEdit.is_in_comment method.
func (self *CodeEdit) IsInComment(line int64, column int64) int64 {
	var ret int64
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&line)),
		gdextension.TypePtr(unsafe.Pointer(&column)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodIsInComment(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// GetDelimiterStartKey mirrors the Godot CodeEdit.get_delimiter_start_key method.
func (self *CodeEdit) GetDelimiterStartKey(delimiter_index int64) string {
	var raw variant.String
	defer raw.Destroy()
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&delimiter_index)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodGetDelimiterStartKey(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&raw)))
	return variant.StringToGo(&raw)
}

// GetDelimiterEndKey mirrors the Godot CodeEdit.get_delimiter_end_key method.
func (self *CodeEdit) GetDelimiterEndKey(delimiter_index int64) string {
	var raw variant.String
	defer raw.Destroy()
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&delimiter_index)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodGetDelimiterEndKey(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&raw)))
	return variant.StringToGo(&raw)
}

// GetDelimiterStartPosition mirrors the Godot CodeEdit.get_delimiter_start_position method.
func (self *CodeEdit) GetDelimiterStartPosition(line int64, column int64) variant.Vector2 {
	var ret variant.Vector2
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&line)),
		gdextension.TypePtr(unsafe.Pointer(&column)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodGetDelimiterStartPosition(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// GetDelimiterEndPosition mirrors the Godot CodeEdit.get_delimiter_end_position method.
func (self *CodeEdit) GetDelimiterEndPosition(line int64, column int64) variant.Vector2 {
	var ret variant.Vector2
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&line)),
		gdextension.TypePtr(unsafe.Pointer(&column)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodGetDelimiterEndPosition(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetCodeHint mirrors the Godot CodeEdit.set_code_hint method.
func (self *CodeEdit) SetCodeHint(code_hint string) {
	tmp_code_hint := variant.NewStringFromString(code_hint)
	defer tmp_code_hint.Destroy()

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_code_hint)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodSetCodeHint(), self.Ptr(), args[:], nil)
}

// SetCodeHintDrawBelow mirrors the Godot CodeEdit.set_code_hint_draw_below method.
func (self *CodeEdit) SetCodeHintDrawBelow(draw_below bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&draw_below)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodSetCodeHintDrawBelow(), self.Ptr(), args[:], nil)
}

// GetTextForCodeCompletion mirrors the Godot CodeEdit.get_text_for_code_completion method.
func (self *CodeEdit) GetTextForCodeCompletion() string {
	var raw variant.String
	defer raw.Destroy()
	gdextension.CallMethodBindPtrCall(codeEditMethodGetTextForCodeCompletion(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return variant.StringToGo(&raw)
}

// RequestCodeCompletion mirrors the Godot CodeEdit.request_code_completion method.
func (self *CodeEdit) RequestCodeCompletion(force bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&force)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodRequestCodeCompletion(), self.Ptr(), args[:], nil)
}

// AddCodeCompletionOption mirrors the Godot CodeEdit.add_code_completion_option method.
func (self *CodeEdit) AddCodeCompletionOption(typ CodeEditCodeCompletionKind, display_text string, insert_text string, text_color variant.Color, icon *Resource, value variant.Variant, location int64) {
	tmp_typ := int64(typ)

	tmp_display_text := variant.NewStringFromString(display_text)
	defer tmp_display_text.Destroy()

	tmp_insert_text := variant.NewStringFromString(insert_text)
	defer tmp_insert_text.Destroy()

	var tmp_icon gdextension.ObjectPtr
	if icon != nil {
		tmp_icon = icon.Ptr()
	}

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_typ)),
		gdextension.TypePtr(unsafe.Pointer(&tmp_display_text)),
		gdextension.TypePtr(unsafe.Pointer(&tmp_insert_text)),
		gdextension.TypePtr(unsafe.Pointer(&text_color)),
		gdextension.TypePtr(unsafe.Pointer(&tmp_icon)),
		gdextension.TypePtr(unsafe.Pointer(&value)),
		gdextension.TypePtr(unsafe.Pointer(&location)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodAddCodeCompletionOption(), self.Ptr(), args[:], nil)
}

// UpdateCodeCompletionOptions mirrors the Godot CodeEdit.update_code_completion_options method.
func (self *CodeEdit) UpdateCodeCompletionOptions(force bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&force)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodUpdateCodeCompletionOptions(), self.Ptr(), args[:], nil)
}

// GetCodeCompletionOptions mirrors the Godot CodeEdit.get_code_completion_options method.
func (self *CodeEdit) GetCodeCompletionOptions() variant.Array {
	var ret variant.Array
	gdextension.CallMethodBindPtrCall(codeEditMethodGetCodeCompletionOptions(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// GetCodeCompletionOption mirrors the Godot CodeEdit.get_code_completion_option method.
func (self *CodeEdit) GetCodeCompletionOption(index int64) variant.Dictionary {
	var ret variant.Dictionary
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&index)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodGetCodeCompletionOption(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// GetCodeCompletionSelectedIndex mirrors the Godot CodeEdit.get_code_completion_selected_index method.
func (self *CodeEdit) GetCodeCompletionSelectedIndex() int64 {
	var ret int64
	gdextension.CallMethodBindPtrCall(codeEditMethodGetCodeCompletionSelectedIndex(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetCodeCompletionSelectedIndex mirrors the Godot CodeEdit.set_code_completion_selected_index method.
func (self *CodeEdit) SetCodeCompletionSelectedIndex(index int64) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&index)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodSetCodeCompletionSelectedIndex(), self.Ptr(), args[:], nil)
}

// ConfirmCodeCompletion mirrors the Godot CodeEdit.confirm_code_completion method.
func (self *CodeEdit) ConfirmCodeCompletion(replace bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&replace)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodConfirmCodeCompletion(), self.Ptr(), args[:], nil)
}

// CancelCodeCompletion mirrors the Godot CodeEdit.cancel_code_completion method.
func (self *CodeEdit) CancelCodeCompletion() {
	gdextension.CallMethodBindPtrCall(codeEditMethodCancelCodeCompletion(), self.Ptr(), nil, nil)
}

// SetCodeCompletionEnabled mirrors the Godot CodeEdit.set_code_completion_enabled method.
func (self *CodeEdit) SetCodeCompletionEnabled(enable bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&enable)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodSetCodeCompletionEnabled(), self.Ptr(), args[:], nil)
}

// IsCodeCompletionEnabled mirrors the Godot CodeEdit.is_code_completion_enabled method.
func (self *CodeEdit) IsCodeCompletionEnabled() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(codeEditMethodIsCodeCompletionEnabled(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetCodeCompletionPrefixes mirrors the Godot CodeEdit.set_code_completion_prefixes method.
func (self *CodeEdit) SetCodeCompletionPrefixes(prefixes variant.Array) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&prefixes)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodSetCodeCompletionPrefixes(), self.Ptr(), args[:], nil)
}

// GetCodeCompletionPrefixes mirrors the Godot CodeEdit.get_code_completion_prefixes method.
func (self *CodeEdit) GetCodeCompletionPrefixes() variant.Array {
	var ret variant.Array
	gdextension.CallMethodBindPtrCall(codeEditMethodGetCodeCompletionPrefixes(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetLineLengthGuidelines mirrors the Godot CodeEdit.set_line_length_guidelines method.
func (self *CodeEdit) SetLineLengthGuidelines(guideline_columns variant.Array) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&guideline_columns)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodSetLineLengthGuidelines(), self.Ptr(), args[:], nil)
}

// GetLineLengthGuidelines mirrors the Godot CodeEdit.get_line_length_guidelines method.
func (self *CodeEdit) GetLineLengthGuidelines() variant.Array {
	var ret variant.Array
	gdextension.CallMethodBindPtrCall(codeEditMethodGetLineLengthGuidelines(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetSymbolLookupOnClickEnabled mirrors the Godot CodeEdit.set_symbol_lookup_on_click_enabled method.
func (self *CodeEdit) SetSymbolLookupOnClickEnabled(enable bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&enable)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodSetSymbolLookupOnClickEnabled(), self.Ptr(), args[:], nil)
}

// IsSymbolLookupOnClickEnabled mirrors the Godot CodeEdit.is_symbol_lookup_on_click_enabled method.
func (self *CodeEdit) IsSymbolLookupOnClickEnabled() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(codeEditMethodIsSymbolLookupOnClickEnabled(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// GetTextForSymbolLookup mirrors the Godot CodeEdit.get_text_for_symbol_lookup method.
func (self *CodeEdit) GetTextForSymbolLookup() string {
	var raw variant.String
	defer raw.Destroy()
	gdextension.CallMethodBindPtrCall(codeEditMethodGetTextForSymbolLookup(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return variant.StringToGo(&raw)
}

// GetTextWithCursorChar mirrors the Godot CodeEdit.get_text_with_cursor_char method.
func (self *CodeEdit) GetTextWithCursorChar(line int64, column int64) string {
	var raw variant.String
	defer raw.Destroy()
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&line)),
		gdextension.TypePtr(unsafe.Pointer(&column)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodGetTextWithCursorChar(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&raw)))
	return variant.StringToGo(&raw)
}

// SetSymbolLookupWordAsValid mirrors the Godot CodeEdit.set_symbol_lookup_word_as_valid method.
func (self *CodeEdit) SetSymbolLookupWordAsValid(valid bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&valid)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodSetSymbolLookupWordAsValid(), self.Ptr(), args[:], nil)
}

// SetSymbolTooltipOnHoverEnabled mirrors the Godot CodeEdit.set_symbol_tooltip_on_hover_enabled method.
func (self *CodeEdit) SetSymbolTooltipOnHoverEnabled(enable bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&enable)),
	}
	gdextension.CallMethodBindPtrCall(codeEditMethodSetSymbolTooltipOnHoverEnabled(), self.Ptr(), args[:], nil)
}

// IsSymbolTooltipOnHoverEnabled mirrors the Godot CodeEdit.is_symbol_tooltip_on_hover_enabled method.
func (self *CodeEdit) IsSymbolTooltipOnHoverEnabled() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(codeEditMethodIsSymbolTooltipOnHoverEnabled(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// MoveLinesUp mirrors the Godot CodeEdit.move_lines_up method.
func (self *CodeEdit) MoveLinesUp() {
	gdextension.CallMethodBindPtrCall(codeEditMethodMoveLinesUp(), self.Ptr(), nil, nil)
}

// MoveLinesDown mirrors the Godot CodeEdit.move_lines_down method.
func (self *CodeEdit) MoveLinesDown() {
	gdextension.CallMethodBindPtrCall(codeEditMethodMoveLinesDown(), self.Ptr(), nil, nil)
}

// DeleteLines mirrors the Godot CodeEdit.delete_lines method.
func (self *CodeEdit) DeleteLines() {
	gdextension.CallMethodBindPtrCall(codeEditMethodDeleteLines(), self.Ptr(), nil, nil)
}

// DuplicateSelection mirrors the Godot CodeEdit.duplicate_selection method.
func (self *CodeEdit) DuplicateSelection() {
	gdextension.CallMethodBindPtrCall(codeEditMethodDuplicateSelection(), self.Ptr(), nil, nil)
}

// DuplicateLines mirrors the Godot CodeEdit.duplicate_lines method.
func (self *CodeEdit) DuplicateLines() {
	gdextension.CallMethodBindPtrCall(codeEditMethodDuplicateLines(), self.Ptr(), nil, nil)
}
