// Code generated by godot-go-bindgen. DO NOT EDIT.

package core

import (
	"sync"
	"unsafe"

	"github.com/legendary-code/godot-go/internal/gdextension"
	"github.com/legendary-code/godot-go/variant"
)

// ColorPickerButton mirrors the Godot engine class ColorPickerButton.
type ColorPickerButton struct {
	Button
}

// ColorPickerButtonFromPtr wraps an existing host-allocated GDExtensionObjectPtr in a
// *ColorPickerButton. Returns nil on a nil input.
func ColorPickerButtonFromPtr(p gdextension.ObjectPtr) *ColorPickerButton {
	if p == nil {
		return nil
	}
	ret := &ColorPickerButton{}
	ret.BindPtr(p)
	return ret
}

var (
	colorPickerButtonMethodSetPickColor = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("ColorPickerButton"),
			gdextension.InternStringName("set_pick_color"),
			2920490490,
		)
	})
	colorPickerButtonMethodGetPickColor = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("ColorPickerButton"),
			gdextension.InternStringName("get_pick_color"),
			3444240500,
		)
	})
	colorPickerButtonMethodGetPicker = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("ColorPickerButton"),
			gdextension.InternStringName("get_picker"),
			331835996,
		)
	})
	colorPickerButtonMethodGetPopup = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("ColorPickerButton"),
			gdextension.InternStringName("get_popup"),
			1322440207,
		)
	})
	colorPickerButtonMethodSetEditAlpha = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("ColorPickerButton"),
			gdextension.InternStringName("set_edit_alpha"),
			2586408642,
		)
	})
	colorPickerButtonMethodIsEditingAlpha = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("ColorPickerButton"),
			gdextension.InternStringName("is_editing_alpha"),
			36873697,
		)
	})
	colorPickerButtonMethodSetEditIntensity = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("ColorPickerButton"),
			gdextension.InternStringName("set_edit_intensity"),
			2586408642,
		)
	})
	colorPickerButtonMethodIsEditingIntensity = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("ColorPickerButton"),
			gdextension.InternStringName("is_editing_intensity"),
			36873697,
		)
	})
)

// SetPickColor mirrors the Godot ColorPickerButton.set_pick_color method.
func (self *ColorPickerButton) SetPickColor(color variant.Color) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&color)),
	}
	gdextension.CallMethodBindPtrCall(colorPickerButtonMethodSetPickColor(), self.Ptr(), args[:], nil)
}

// GetPickColor mirrors the Godot ColorPickerButton.get_pick_color method.
func (self *ColorPickerButton) GetPickColor() variant.Color {
	var ret variant.Color
	gdextension.CallMethodBindPtrCall(colorPickerButtonMethodGetPickColor(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// GetPicker mirrors the Godot ColorPickerButton.get_picker method.
func (self *ColorPickerButton) GetPicker() *ColorPicker {
	var ret gdextension.ObjectPtr
	gdextension.CallMethodBindPtrCall(colorPickerButtonMethodGetPicker(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ColorPickerFromPtr(ret)
}

// GetPopup mirrors the Godot ColorPickerButton.get_popup method.
func (self *ColorPickerButton) GetPopup() *PopupPanel {
	var ret gdextension.ObjectPtr
	gdextension.CallMethodBindPtrCall(colorPickerButtonMethodGetPopup(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return PopupPanelFromPtr(ret)
}

// SetEditAlpha mirrors the Godot ColorPickerButton.set_edit_alpha method.
func (self *ColorPickerButton) SetEditAlpha(show bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&show)),
	}
	gdextension.CallMethodBindPtrCall(colorPickerButtonMethodSetEditAlpha(), self.Ptr(), args[:], nil)
}

// IsEditingAlpha mirrors the Godot ColorPickerButton.is_editing_alpha method.
func (self *ColorPickerButton) IsEditingAlpha() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(colorPickerButtonMethodIsEditingAlpha(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetEditIntensity mirrors the Godot ColorPickerButton.set_edit_intensity method.
func (self *ColorPickerButton) SetEditIntensity(show bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&show)),
	}
	gdextension.CallMethodBindPtrCall(colorPickerButtonMethodSetEditIntensity(), self.Ptr(), args[:], nil)
}

// IsEditingIntensity mirrors the Godot ColorPickerButton.is_editing_intensity method.
func (self *ColorPickerButton) IsEditingIntensity() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(colorPickerButtonMethodIsEditingIntensity(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}
