// Code generated by godot-go-bindgen. DO NOT EDIT.

package core

import (
	"sync"
	"unsafe"

	"github.com/legendary-code/godot-go/gdextension"
	"github.com/legendary-code/godot-go/variant"
)

// CPUParticles2D mirrors the Godot engine class CPUParticles2D.
type CPUParticles2D struct {
	Node2D
}

// CPUParticles2DFromPtr wraps an existing host-allocated GDExtensionObjectPtr in a
// *CPUParticles2D. Returns nil on a nil input.
func CPUParticles2DFromPtr(p gdextension.ObjectPtr) *CPUParticles2D {
	if p == nil {
		return nil
	}
	ret := &CPUParticles2D{}
	ret.BindPtr(p)
	return ret
}

// CPUParticles2DDrawOrder is the Godot CPUParticles2DDrawOrder enum.
type CPUParticles2DDrawOrder int64

const (
	CPUParticles2D_DRAW_ORDER_INDEX    CPUParticles2DDrawOrder = 0
	CPUParticles2D_DRAW_ORDER_LIFETIME CPUParticles2DDrawOrder = 1
)

// CPUParticles2DParameter is the Godot CPUParticles2DParameter enum.
type CPUParticles2DParameter int64

const (
	CPUParticles2D_PARAM_INITIAL_LINEAR_VELOCITY CPUParticles2DParameter = 0
	CPUParticles2D_PARAM_ANGULAR_VELOCITY        CPUParticles2DParameter = 1
	CPUParticles2D_PARAM_ORBIT_VELOCITY          CPUParticles2DParameter = 2
	CPUParticles2D_PARAM_LINEAR_ACCEL            CPUParticles2DParameter = 3
	CPUParticles2D_PARAM_RADIAL_ACCEL            CPUParticles2DParameter = 4
	CPUParticles2D_PARAM_TANGENTIAL_ACCEL        CPUParticles2DParameter = 5
	CPUParticles2D_PARAM_DAMPING                 CPUParticles2DParameter = 6
	CPUParticles2D_PARAM_ANGLE                   CPUParticles2DParameter = 7
	CPUParticles2D_PARAM_SCALE                   CPUParticles2DParameter = 8
	CPUParticles2D_PARAM_HUE_VARIATION           CPUParticles2DParameter = 9
	CPUParticles2D_PARAM_ANIM_SPEED              CPUParticles2DParameter = 10
	CPUParticles2D_PARAM_ANIM_OFFSET             CPUParticles2DParameter = 11
	CPUParticles2D_PARAM_MAX                     CPUParticles2DParameter = 12
)

// CPUParticles2DParticleFlags is the Godot CPUParticles2DParticleFlags enum.
type CPUParticles2DParticleFlags int64

const (
	CPUParticles2D_PARTICLE_FLAG_ALIGN_Y_TO_VELOCITY CPUParticles2DParticleFlags = 0
	CPUParticles2D_PARTICLE_FLAG_ROTATE_Y            CPUParticles2DParticleFlags = 1
	CPUParticles2D_PARTICLE_FLAG_DISABLE_Z           CPUParticles2DParticleFlags = 2
	CPUParticles2D_PARTICLE_FLAG_MAX                 CPUParticles2DParticleFlags = 3
)

// CPUParticles2DEmissionShape is the Godot CPUParticles2DEmissionShape enum.
type CPUParticles2DEmissionShape int64

const (
	CPUParticles2D_EMISSION_SHAPE_POINT           CPUParticles2DEmissionShape = 0
	CPUParticles2D_EMISSION_SHAPE_SPHERE          CPUParticles2DEmissionShape = 1
	CPUParticles2D_EMISSION_SHAPE_SPHERE_SURFACE  CPUParticles2DEmissionShape = 2
	CPUParticles2D_EMISSION_SHAPE_RECTANGLE       CPUParticles2DEmissionShape = 3
	CPUParticles2D_EMISSION_SHAPE_POINTS          CPUParticles2DEmissionShape = 4
	CPUParticles2D_EMISSION_SHAPE_DIRECTED_POINTS CPUParticles2DEmissionShape = 5
	CPUParticles2D_EMISSION_SHAPE_RING            CPUParticles2DEmissionShape = 6
	CPUParticles2D_EMISSION_SHAPE_MAX             CPUParticles2DEmissionShape = 7
)

var (
	cPUParticles2DMethodSetEmitting = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("set_emitting"),
			2586408642,
		)
	})
	cPUParticles2DMethodSetAmount = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("set_amount"),
			1286410249,
		)
	})
	cPUParticles2DMethodSetLifetime = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("set_lifetime"),
			373806689,
		)
	})
	cPUParticles2DMethodSetOneShot = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("set_one_shot"),
			2586408642,
		)
	})
	cPUParticles2DMethodSetPreProcessTime = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("set_pre_process_time"),
			373806689,
		)
	})
	cPUParticles2DMethodSetExplosivenessRatio = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("set_explosiveness_ratio"),
			373806689,
		)
	})
	cPUParticles2DMethodSetRandomnessRatio = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("set_randomness_ratio"),
			373806689,
		)
	})
	cPUParticles2DMethodSetLifetimeRandomness = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("set_lifetime_randomness"),
			373806689,
		)
	})
	cPUParticles2DMethodSetUseLocalCoordinates = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("set_use_local_coordinates"),
			2586408642,
		)
	})
	cPUParticles2DMethodSetFixedFps = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("set_fixed_fps"),
			1286410249,
		)
	})
	cPUParticles2DMethodSetFractionalDelta = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("set_fractional_delta"),
			2586408642,
		)
	})
	cPUParticles2DMethodSetSpeedScale = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("set_speed_scale"),
			373806689,
		)
	})
	cPUParticles2DMethodRequestParticlesProcess = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("request_particles_process"),
			373806689,
		)
	})
	cPUParticles2DMethodIsEmitting = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("is_emitting"),
			36873697,
		)
	})
	cPUParticles2DMethodGetAmount = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("get_amount"),
			3905245786,
		)
	})
	cPUParticles2DMethodGetLifetime = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("get_lifetime"),
			1740695150,
		)
	})
	cPUParticles2DMethodGetOneShot = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("get_one_shot"),
			36873697,
		)
	})
	cPUParticles2DMethodGetPreProcessTime = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("get_pre_process_time"),
			1740695150,
		)
	})
	cPUParticles2DMethodGetExplosivenessRatio = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("get_explosiveness_ratio"),
			1740695150,
		)
	})
	cPUParticles2DMethodGetRandomnessRatio = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("get_randomness_ratio"),
			1740695150,
		)
	})
	cPUParticles2DMethodGetLifetimeRandomness = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("get_lifetime_randomness"),
			1740695150,
		)
	})
	cPUParticles2DMethodGetUseLocalCoordinates = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("get_use_local_coordinates"),
			36873697,
		)
	})
	cPUParticles2DMethodGetFixedFps = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("get_fixed_fps"),
			3905245786,
		)
	})
	cPUParticles2DMethodGetFractionalDelta = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("get_fractional_delta"),
			36873697,
		)
	})
	cPUParticles2DMethodGetSpeedScale = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("get_speed_scale"),
			1740695150,
		)
	})
	cPUParticles2DMethodSetUseFixedSeed = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("set_use_fixed_seed"),
			2586408642,
		)
	})
	cPUParticles2DMethodGetUseFixedSeed = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("get_use_fixed_seed"),
			36873697,
		)
	})
	cPUParticles2DMethodSetSeed = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("set_seed"),
			1286410249,
		)
	})
	cPUParticles2DMethodGetSeed = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("get_seed"),
			3905245786,
		)
	})
	cPUParticles2DMethodSetDrawOrder = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("set_draw_order"),
			4183193490,
		)
	})
	cPUParticles2DMethodGetDrawOrder = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("get_draw_order"),
			1668655735,
		)
	})
	cPUParticles2DMethodSetTexture = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("set_texture"),
			4051416890,
		)
	})
	cPUParticles2DMethodGetTexture = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("get_texture"),
			3635182373,
		)
	})
	cPUParticles2DMethodRestart = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("restart"),
			107499316,
		)
	})
	cPUParticles2DMethodSetDirection = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("set_direction"),
			743155724,
		)
	})
	cPUParticles2DMethodGetDirection = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("get_direction"),
			3341600327,
		)
	})
	cPUParticles2DMethodSetSpread = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("set_spread"),
			373806689,
		)
	})
	cPUParticles2DMethodGetSpread = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("get_spread"),
			1740695150,
		)
	})
	cPUParticles2DMethodSetParamMin = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("set_param_min"),
			3320615296,
		)
	})
	cPUParticles2DMethodGetParamMin = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("get_param_min"),
			2038050600,
		)
	})
	cPUParticles2DMethodSetParamMax = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("set_param_max"),
			3320615296,
		)
	})
	cPUParticles2DMethodGetParamMax = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("get_param_max"),
			2038050600,
		)
	})
	cPUParticles2DMethodSetParamCurve = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("set_param_curve"),
			2959350143,
		)
	})
	cPUParticles2DMethodGetParamCurve = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("get_param_curve"),
			2603158474,
		)
	})
	cPUParticles2DMethodSetColor = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("set_color"),
			2920490490,
		)
	})
	cPUParticles2DMethodGetColor = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("get_color"),
			3444240500,
		)
	})
	cPUParticles2DMethodSetColorRamp = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("set_color_ramp"),
			2756054477,
		)
	})
	cPUParticles2DMethodGetColorRamp = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("get_color_ramp"),
			132272999,
		)
	})
	cPUParticles2DMethodSetColorInitialRamp = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("set_color_initial_ramp"),
			2756054477,
		)
	})
	cPUParticles2DMethodGetColorInitialRamp = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("get_color_initial_ramp"),
			132272999,
		)
	})
	cPUParticles2DMethodSetParticleFlag = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("set_particle_flag"),
			4178137949,
		)
	})
	cPUParticles2DMethodGetParticleFlag = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("get_particle_flag"),
			2829976507,
		)
	})
	cPUParticles2DMethodSetEmissionShape = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("set_emission_shape"),
			393763892,
		)
	})
	cPUParticles2DMethodGetEmissionShape = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("get_emission_shape"),
			1740246024,
		)
	})
	cPUParticles2DMethodSetEmissionSphereRadius = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("set_emission_sphere_radius"),
			373806689,
		)
	})
	cPUParticles2DMethodGetEmissionSphereRadius = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("get_emission_sphere_radius"),
			1740695150,
		)
	})
	cPUParticles2DMethodSetEmissionRectExtents = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("set_emission_rect_extents"),
			743155724,
		)
	})
	cPUParticles2DMethodGetEmissionRectExtents = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("get_emission_rect_extents"),
			3341600327,
		)
	})
	cPUParticles2DMethodSetEmissionPoints = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("set_emission_points"),
			1509147220,
		)
	})
	cPUParticles2DMethodGetEmissionPoints = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("get_emission_points"),
			2961356807,
		)
	})
	cPUParticles2DMethodSetEmissionNormals = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("set_emission_normals"),
			1509147220,
		)
	})
	cPUParticles2DMethodGetEmissionNormals = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("get_emission_normals"),
			2961356807,
		)
	})
	cPUParticles2DMethodSetEmissionColors = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("set_emission_colors"),
			3546319833,
		)
	})
	cPUParticles2DMethodGetEmissionColors = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("get_emission_colors"),
			1392750486,
		)
	})
	cPUParticles2DMethodSetEmissionRingInnerRadius = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("set_emission_ring_inner_radius"),
			373806689,
		)
	})
	cPUParticles2DMethodGetEmissionRingInnerRadius = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("get_emission_ring_inner_radius"),
			1740695150,
		)
	})
	cPUParticles2DMethodSetEmissionRingRadius = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("set_emission_ring_radius"),
			373806689,
		)
	})
	cPUParticles2DMethodGetEmissionRingRadius = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("get_emission_ring_radius"),
			1740695150,
		)
	})
	cPUParticles2DMethodGetGravity = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("get_gravity"),
			3341600327,
		)
	})
	cPUParticles2DMethodSetGravity = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("set_gravity"),
			743155724,
		)
	})
	cPUParticles2DMethodGetSplitScale = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("get_split_scale"),
			2240911060,
		)
	})
	cPUParticles2DMethodSetSplitScale = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("set_split_scale"),
			2586408642,
		)
	})
	cPUParticles2DMethodGetScaleCurveX = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("get_scale_curve_x"),
			2460114913,
		)
	})
	cPUParticles2DMethodSetScaleCurveX = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("set_scale_curve_x"),
			270443179,
		)
	})
	cPUParticles2DMethodGetScaleCurveY = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("get_scale_curve_y"),
			2460114913,
		)
	})
	cPUParticles2DMethodSetScaleCurveY = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("set_scale_curve_y"),
			270443179,
		)
	})
	cPUParticles2DMethodConvertFromParticles = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("CPUParticles2D"),
			gdextension.InternStringName("convert_from_particles"),
			1078189570,
		)
	})
)

// SetEmitting mirrors the Godot CPUParticles2D.set_emitting method.
func (self *CPUParticles2D) SetEmitting(emitting bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&emitting)),
	}
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodSetEmitting(), self.Ptr(), args[:], nil)
}

// SetAmount mirrors the Godot CPUParticles2D.set_amount method.
func (self *CPUParticles2D) SetAmount(amount int64) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&amount)),
	}
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodSetAmount(), self.Ptr(), args[:], nil)
}

// SetLifetime mirrors the Godot CPUParticles2D.set_lifetime method.
func (self *CPUParticles2D) SetLifetime(secs float32) {
	tmp_secs := float64(secs)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_secs)),
	}
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodSetLifetime(), self.Ptr(), args[:], nil)
}

// SetOneShot mirrors the Godot CPUParticles2D.set_one_shot method.
func (self *CPUParticles2D) SetOneShot(enable bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&enable)),
	}
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodSetOneShot(), self.Ptr(), args[:], nil)
}

// SetPreProcessTime mirrors the Godot CPUParticles2D.set_pre_process_time method.
func (self *CPUParticles2D) SetPreProcessTime(secs float32) {
	tmp_secs := float64(secs)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_secs)),
	}
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodSetPreProcessTime(), self.Ptr(), args[:], nil)
}

// SetExplosivenessRatio mirrors the Godot CPUParticles2D.set_explosiveness_ratio method.
func (self *CPUParticles2D) SetExplosivenessRatio(ratio float32) {
	tmp_ratio := float64(ratio)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_ratio)),
	}
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodSetExplosivenessRatio(), self.Ptr(), args[:], nil)
}

// SetRandomnessRatio mirrors the Godot CPUParticles2D.set_randomness_ratio method.
func (self *CPUParticles2D) SetRandomnessRatio(ratio float32) {
	tmp_ratio := float64(ratio)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_ratio)),
	}
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodSetRandomnessRatio(), self.Ptr(), args[:], nil)
}

// SetLifetimeRandomness mirrors the Godot CPUParticles2D.set_lifetime_randomness method.
func (self *CPUParticles2D) SetLifetimeRandomness(random float32) {
	tmp_random := float64(random)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_random)),
	}
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodSetLifetimeRandomness(), self.Ptr(), args[:], nil)
}

// SetUseLocalCoordinates mirrors the Godot CPUParticles2D.set_use_local_coordinates method.
func (self *CPUParticles2D) SetUseLocalCoordinates(enable bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&enable)),
	}
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodSetUseLocalCoordinates(), self.Ptr(), args[:], nil)
}

// SetFixedFps mirrors the Godot CPUParticles2D.set_fixed_fps method.
func (self *CPUParticles2D) SetFixedFps(fps int64) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&fps)),
	}
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodSetFixedFps(), self.Ptr(), args[:], nil)
}

// SetFractionalDelta mirrors the Godot CPUParticles2D.set_fractional_delta method.
func (self *CPUParticles2D) SetFractionalDelta(enable bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&enable)),
	}
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodSetFractionalDelta(), self.Ptr(), args[:], nil)
}

// SetSpeedScale mirrors the Godot CPUParticles2D.set_speed_scale method.
func (self *CPUParticles2D) SetSpeedScale(scale float32) {
	tmp_scale := float64(scale)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_scale)),
	}
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodSetSpeedScale(), self.Ptr(), args[:], nil)
}

// RequestParticlesProcess mirrors the Godot CPUParticles2D.request_particles_process method.
func (self *CPUParticles2D) RequestParticlesProcess(process_time float32) {
	tmp_process_time := float64(process_time)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_process_time)),
	}
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodRequestParticlesProcess(), self.Ptr(), args[:], nil)
}

// IsEmitting mirrors the Godot CPUParticles2D.is_emitting method.
func (self *CPUParticles2D) IsEmitting() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodIsEmitting(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// GetAmount mirrors the Godot CPUParticles2D.get_amount method.
func (self *CPUParticles2D) GetAmount() int64 {
	var ret int64
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodGetAmount(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// GetLifetime mirrors the Godot CPUParticles2D.get_lifetime method.
func (self *CPUParticles2D) GetLifetime() float32 {
	var raw float64
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodGetLifetime(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}

// GetOneShot mirrors the Godot CPUParticles2D.get_one_shot method.
func (self *CPUParticles2D) GetOneShot() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodGetOneShot(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// GetPreProcessTime mirrors the Godot CPUParticles2D.get_pre_process_time method.
func (self *CPUParticles2D) GetPreProcessTime() float32 {
	var raw float64
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodGetPreProcessTime(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}

// GetExplosivenessRatio mirrors the Godot CPUParticles2D.get_explosiveness_ratio method.
func (self *CPUParticles2D) GetExplosivenessRatio() float32 {
	var raw float64
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodGetExplosivenessRatio(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}

// GetRandomnessRatio mirrors the Godot CPUParticles2D.get_randomness_ratio method.
func (self *CPUParticles2D) GetRandomnessRatio() float32 {
	var raw float64
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodGetRandomnessRatio(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}

// GetLifetimeRandomness mirrors the Godot CPUParticles2D.get_lifetime_randomness method.
func (self *CPUParticles2D) GetLifetimeRandomness() float32 {
	var raw float64
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodGetLifetimeRandomness(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}

// GetUseLocalCoordinates mirrors the Godot CPUParticles2D.get_use_local_coordinates method.
func (self *CPUParticles2D) GetUseLocalCoordinates() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodGetUseLocalCoordinates(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// GetFixedFps mirrors the Godot CPUParticles2D.get_fixed_fps method.
func (self *CPUParticles2D) GetFixedFps() int64 {
	var ret int64
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodGetFixedFps(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// GetFractionalDelta mirrors the Godot CPUParticles2D.get_fractional_delta method.
func (self *CPUParticles2D) GetFractionalDelta() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodGetFractionalDelta(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// GetSpeedScale mirrors the Godot CPUParticles2D.get_speed_scale method.
func (self *CPUParticles2D) GetSpeedScale() float32 {
	var raw float64
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodGetSpeedScale(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}

// SetUseFixedSeed mirrors the Godot CPUParticles2D.set_use_fixed_seed method.
func (self *CPUParticles2D) SetUseFixedSeed(use_fixed_seed bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&use_fixed_seed)),
	}
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodSetUseFixedSeed(), self.Ptr(), args[:], nil)
}

// GetUseFixedSeed mirrors the Godot CPUParticles2D.get_use_fixed_seed method.
func (self *CPUParticles2D) GetUseFixedSeed() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodGetUseFixedSeed(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetSeed mirrors the Godot CPUParticles2D.set_seed method.
func (self *CPUParticles2D) SetSeed(seed int64) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&seed)),
	}
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodSetSeed(), self.Ptr(), args[:], nil)
}

// GetSeed mirrors the Godot CPUParticles2D.get_seed method.
func (self *CPUParticles2D) GetSeed() int64 {
	var ret int64
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodGetSeed(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetDrawOrder mirrors the Godot CPUParticles2D.set_draw_order method.
func (self *CPUParticles2D) SetDrawOrder(order CPUParticles2DDrawOrder) {
	tmp_order := int64(order)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_order)),
	}
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodSetDrawOrder(), self.Ptr(), args[:], nil)
}

// GetDrawOrder mirrors the Godot CPUParticles2D.get_draw_order method.
func (self *CPUParticles2D) GetDrawOrder() CPUParticles2DDrawOrder {
	var ret int64
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodGetDrawOrder(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return CPUParticles2DDrawOrder(ret)
}

// SetTexture mirrors the Godot CPUParticles2D.set_texture method.
func (self *CPUParticles2D) SetTexture(texture *Texture2D) {
	var tmp_texture gdextension.ObjectPtr
	if texture != nil {
		tmp_texture = texture.Ptr()
	}

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_texture)),
	}
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodSetTexture(), self.Ptr(), args[:], nil)
}

// GetTexture mirrors the Godot CPUParticles2D.get_texture method.
func (self *CPUParticles2D) GetTexture() *Texture2D {
	var ret gdextension.ObjectPtr
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodGetTexture(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return Texture2DFromPtr(ret)
}

// Restart mirrors the Godot CPUParticles2D.restart method.
func (self *CPUParticles2D) Restart(keep_seed bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&keep_seed)),
	}
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodRestart(), self.Ptr(), args[:], nil)
}

// SetDirection mirrors the Godot CPUParticles2D.set_direction method.
func (self *CPUParticles2D) SetDirection(direction variant.Vector2) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&direction)),
	}
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodSetDirection(), self.Ptr(), args[:], nil)
}

// GetDirection mirrors the Godot CPUParticles2D.get_direction method.
func (self *CPUParticles2D) GetDirection() variant.Vector2 {
	var ret variant.Vector2
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodGetDirection(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetSpread mirrors the Godot CPUParticles2D.set_spread method.
func (self *CPUParticles2D) SetSpread(spread float32) {
	tmp_spread := float64(spread)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_spread)),
	}
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodSetSpread(), self.Ptr(), args[:], nil)
}

// GetSpread mirrors the Godot CPUParticles2D.get_spread method.
func (self *CPUParticles2D) GetSpread() float32 {
	var raw float64
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodGetSpread(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}

// SetParamMin mirrors the Godot CPUParticles2D.set_param_min method.
func (self *CPUParticles2D) SetParamMin(param CPUParticles2DParameter, value float32) {
	tmp_param := int64(param)

	tmp_value := float64(value)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_param)),
		gdextension.TypePtr(unsafe.Pointer(&tmp_value)),
	}
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodSetParamMin(), self.Ptr(), args[:], nil)
}

// GetParamMin mirrors the Godot CPUParticles2D.get_param_min method.
func (self *CPUParticles2D) GetParamMin(param CPUParticles2DParameter) float32 {
	var raw float64
	tmp_param := int64(param)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_param)),
	}
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodGetParamMin(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}

// SetParamMax mirrors the Godot CPUParticles2D.set_param_max method.
func (self *CPUParticles2D) SetParamMax(param CPUParticles2DParameter, value float32) {
	tmp_param := int64(param)

	tmp_value := float64(value)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_param)),
		gdextension.TypePtr(unsafe.Pointer(&tmp_value)),
	}
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodSetParamMax(), self.Ptr(), args[:], nil)
}

// GetParamMax mirrors the Godot CPUParticles2D.get_param_max method.
func (self *CPUParticles2D) GetParamMax(param CPUParticles2DParameter) float32 {
	var raw float64
	tmp_param := int64(param)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_param)),
	}
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodGetParamMax(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}

// SetParamCurve mirrors the Godot CPUParticles2D.set_param_curve method.
func (self *CPUParticles2D) SetParamCurve(param CPUParticles2DParameter, curve *Curve) {
	tmp_param := int64(param)

	var tmp_curve gdextension.ObjectPtr
	if curve != nil {
		tmp_curve = curve.Ptr()
	}

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_param)),
		gdextension.TypePtr(unsafe.Pointer(&tmp_curve)),
	}
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodSetParamCurve(), self.Ptr(), args[:], nil)
}

// GetParamCurve mirrors the Godot CPUParticles2D.get_param_curve method.
func (self *CPUParticles2D) GetParamCurve(param CPUParticles2DParameter) *Curve {
	var ret gdextension.ObjectPtr
	tmp_param := int64(param)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_param)),
	}
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodGetParamCurve(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return CurveFromPtr(ret)
}

// SetColor mirrors the Godot CPUParticles2D.set_color method.
func (self *CPUParticles2D) SetColor(color variant.Color) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&color)),
	}
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodSetColor(), self.Ptr(), args[:], nil)
}

// GetColor mirrors the Godot CPUParticles2D.get_color method.
func (self *CPUParticles2D) GetColor() variant.Color {
	var ret variant.Color
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodGetColor(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetColorRamp mirrors the Godot CPUParticles2D.set_color_ramp method.
func (self *CPUParticles2D) SetColorRamp(ramp *Gradient) {
	var tmp_ramp gdextension.ObjectPtr
	if ramp != nil {
		tmp_ramp = ramp.Ptr()
	}

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_ramp)),
	}
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodSetColorRamp(), self.Ptr(), args[:], nil)
}

// GetColorRamp mirrors the Godot CPUParticles2D.get_color_ramp method.
func (self *CPUParticles2D) GetColorRamp() *Gradient {
	var ret gdextension.ObjectPtr
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodGetColorRamp(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return GradientFromPtr(ret)
}

// SetColorInitialRamp mirrors the Godot CPUParticles2D.set_color_initial_ramp method.
func (self *CPUParticles2D) SetColorInitialRamp(ramp *Gradient) {
	var tmp_ramp gdextension.ObjectPtr
	if ramp != nil {
		tmp_ramp = ramp.Ptr()
	}

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_ramp)),
	}
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodSetColorInitialRamp(), self.Ptr(), args[:], nil)
}

// GetColorInitialRamp mirrors the Godot CPUParticles2D.get_color_initial_ramp method.
func (self *CPUParticles2D) GetColorInitialRamp() *Gradient {
	var ret gdextension.ObjectPtr
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodGetColorInitialRamp(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return GradientFromPtr(ret)
}

// SetParticleFlag mirrors the Godot CPUParticles2D.set_particle_flag method.
func (self *CPUParticles2D) SetParticleFlag(particle_flag CPUParticles2DParticleFlags, enable bool) {
	tmp_particle_flag := int64(particle_flag)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_particle_flag)),
		gdextension.TypePtr(unsafe.Pointer(&enable)),
	}
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodSetParticleFlag(), self.Ptr(), args[:], nil)
}

// GetParticleFlag mirrors the Godot CPUParticles2D.get_particle_flag method.
func (self *CPUParticles2D) GetParticleFlag(particle_flag CPUParticles2DParticleFlags) bool {
	var ret bool
	tmp_particle_flag := int64(particle_flag)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_particle_flag)),
	}
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodGetParticleFlag(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetEmissionShape mirrors the Godot CPUParticles2D.set_emission_shape method.
func (self *CPUParticles2D) SetEmissionShape(shape CPUParticles2DEmissionShape) {
	tmp_shape := int64(shape)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_shape)),
	}
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodSetEmissionShape(), self.Ptr(), args[:], nil)
}

// GetEmissionShape mirrors the Godot CPUParticles2D.get_emission_shape method.
func (self *CPUParticles2D) GetEmissionShape() CPUParticles2DEmissionShape {
	var ret int64
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodGetEmissionShape(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return CPUParticles2DEmissionShape(ret)
}

// SetEmissionSphereRadius mirrors the Godot CPUParticles2D.set_emission_sphere_radius method.
func (self *CPUParticles2D) SetEmissionSphereRadius(radius float32) {
	tmp_radius := float64(radius)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_radius)),
	}
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodSetEmissionSphereRadius(), self.Ptr(), args[:], nil)
}

// GetEmissionSphereRadius mirrors the Godot CPUParticles2D.get_emission_sphere_radius method.
func (self *CPUParticles2D) GetEmissionSphereRadius() float32 {
	var raw float64
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodGetEmissionSphereRadius(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}

// SetEmissionRectExtents mirrors the Godot CPUParticles2D.set_emission_rect_extents method.
func (self *CPUParticles2D) SetEmissionRectExtents(extents variant.Vector2) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&extents)),
	}
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodSetEmissionRectExtents(), self.Ptr(), args[:], nil)
}

// GetEmissionRectExtents mirrors the Godot CPUParticles2D.get_emission_rect_extents method.
func (self *CPUParticles2D) GetEmissionRectExtents() variant.Vector2 {
	var ret variant.Vector2
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodGetEmissionRectExtents(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetEmissionPoints mirrors the Godot CPUParticles2D.set_emission_points method.
func (self *CPUParticles2D) SetEmissionPoints(array variant.PackedVector2Array) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&array)),
	}
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodSetEmissionPoints(), self.Ptr(), args[:], nil)
}

// GetEmissionPoints mirrors the Godot CPUParticles2D.get_emission_points method.
func (self *CPUParticles2D) GetEmissionPoints() variant.PackedVector2Array {
	var ret variant.PackedVector2Array
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodGetEmissionPoints(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetEmissionNormals mirrors the Godot CPUParticles2D.set_emission_normals method.
func (self *CPUParticles2D) SetEmissionNormals(array variant.PackedVector2Array) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&array)),
	}
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodSetEmissionNormals(), self.Ptr(), args[:], nil)
}

// GetEmissionNormals mirrors the Godot CPUParticles2D.get_emission_normals method.
func (self *CPUParticles2D) GetEmissionNormals() variant.PackedVector2Array {
	var ret variant.PackedVector2Array
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodGetEmissionNormals(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetEmissionColors mirrors the Godot CPUParticles2D.set_emission_colors method.
func (self *CPUParticles2D) SetEmissionColors(array variant.PackedColorArray) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&array)),
	}
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodSetEmissionColors(), self.Ptr(), args[:], nil)
}

// GetEmissionColors mirrors the Godot CPUParticles2D.get_emission_colors method.
func (self *CPUParticles2D) GetEmissionColors() variant.PackedColorArray {
	var ret variant.PackedColorArray
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodGetEmissionColors(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetEmissionRingInnerRadius mirrors the Godot CPUParticles2D.set_emission_ring_inner_radius method.
func (self *CPUParticles2D) SetEmissionRingInnerRadius(inner_radius float32) {
	tmp_inner_radius := float64(inner_radius)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_inner_radius)),
	}
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodSetEmissionRingInnerRadius(), self.Ptr(), args[:], nil)
}

// GetEmissionRingInnerRadius mirrors the Godot CPUParticles2D.get_emission_ring_inner_radius method.
func (self *CPUParticles2D) GetEmissionRingInnerRadius() float32 {
	var raw float64
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodGetEmissionRingInnerRadius(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}

// SetEmissionRingRadius mirrors the Godot CPUParticles2D.set_emission_ring_radius method.
func (self *CPUParticles2D) SetEmissionRingRadius(radius float32) {
	tmp_radius := float64(radius)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_radius)),
	}
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodSetEmissionRingRadius(), self.Ptr(), args[:], nil)
}

// GetEmissionRingRadius mirrors the Godot CPUParticles2D.get_emission_ring_radius method.
func (self *CPUParticles2D) GetEmissionRingRadius() float32 {
	var raw float64
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodGetEmissionRingRadius(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}

// GetGravity mirrors the Godot CPUParticles2D.get_gravity method.
func (self *CPUParticles2D) GetGravity() variant.Vector2 {
	var ret variant.Vector2
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodGetGravity(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetGravity mirrors the Godot CPUParticles2D.set_gravity method.
func (self *CPUParticles2D) SetGravity(accel_vec variant.Vector2) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&accel_vec)),
	}
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodSetGravity(), self.Ptr(), args[:], nil)
}

// GetSplitScale mirrors the Godot CPUParticles2D.get_split_scale method.
func (self *CPUParticles2D) GetSplitScale() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodGetSplitScale(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetSplitScale mirrors the Godot CPUParticles2D.set_split_scale method.
func (self *CPUParticles2D) SetSplitScale(split_scale bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&split_scale)),
	}
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodSetSplitScale(), self.Ptr(), args[:], nil)
}

// GetScaleCurveX mirrors the Godot CPUParticles2D.get_scale_curve_x method.
func (self *CPUParticles2D) GetScaleCurveX() *Curve {
	var ret gdextension.ObjectPtr
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodGetScaleCurveX(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return CurveFromPtr(ret)
}

// SetScaleCurveX mirrors the Godot CPUParticles2D.set_scale_curve_x method.
func (self *CPUParticles2D) SetScaleCurveX(scale_curve *Curve) {
	var tmp_scale_curve gdextension.ObjectPtr
	if scale_curve != nil {
		tmp_scale_curve = scale_curve.Ptr()
	}

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_scale_curve)),
	}
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodSetScaleCurveX(), self.Ptr(), args[:], nil)
}

// GetScaleCurveY mirrors the Godot CPUParticles2D.get_scale_curve_y method.
func (self *CPUParticles2D) GetScaleCurveY() *Curve {
	var ret gdextension.ObjectPtr
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodGetScaleCurveY(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return CurveFromPtr(ret)
}

// SetScaleCurveY mirrors the Godot CPUParticles2D.set_scale_curve_y method.
func (self *CPUParticles2D) SetScaleCurveY(scale_curve *Curve) {
	var tmp_scale_curve gdextension.ObjectPtr
	if scale_curve != nil {
		tmp_scale_curve = scale_curve.Ptr()
	}

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_scale_curve)),
	}
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodSetScaleCurveY(), self.Ptr(), args[:], nil)
}

// ConvertFromParticles mirrors the Godot CPUParticles2D.convert_from_particles method.
func (self *CPUParticles2D) ConvertFromParticles(particles *Node) {
	var tmp_particles gdextension.ObjectPtr
	if particles != nil {
		tmp_particles = particles.Ptr()
	}

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_particles)),
	}
	gdextension.CallMethodBindPtrCall(cPUParticles2DMethodConvertFromParticles(), self.Ptr(), args[:], nil)
}
