// Code generated by godot-go-bindgen. DO NOT EDIT.

package core

import (
	"sync"
	"unsafe"

	"github.com/legendary-code/godot-go/internal/gdextension"
)

// EncodedObjectAsID mirrors the Godot engine class EncodedObjectAsID.
type EncodedObjectAsID struct {
	RefCounted
}

// EncodedObjectAsIDFromPtr wraps an existing host-allocated GDExtensionObjectPtr in a
// *EncodedObjectAsID. Returns nil on a nil input.
func EncodedObjectAsIDFromPtr(p gdextension.ObjectPtr) *EncodedObjectAsID {
	if p == nil {
		return nil
	}
	ret := &EncodedObjectAsID{}
	ret.BindPtr(p)
	return ret
}

var (
	encodedObjectAsIDMethodSetObjectId = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("EncodedObjectAsID"),
			gdextension.InternStringName("set_object_id"),
			1286410249,
		)
	})
	encodedObjectAsIDMethodGetObjectId = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("EncodedObjectAsID"),
			gdextension.InternStringName("get_object_id"),
			3905245786,
		)
	})
)

// SetObjectId mirrors the Godot EncodedObjectAsID.set_object_id method.
func (self *EncodedObjectAsID) SetObjectId(id int64) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&id)),
	}
	gdextension.CallMethodBindPtrCall(encodedObjectAsIDMethodSetObjectId(), self.Ptr(), args[:], nil)
}

// GetObjectId mirrors the Godot EncodedObjectAsID.get_object_id method.
func (self *EncodedObjectAsID) GetObjectId() int64 {
	var ret int64
	gdextension.CallMethodBindPtrCall(encodedObjectAsIDMethodGetObjectId(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}
