// Code generated by godot-go-bindgen. DO NOT EDIT.

package core

import (
	"sync"
	"unsafe"

	"github.com/legendary-code/godot-go/internal/gdextension"
	"github.com/legendary-code/godot-go/variant"
)

// FoldableGroup mirrors the Godot engine class FoldableGroup.
type FoldableGroup struct {
	Resource
}

// FoldableGroupFromPtr wraps an existing host-allocated GDExtensionObjectPtr in a
// *FoldableGroup. Returns nil on a nil input.
func FoldableGroupFromPtr(p gdextension.ObjectPtr) *FoldableGroup {
	if p == nil {
		return nil
	}
	ret := &FoldableGroup{}
	ret.BindPtr(p)
	return ret
}

var (
	foldableGroupMethodGetExpandedContainer = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("FoldableGroup"),
			gdextension.InternStringName("get_expanded_container"),
			1427441056,
		)
	})
	foldableGroupMethodGetContainers = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("FoldableGroup"),
			gdextension.InternStringName("get_containers"),
			3995934104,
		)
	})
	foldableGroupMethodSetAllowFoldingAll = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("FoldableGroup"),
			gdextension.InternStringName("set_allow_folding_all"),
			2586408642,
		)
	})
	foldableGroupMethodIsAllowFoldingAll = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("FoldableGroup"),
			gdextension.InternStringName("is_allow_folding_all"),
			36873697,
		)
	})
)

// GetExpandedContainer mirrors the Godot FoldableGroup.get_expanded_container method.
func (self *FoldableGroup) GetExpandedContainer() *FoldableContainer {
	var ret gdextension.ObjectPtr
	gdextension.CallMethodBindPtrCall(foldableGroupMethodGetExpandedContainer(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return FoldableContainerFromPtr(ret)
}

// GetContainers mirrors the Godot FoldableGroup.get_containers method.
func (self *FoldableGroup) GetContainers() variant.Array {
	var ret variant.Array
	gdextension.CallMethodBindPtrCall(foldableGroupMethodGetContainers(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetAllowFoldingAll mirrors the Godot FoldableGroup.set_allow_folding_all method.
func (self *FoldableGroup) SetAllowFoldingAll(enabled bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&enabled)),
	}
	gdextension.CallMethodBindPtrCall(foldableGroupMethodSetAllowFoldingAll(), self.Ptr(), args[:], nil)
}

// IsAllowFoldingAll mirrors the Godot FoldableGroup.is_allow_folding_all method.
func (self *FoldableGroup) IsAllowFoldingAll() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(foldableGroupMethodIsAllowFoldingAll(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}
