// Code generated by godot-go-bindgen. DO NOT EDIT.

package core

import (
	"runtime"
	"sync"
	"unsafe"

	"github.com/legendary-code/godot-go/gdextension"
	"github.com/legendary-code/godot-go/variant"
)

// GLTFSpecGloss mirrors the Godot engine class GLTFSpecGloss.
type GLTFSpecGloss struct {
	Resource
}

// GLTFSpecGlossFromPtr wraps an existing host-allocated GDExtensionObjectPtr in a
// *GLTFSpecGloss. Returns nil on a nil input. GLTFSpecGloss descends from RefCounted, so the
// returned wrapper carries a Go finalizer that drops one engine
// reference (via Unreference, dispatched on the main thread) when
// Go's GC determines the wrapper is unreachable. Users who want
// deterministic free can call ret.Unreference() directly — the
// finalizer is harmless after the refcount hits zero.
func GLTFSpecGlossFromPtr(p gdextension.ObjectPtr) *GLTFSpecGloss {
	if p == nil {
		return nil
	}
	ret := &GLTFSpecGloss{}
	ret.BindPtr(p)
	runtime.SetFinalizer(ret, func(r *GLTFSpecGloss) {
		gdextension.RunOnMain(func() { r.Unreference() })
	})
	return ret
}

var (
	gLTFSpecGlossMethodGetDiffuseImg = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("GLTFSpecGloss"),
			gdextension.InternStringName("get_diffuse_img"),
			564927088,
		)
	})
	gLTFSpecGlossMethodSetDiffuseImg = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("GLTFSpecGloss"),
			gdextension.InternStringName("set_diffuse_img"),
			532598488,
		)
	})
	gLTFSpecGlossMethodGetDiffuseFactor = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("GLTFSpecGloss"),
			gdextension.InternStringName("get_diffuse_factor"),
			3200896285,
		)
	})
	gLTFSpecGlossMethodSetDiffuseFactor = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("GLTFSpecGloss"),
			gdextension.InternStringName("set_diffuse_factor"),
			2920490490,
		)
	})
	gLTFSpecGlossMethodGetGlossFactor = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("GLTFSpecGloss"),
			gdextension.InternStringName("get_gloss_factor"),
			191475506,
		)
	})
	gLTFSpecGlossMethodSetGlossFactor = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("GLTFSpecGloss"),
			gdextension.InternStringName("set_gloss_factor"),
			373806689,
		)
	})
	gLTFSpecGlossMethodGetSpecularFactor = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("GLTFSpecGloss"),
			gdextension.InternStringName("get_specular_factor"),
			3200896285,
		)
	})
	gLTFSpecGlossMethodSetSpecularFactor = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("GLTFSpecGloss"),
			gdextension.InternStringName("set_specular_factor"),
			2920490490,
		)
	})
	gLTFSpecGlossMethodGetSpecGlossImg = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("GLTFSpecGloss"),
			gdextension.InternStringName("get_spec_gloss_img"),
			564927088,
		)
	})
	gLTFSpecGlossMethodSetSpecGlossImg = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("GLTFSpecGloss"),
			gdextension.InternStringName("set_spec_gloss_img"),
			532598488,
		)
	})
)

// GetDiffuseImg mirrors the Godot GLTFSpecGloss.get_diffuse_img method.
func (self *GLTFSpecGloss) GetDiffuseImg() *Image {
	var ret gdextension.ObjectPtr
	gdextension.CallMethodBindPtrCall(gLTFSpecGlossMethodGetDiffuseImg(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ImageFromPtr(ret)
}

// SetDiffuseImg mirrors the Godot GLTFSpecGloss.set_diffuse_img method.
func (self *GLTFSpecGloss) SetDiffuseImg(diffuse_img *Image) {
	var tmp_diffuse_img gdextension.ObjectPtr
	if diffuse_img != nil {
		tmp_diffuse_img = diffuse_img.Ptr()
	}

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_diffuse_img)),
	}
	gdextension.CallMethodBindPtrCall(gLTFSpecGlossMethodSetDiffuseImg(), self.Ptr(), args[:], nil)
}

// GetDiffuseFactor mirrors the Godot GLTFSpecGloss.get_diffuse_factor method.
func (self *GLTFSpecGloss) GetDiffuseFactor() variant.Color {
	var ret variant.Color
	gdextension.CallMethodBindPtrCall(gLTFSpecGlossMethodGetDiffuseFactor(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetDiffuseFactor mirrors the Godot GLTFSpecGloss.set_diffuse_factor method.
func (self *GLTFSpecGloss) SetDiffuseFactor(diffuse_factor variant.Color) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&diffuse_factor)),
	}
	gdextension.CallMethodBindPtrCall(gLTFSpecGlossMethodSetDiffuseFactor(), self.Ptr(), args[:], nil)
}

// GetGlossFactor mirrors the Godot GLTFSpecGloss.get_gloss_factor method.
func (self *GLTFSpecGloss) GetGlossFactor() float32 {
	var raw float64
	gdextension.CallMethodBindPtrCall(gLTFSpecGlossMethodGetGlossFactor(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}

// SetGlossFactor mirrors the Godot GLTFSpecGloss.set_gloss_factor method.
func (self *GLTFSpecGloss) SetGlossFactor(gloss_factor float32) {
	tmp_gloss_factor := float64(gloss_factor)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_gloss_factor)),
	}
	gdextension.CallMethodBindPtrCall(gLTFSpecGlossMethodSetGlossFactor(), self.Ptr(), args[:], nil)
}

// GetSpecularFactor mirrors the Godot GLTFSpecGloss.get_specular_factor method.
func (self *GLTFSpecGloss) GetSpecularFactor() variant.Color {
	var ret variant.Color
	gdextension.CallMethodBindPtrCall(gLTFSpecGlossMethodGetSpecularFactor(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetSpecularFactor mirrors the Godot GLTFSpecGloss.set_specular_factor method.
func (self *GLTFSpecGloss) SetSpecularFactor(specular_factor variant.Color) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&specular_factor)),
	}
	gdextension.CallMethodBindPtrCall(gLTFSpecGlossMethodSetSpecularFactor(), self.Ptr(), args[:], nil)
}

// GetSpecGlossImg mirrors the Godot GLTFSpecGloss.get_spec_gloss_img method.
func (self *GLTFSpecGloss) GetSpecGlossImg() *Image {
	var ret gdextension.ObjectPtr
	gdextension.CallMethodBindPtrCall(gLTFSpecGlossMethodGetSpecGlossImg(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ImageFromPtr(ret)
}

// SetSpecGlossImg mirrors the Godot GLTFSpecGloss.set_spec_gloss_img method.
func (self *GLTFSpecGloss) SetSpecGlossImg(spec_gloss_img *Image) {
	var tmp_spec_gloss_img gdextension.ObjectPtr
	if spec_gloss_img != nil {
		tmp_spec_gloss_img = spec_gloss_img.Ptr()
	}

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_spec_gloss_img)),
	}
	gdextension.CallMethodBindPtrCall(gLTFSpecGlossMethodSetSpecGlossImg(), self.Ptr(), args[:], nil)
}
