// Code generated by godot-go-bindgen. DO NOT EDIT.

package core

import (
	"runtime"
	"sync"
	"unsafe"

	"github.com/legendary-code/godot-go/internal/gdextension"
)

// InputEventWithModifiers mirrors the Godot engine class InputEventWithModifiers.
type InputEventWithModifiers struct {
	InputEventFromWindow
}

// InputEventWithModifiersFromPtr wraps an existing host-allocated GDExtensionObjectPtr in a
// *InputEventWithModifiers. Returns nil on a nil input. InputEventWithModifiers descends from RefCounted, so the
// returned wrapper carries a Go finalizer that drops one engine
// reference (via Unreference, dispatched on the main thread) when
// Go's GC determines the wrapper is unreachable. Users who want
// deterministic free can call ret.Unreference() directly — the
// finalizer is harmless after the refcount hits zero.
func InputEventWithModifiersFromPtr(p gdextension.ObjectPtr) *InputEventWithModifiers {
	if p == nil {
		return nil
	}
	ret := &InputEventWithModifiers{}
	ret.BindPtr(p)
	runtime.SetFinalizer(ret, func(r *InputEventWithModifiers) {
		gdextension.RunOnMain(func() { r.Unreference() })
	})
	return ret
}

var (
	inputEventWithModifiersMethodSetCommandOrControlAutoremap = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("InputEventWithModifiers"),
			gdextension.InternStringName("set_command_or_control_autoremap"),
			2586408642,
		)
	})
	inputEventWithModifiersMethodIsCommandOrControlAutoremap = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("InputEventWithModifiers"),
			gdextension.InternStringName("is_command_or_control_autoremap"),
			36873697,
		)
	})
	inputEventWithModifiersMethodIsCommandOrControlPressed = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("InputEventWithModifiers"),
			gdextension.InternStringName("is_command_or_control_pressed"),
			36873697,
		)
	})
	inputEventWithModifiersMethodSetAltPressed = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("InputEventWithModifiers"),
			gdextension.InternStringName("set_alt_pressed"),
			2586408642,
		)
	})
	inputEventWithModifiersMethodIsAltPressed = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("InputEventWithModifiers"),
			gdextension.InternStringName("is_alt_pressed"),
			36873697,
		)
	})
	inputEventWithModifiersMethodSetShiftPressed = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("InputEventWithModifiers"),
			gdextension.InternStringName("set_shift_pressed"),
			2586408642,
		)
	})
	inputEventWithModifiersMethodIsShiftPressed = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("InputEventWithModifiers"),
			gdextension.InternStringName("is_shift_pressed"),
			36873697,
		)
	})
	inputEventWithModifiersMethodSetCtrlPressed = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("InputEventWithModifiers"),
			gdextension.InternStringName("set_ctrl_pressed"),
			2586408642,
		)
	})
	inputEventWithModifiersMethodIsCtrlPressed = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("InputEventWithModifiers"),
			gdextension.InternStringName("is_ctrl_pressed"),
			36873697,
		)
	})
	inputEventWithModifiersMethodSetMetaPressed = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("InputEventWithModifiers"),
			gdextension.InternStringName("set_meta_pressed"),
			2586408642,
		)
	})
	inputEventWithModifiersMethodIsMetaPressed = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("InputEventWithModifiers"),
			gdextension.InternStringName("is_meta_pressed"),
			36873697,
		)
	})
	inputEventWithModifiersMethodGetModifiersMask = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("InputEventWithModifiers"),
			gdextension.InternStringName("get_modifiers_mask"),
			1258259499,
		)
	})
)

// SetCommandOrControlAutoremap mirrors the Godot InputEventWithModifiers.set_command_or_control_autoremap method.
func (self *InputEventWithModifiers) SetCommandOrControlAutoremap(enable bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&enable)),
	}
	gdextension.CallMethodBindPtrCall(inputEventWithModifiersMethodSetCommandOrControlAutoremap(), self.Ptr(), args[:], nil)
}

// IsCommandOrControlAutoremap mirrors the Godot InputEventWithModifiers.is_command_or_control_autoremap method.
func (self *InputEventWithModifiers) IsCommandOrControlAutoremap() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(inputEventWithModifiersMethodIsCommandOrControlAutoremap(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// IsCommandOrControlPressed mirrors the Godot InputEventWithModifiers.is_command_or_control_pressed method.
func (self *InputEventWithModifiers) IsCommandOrControlPressed() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(inputEventWithModifiersMethodIsCommandOrControlPressed(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetAltPressed mirrors the Godot InputEventWithModifiers.set_alt_pressed method.
func (self *InputEventWithModifiers) SetAltPressed(pressed bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&pressed)),
	}
	gdextension.CallMethodBindPtrCall(inputEventWithModifiersMethodSetAltPressed(), self.Ptr(), args[:], nil)
}

// IsAltPressed mirrors the Godot InputEventWithModifiers.is_alt_pressed method.
func (self *InputEventWithModifiers) IsAltPressed() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(inputEventWithModifiersMethodIsAltPressed(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetShiftPressed mirrors the Godot InputEventWithModifiers.set_shift_pressed method.
func (self *InputEventWithModifiers) SetShiftPressed(pressed bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&pressed)),
	}
	gdextension.CallMethodBindPtrCall(inputEventWithModifiersMethodSetShiftPressed(), self.Ptr(), args[:], nil)
}

// IsShiftPressed mirrors the Godot InputEventWithModifiers.is_shift_pressed method.
func (self *InputEventWithModifiers) IsShiftPressed() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(inputEventWithModifiersMethodIsShiftPressed(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetCtrlPressed mirrors the Godot InputEventWithModifiers.set_ctrl_pressed method.
func (self *InputEventWithModifiers) SetCtrlPressed(pressed bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&pressed)),
	}
	gdextension.CallMethodBindPtrCall(inputEventWithModifiersMethodSetCtrlPressed(), self.Ptr(), args[:], nil)
}

// IsCtrlPressed mirrors the Godot InputEventWithModifiers.is_ctrl_pressed method.
func (self *InputEventWithModifiers) IsCtrlPressed() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(inputEventWithModifiersMethodIsCtrlPressed(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetMetaPressed mirrors the Godot InputEventWithModifiers.set_meta_pressed method.
func (self *InputEventWithModifiers) SetMetaPressed(pressed bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&pressed)),
	}
	gdextension.CallMethodBindPtrCall(inputEventWithModifiersMethodSetMetaPressed(), self.Ptr(), args[:], nil)
}

// IsMetaPressed mirrors the Godot InputEventWithModifiers.is_meta_pressed method.
func (self *InputEventWithModifiers) IsMetaPressed() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(inputEventWithModifiersMethodIsMetaPressed(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// GetModifiersMask mirrors the Godot InputEventWithModifiers.get_modifiers_mask method.
func (self *InputEventWithModifiers) GetModifiersMask() int64 {
	var ret int64
	gdextension.CallMethodBindPtrCall(inputEventWithModifiersMethodGetModifiersMask(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}
