// Code generated by godot-go-bindgen. DO NOT EDIT.

package core

import (
	"github.com/legendary-code/godot-go/internal/gdextension"
)

// JacobianIK3D mirrors the Godot engine class JacobianIK3D.
type JacobianIK3D struct {
	IterateIK3D
}

// JacobianIK3DFromPtr wraps an existing host-allocated GDExtensionObjectPtr in a
// *JacobianIK3D. Returns nil on a nil input.
func JacobianIK3DFromPtr(p gdextension.ObjectPtr) *JacobianIK3D {
	if p == nil {
		return nil
	}
	ret := &JacobianIK3D{}
	ret.BindPtr(p)
	return ret
}
