// Code generated by godot-go-bindgen. DO NOT EDIT.

package core

import (
	"sync"
	"unsafe"

	"github.com/legendary-code/godot-go/gdextension"
	"github.com/legendary-code/godot-go/variant"
)

// LimitAngularVelocityModifier3D mirrors the Godot engine class LimitAngularVelocityModifier3D.
type LimitAngularVelocityModifier3D struct {
	SkeletonModifier3D
}

// LimitAngularVelocityModifier3DFromPtr wraps an existing host-allocated GDExtensionObjectPtr in a
// *LimitAngularVelocityModifier3D. Returns nil on a nil input.
func LimitAngularVelocityModifier3DFromPtr(p gdextension.ObjectPtr) *LimitAngularVelocityModifier3D {
	if p == nil {
		return nil
	}
	ret := &LimitAngularVelocityModifier3D{}
	ret.BindPtr(p)
	return ret
}

var (
	limitAngularVelocityModifier3DMethodSetRootBoneName = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("LimitAngularVelocityModifier3D"),
			gdextension.InternStringName("set_root_bone_name"),
			501894301,
		)
	})
	limitAngularVelocityModifier3DMethodGetRootBoneName = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("LimitAngularVelocityModifier3D"),
			gdextension.InternStringName("get_root_bone_name"),
			844755477,
		)
	})
	limitAngularVelocityModifier3DMethodSetRootBone = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("LimitAngularVelocityModifier3D"),
			gdextension.InternStringName("set_root_bone"),
			3937882851,
		)
	})
	limitAngularVelocityModifier3DMethodGetRootBone = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("LimitAngularVelocityModifier3D"),
			gdextension.InternStringName("get_root_bone"),
			923996154,
		)
	})
	limitAngularVelocityModifier3DMethodSetEndBoneName = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("LimitAngularVelocityModifier3D"),
			gdextension.InternStringName("set_end_bone_name"),
			501894301,
		)
	})
	limitAngularVelocityModifier3DMethodGetEndBoneName = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("LimitAngularVelocityModifier3D"),
			gdextension.InternStringName("get_end_bone_name"),
			844755477,
		)
	})
	limitAngularVelocityModifier3DMethodSetEndBone = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("LimitAngularVelocityModifier3D"),
			gdextension.InternStringName("set_end_bone"),
			3937882851,
		)
	})
	limitAngularVelocityModifier3DMethodGetEndBone = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("LimitAngularVelocityModifier3D"),
			gdextension.InternStringName("get_end_bone"),
			923996154,
		)
	})
	limitAngularVelocityModifier3DMethodSetChainCount = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("LimitAngularVelocityModifier3D"),
			gdextension.InternStringName("set_chain_count"),
			1286410249,
		)
	})
	limitAngularVelocityModifier3DMethodGetChainCount = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("LimitAngularVelocityModifier3D"),
			gdextension.InternStringName("get_chain_count"),
			3905245786,
		)
	})
	limitAngularVelocityModifier3DMethodClearChains = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("LimitAngularVelocityModifier3D"),
			gdextension.InternStringName("clear_chains"),
			3218959716,
		)
	})
	limitAngularVelocityModifier3DMethodSetMaxAngularVelocity = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("LimitAngularVelocityModifier3D"),
			gdextension.InternStringName("set_max_angular_velocity"),
			373806689,
		)
	})
	limitAngularVelocityModifier3DMethodGetMaxAngularVelocity = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("LimitAngularVelocityModifier3D"),
			gdextension.InternStringName("get_max_angular_velocity"),
			1740695150,
		)
	})
	limitAngularVelocityModifier3DMethodSetExclude = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("LimitAngularVelocityModifier3D"),
			gdextension.InternStringName("set_exclude"),
			2586408642,
		)
	})
	limitAngularVelocityModifier3DMethodIsExclude = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("LimitAngularVelocityModifier3D"),
			gdextension.InternStringName("is_exclude"),
			36873697,
		)
	})
	limitAngularVelocityModifier3DMethodReset = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("LimitAngularVelocityModifier3D"),
			gdextension.InternStringName("reset"),
			3218959716,
		)
	})
)

// SetRootBoneName mirrors the Godot LimitAngularVelocityModifier3D.set_root_bone_name method.
func (self *LimitAngularVelocityModifier3D) SetRootBoneName(index int64, bone_name string) {
	tmp_bone_name := variant.NewStringFromString(bone_name)
	defer tmp_bone_name.Destroy()

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&index)),
		gdextension.TypePtr(unsafe.Pointer(&tmp_bone_name)),
	}
	gdextension.CallMethodBindPtrCall(limitAngularVelocityModifier3DMethodSetRootBoneName(), self.Ptr(), args[:], nil)
}

// GetRootBoneName mirrors the Godot LimitAngularVelocityModifier3D.get_root_bone_name method.
func (self *LimitAngularVelocityModifier3D) GetRootBoneName(index int64) string {
	var raw variant.String
	defer raw.Destroy()
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&index)),
	}
	gdextension.CallMethodBindPtrCall(limitAngularVelocityModifier3DMethodGetRootBoneName(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&raw)))
	return variant.StringToGo(&raw)
}

// SetRootBone mirrors the Godot LimitAngularVelocityModifier3D.set_root_bone method.
func (self *LimitAngularVelocityModifier3D) SetRootBone(index int64, bone int64) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&index)),
		gdextension.TypePtr(unsafe.Pointer(&bone)),
	}
	gdextension.CallMethodBindPtrCall(limitAngularVelocityModifier3DMethodSetRootBone(), self.Ptr(), args[:], nil)
}

// GetRootBone mirrors the Godot LimitAngularVelocityModifier3D.get_root_bone method.
func (self *LimitAngularVelocityModifier3D) GetRootBone(index int64) int64 {
	var ret int64
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&index)),
	}
	gdextension.CallMethodBindPtrCall(limitAngularVelocityModifier3DMethodGetRootBone(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetEndBoneName mirrors the Godot LimitAngularVelocityModifier3D.set_end_bone_name method.
func (self *LimitAngularVelocityModifier3D) SetEndBoneName(index int64, bone_name string) {
	tmp_bone_name := variant.NewStringFromString(bone_name)
	defer tmp_bone_name.Destroy()

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&index)),
		gdextension.TypePtr(unsafe.Pointer(&tmp_bone_name)),
	}
	gdextension.CallMethodBindPtrCall(limitAngularVelocityModifier3DMethodSetEndBoneName(), self.Ptr(), args[:], nil)
}

// GetEndBoneName mirrors the Godot LimitAngularVelocityModifier3D.get_end_bone_name method.
func (self *LimitAngularVelocityModifier3D) GetEndBoneName(index int64) string {
	var raw variant.String
	defer raw.Destroy()
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&index)),
	}
	gdextension.CallMethodBindPtrCall(limitAngularVelocityModifier3DMethodGetEndBoneName(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&raw)))
	return variant.StringToGo(&raw)
}

// SetEndBone mirrors the Godot LimitAngularVelocityModifier3D.set_end_bone method.
func (self *LimitAngularVelocityModifier3D) SetEndBone(index int64, bone int64) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&index)),
		gdextension.TypePtr(unsafe.Pointer(&bone)),
	}
	gdextension.CallMethodBindPtrCall(limitAngularVelocityModifier3DMethodSetEndBone(), self.Ptr(), args[:], nil)
}

// GetEndBone mirrors the Godot LimitAngularVelocityModifier3D.get_end_bone method.
func (self *LimitAngularVelocityModifier3D) GetEndBone(index int64) int64 {
	var ret int64
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&index)),
	}
	gdextension.CallMethodBindPtrCall(limitAngularVelocityModifier3DMethodGetEndBone(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetChainCount mirrors the Godot LimitAngularVelocityModifier3D.set_chain_count method.
func (self *LimitAngularVelocityModifier3D) SetChainCount(count int64) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&count)),
	}
	gdextension.CallMethodBindPtrCall(limitAngularVelocityModifier3DMethodSetChainCount(), self.Ptr(), args[:], nil)
}

// GetChainCount mirrors the Godot LimitAngularVelocityModifier3D.get_chain_count method.
func (self *LimitAngularVelocityModifier3D) GetChainCount() int64 {
	var ret int64
	gdextension.CallMethodBindPtrCall(limitAngularVelocityModifier3DMethodGetChainCount(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// ClearChains mirrors the Godot LimitAngularVelocityModifier3D.clear_chains method.
func (self *LimitAngularVelocityModifier3D) ClearChains() {
	gdextension.CallMethodBindPtrCall(limitAngularVelocityModifier3DMethodClearChains(), self.Ptr(), nil, nil)
}

// SetMaxAngularVelocity mirrors the Godot LimitAngularVelocityModifier3D.set_max_angular_velocity method.
func (self *LimitAngularVelocityModifier3D) SetMaxAngularVelocity(angular_velocity float32) {
	tmp_angular_velocity := float64(angular_velocity)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_angular_velocity)),
	}
	gdextension.CallMethodBindPtrCall(limitAngularVelocityModifier3DMethodSetMaxAngularVelocity(), self.Ptr(), args[:], nil)
}

// GetMaxAngularVelocity mirrors the Godot LimitAngularVelocityModifier3D.get_max_angular_velocity method.
func (self *LimitAngularVelocityModifier3D) GetMaxAngularVelocity() float32 {
	var raw float64
	gdextension.CallMethodBindPtrCall(limitAngularVelocityModifier3DMethodGetMaxAngularVelocity(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}

// SetExclude mirrors the Godot LimitAngularVelocityModifier3D.set_exclude method.
func (self *LimitAngularVelocityModifier3D) SetExclude(exclude bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&exclude)),
	}
	gdextension.CallMethodBindPtrCall(limitAngularVelocityModifier3DMethodSetExclude(), self.Ptr(), args[:], nil)
}

// IsExclude mirrors the Godot LimitAngularVelocityModifier3D.is_exclude method.
func (self *LimitAngularVelocityModifier3D) IsExclude() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(limitAngularVelocityModifier3DMethodIsExclude(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// Reset mirrors the Godot LimitAngularVelocityModifier3D.reset method.
func (self *LimitAngularVelocityModifier3D) Reset() {
	gdextension.CallMethodBindPtrCall(limitAngularVelocityModifier3DMethodReset(), self.Ptr(), nil, nil)
}
