// Code generated by godot-go-bindgen. DO NOT EDIT.

package core

import (
	"runtime"

	"github.com/legendary-code/godot-go/gdextension"
)

// Logger mirrors the Godot engine class Logger.
type Logger struct {
	RefCounted
}

// LoggerFromPtr wraps an existing host-allocated GDExtensionObjectPtr in a
// *Logger. Returns nil on a nil input. Logger descends from RefCounted, so the
// returned wrapper carries a Go finalizer that drops one engine
// reference (via Unreference, dispatched on the main thread) when
// Go's GC determines the wrapper is unreachable. Users who want
// deterministic free can call ret.Unreference() directly — the
// finalizer is harmless after the refcount hits zero.
func LoggerFromPtr(p gdextension.ObjectPtr) *Logger {
	if p == nil {
		return nil
	}
	ret := &Logger{}
	ret.BindPtr(p)
	runtime.SetFinalizer(ret, func(r *Logger) {
		gdextension.RunOnMain(func() { r.Unreference() })
	})
	return ret
}

// LoggerErrorType is the Godot LoggerErrorType enum.
type LoggerErrorType int64

const (
	Logger_ERROR_TYPE_ERROR   LoggerErrorType = 0
	Logger_ERROR_TYPE_WARNING LoggerErrorType = 1
	Logger_ERROR_TYPE_SCRIPT  LoggerErrorType = 2
	Logger_ERROR_TYPE_SHADER  LoggerErrorType = 3
)
