// Code generated by godot-go-bindgen. DO NOT EDIT.

package core

import (
	"sync"
	"unsafe"

	"github.com/legendary-code/godot-go/gdextension"
)

// MenuButton mirrors the Godot engine class MenuButton.
type MenuButton struct {
	Button
}

// MenuButtonFromPtr wraps an existing host-allocated GDExtensionObjectPtr in a
// *MenuButton. Returns nil on a nil input.
func MenuButtonFromPtr(p gdextension.ObjectPtr) *MenuButton {
	if p == nil {
		return nil
	}
	ret := &MenuButton{}
	ret.BindPtr(p)
	return ret
}

var (
	menuButtonMethodGetPopup = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("MenuButton"),
			gdextension.InternStringName("get_popup"),
			229722558,
		)
	})
	menuButtonMethodShowPopup = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("MenuButton"),
			gdextension.InternStringName("show_popup"),
			3218959716,
		)
	})
	menuButtonMethodSetSwitchOnHover = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("MenuButton"),
			gdextension.InternStringName("set_switch_on_hover"),
			2586408642,
		)
	})
	menuButtonMethodIsSwitchOnHover = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("MenuButton"),
			gdextension.InternStringName("is_switch_on_hover"),
			2240911060,
		)
	})
	menuButtonMethodSetDisableShortcuts = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("MenuButton"),
			gdextension.InternStringName("set_disable_shortcuts"),
			2586408642,
		)
	})
	menuButtonMethodSetItemCount = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("MenuButton"),
			gdextension.InternStringName("set_item_count"),
			1286410249,
		)
	})
	menuButtonMethodGetItemCount = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("MenuButton"),
			gdextension.InternStringName("get_item_count"),
			3905245786,
		)
	})
)

// GetPopup mirrors the Godot MenuButton.get_popup method.
func (self *MenuButton) GetPopup() *PopupMenu {
	var ret gdextension.ObjectPtr
	gdextension.CallMethodBindPtrCall(menuButtonMethodGetPopup(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return PopupMenuFromPtr(ret)
}

// ShowPopup mirrors the Godot MenuButton.show_popup method.
func (self *MenuButton) ShowPopup() {
	gdextension.CallMethodBindPtrCall(menuButtonMethodShowPopup(), self.Ptr(), nil, nil)
}

// SetSwitchOnHover mirrors the Godot MenuButton.set_switch_on_hover method.
func (self *MenuButton) SetSwitchOnHover(enable bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&enable)),
	}
	gdextension.CallMethodBindPtrCall(menuButtonMethodSetSwitchOnHover(), self.Ptr(), args[:], nil)
}

// IsSwitchOnHover mirrors the Godot MenuButton.is_switch_on_hover method.
func (self *MenuButton) IsSwitchOnHover() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(menuButtonMethodIsSwitchOnHover(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetDisableShortcuts mirrors the Godot MenuButton.set_disable_shortcuts method.
func (self *MenuButton) SetDisableShortcuts(disabled bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&disabled)),
	}
	gdextension.CallMethodBindPtrCall(menuButtonMethodSetDisableShortcuts(), self.Ptr(), args[:], nil)
}

// SetItemCount mirrors the Godot MenuButton.set_item_count method.
func (self *MenuButton) SetItemCount(count int64) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&count)),
	}
	gdextension.CallMethodBindPtrCall(menuButtonMethodSetItemCount(), self.Ptr(), args[:], nil)
}

// GetItemCount mirrors the Godot MenuButton.get_item_count method.
func (self *MenuButton) GetItemCount() int64 {
	var ret int64
	gdextension.CallMethodBindPtrCall(menuButtonMethodGetItemCount(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}
