// Code generated by godot-go-bindgen. DO NOT EDIT.

package core

import (
	"sync"
	"unsafe"

	"github.com/legendary-code/godot-go/gdextension"
	"github.com/legendary-code/godot-go/variant"
)

// MultiplayerSynchronizer mirrors the Godot engine class MultiplayerSynchronizer.
type MultiplayerSynchronizer struct {
	Node
}

// MultiplayerSynchronizerFromPtr wraps an existing host-allocated GDExtensionObjectPtr in a
// *MultiplayerSynchronizer. Returns nil on a nil input.
func MultiplayerSynchronizerFromPtr(p gdextension.ObjectPtr) *MultiplayerSynchronizer {
	if p == nil {
		return nil
	}
	ret := &MultiplayerSynchronizer{}
	ret.BindPtr(p)
	return ret
}

// MultiplayerSynchronizerVisibilityUpdateMode is the Godot MultiplayerSynchronizerVisibilityUpdateMode enum.
type MultiplayerSynchronizerVisibilityUpdateMode int64

const (
	MultiplayerSynchronizer_VISIBILITY_PROCESS_IDLE    MultiplayerSynchronizerVisibilityUpdateMode = 0
	MultiplayerSynchronizer_VISIBILITY_PROCESS_PHYSICS MultiplayerSynchronizerVisibilityUpdateMode = 1
	MultiplayerSynchronizer_VISIBILITY_PROCESS_NONE    MultiplayerSynchronizerVisibilityUpdateMode = 2
)

var (
	multiplayerSynchronizerMethodSetRootPath = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("MultiplayerSynchronizer"),
			gdextension.InternStringName("set_root_path"),
			1348162250,
		)
	})
	multiplayerSynchronizerMethodGetRootPath = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("MultiplayerSynchronizer"),
			gdextension.InternStringName("get_root_path"),
			4075236667,
		)
	})
	multiplayerSynchronizerMethodSetReplicationInterval = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("MultiplayerSynchronizer"),
			gdextension.InternStringName("set_replication_interval"),
			373806689,
		)
	})
	multiplayerSynchronizerMethodGetReplicationInterval = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("MultiplayerSynchronizer"),
			gdextension.InternStringName("get_replication_interval"),
			1740695150,
		)
	})
	multiplayerSynchronizerMethodSetDeltaInterval = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("MultiplayerSynchronizer"),
			gdextension.InternStringName("set_delta_interval"),
			373806689,
		)
	})
	multiplayerSynchronizerMethodGetDeltaInterval = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("MultiplayerSynchronizer"),
			gdextension.InternStringName("get_delta_interval"),
			1740695150,
		)
	})
	multiplayerSynchronizerMethodSetReplicationConfig = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("MultiplayerSynchronizer"),
			gdextension.InternStringName("set_replication_config"),
			3889206742,
		)
	})
	multiplayerSynchronizerMethodGetReplicationConfig = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("MultiplayerSynchronizer"),
			gdextension.InternStringName("get_replication_config"),
			3200254614,
		)
	})
	multiplayerSynchronizerMethodSetVisibilityUpdateMode = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("MultiplayerSynchronizer"),
			gdextension.InternStringName("set_visibility_update_mode"),
			3494860300,
		)
	})
	multiplayerSynchronizerMethodGetVisibilityUpdateMode = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("MultiplayerSynchronizer"),
			gdextension.InternStringName("get_visibility_update_mode"),
			3352241418,
		)
	})
	multiplayerSynchronizerMethodUpdateVisibility = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("MultiplayerSynchronizer"),
			gdextension.InternStringName("update_visibility"),
			1995695955,
		)
	})
	multiplayerSynchronizerMethodSetVisibilityPublic = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("MultiplayerSynchronizer"),
			gdextension.InternStringName("set_visibility_public"),
			2586408642,
		)
	})
	multiplayerSynchronizerMethodIsVisibilityPublic = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("MultiplayerSynchronizer"),
			gdextension.InternStringName("is_visibility_public"),
			36873697,
		)
	})
	multiplayerSynchronizerMethodAddVisibilityFilter = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("MultiplayerSynchronizer"),
			gdextension.InternStringName("add_visibility_filter"),
			1611583062,
		)
	})
	multiplayerSynchronizerMethodRemoveVisibilityFilter = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("MultiplayerSynchronizer"),
			gdextension.InternStringName("remove_visibility_filter"),
			1611583062,
		)
	})
	multiplayerSynchronizerMethodSetVisibilityFor = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("MultiplayerSynchronizer"),
			gdextension.InternStringName("set_visibility_for"),
			300928843,
		)
	})
	multiplayerSynchronizerMethodGetVisibilityFor = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("MultiplayerSynchronizer"),
			gdextension.InternStringName("get_visibility_for"),
			1116898809,
		)
	})
)

// SetRootPath mirrors the Godot MultiplayerSynchronizer.set_root_path method.
func (self *MultiplayerSynchronizer) SetRootPath(path string) {
	tmp_path := variant.NewNodePathFromString(path)
	defer tmp_path.Destroy()

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_path)),
	}
	gdextension.CallMethodBindPtrCall(multiplayerSynchronizerMethodSetRootPath(), self.Ptr(), args[:], nil)
}

// GetRootPath mirrors the Godot MultiplayerSynchronizer.get_root_path method.
func (self *MultiplayerSynchronizer) GetRootPath() string {
	var raw variant.NodePath
	defer raw.Destroy()
	gdextension.CallMethodBindPtrCall(multiplayerSynchronizerMethodGetRootPath(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return variant.NodePathToGo(&raw)
}

// SetReplicationInterval mirrors the Godot MultiplayerSynchronizer.set_replication_interval method.
func (self *MultiplayerSynchronizer) SetReplicationInterval(milliseconds float32) {
	tmp_milliseconds := float64(milliseconds)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_milliseconds)),
	}
	gdextension.CallMethodBindPtrCall(multiplayerSynchronizerMethodSetReplicationInterval(), self.Ptr(), args[:], nil)
}

// GetReplicationInterval mirrors the Godot MultiplayerSynchronizer.get_replication_interval method.
func (self *MultiplayerSynchronizer) GetReplicationInterval() float32 {
	var raw float64
	gdextension.CallMethodBindPtrCall(multiplayerSynchronizerMethodGetReplicationInterval(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}

// SetDeltaInterval mirrors the Godot MultiplayerSynchronizer.set_delta_interval method.
func (self *MultiplayerSynchronizer) SetDeltaInterval(milliseconds float32) {
	tmp_milliseconds := float64(milliseconds)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_milliseconds)),
	}
	gdextension.CallMethodBindPtrCall(multiplayerSynchronizerMethodSetDeltaInterval(), self.Ptr(), args[:], nil)
}

// GetDeltaInterval mirrors the Godot MultiplayerSynchronizer.get_delta_interval method.
func (self *MultiplayerSynchronizer) GetDeltaInterval() float32 {
	var raw float64
	gdextension.CallMethodBindPtrCall(multiplayerSynchronizerMethodGetDeltaInterval(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}

// SetReplicationConfig mirrors the Godot MultiplayerSynchronizer.set_replication_config method.
func (self *MultiplayerSynchronizer) SetReplicationConfig(config *SceneReplicationConfig) {
	var tmp_config gdextension.ObjectPtr
	if config != nil {
		tmp_config = config.Ptr()
	}

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_config)),
	}
	gdextension.CallMethodBindPtrCall(multiplayerSynchronizerMethodSetReplicationConfig(), self.Ptr(), args[:], nil)
}

// GetReplicationConfig mirrors the Godot MultiplayerSynchronizer.get_replication_config method.
func (self *MultiplayerSynchronizer) GetReplicationConfig() *SceneReplicationConfig {
	var ret gdextension.ObjectPtr
	gdextension.CallMethodBindPtrCall(multiplayerSynchronizerMethodGetReplicationConfig(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return SceneReplicationConfigFromPtr(ret)
}

// SetVisibilityUpdateMode mirrors the Godot MultiplayerSynchronizer.set_visibility_update_mode method.
func (self *MultiplayerSynchronizer) SetVisibilityUpdateMode(mode MultiplayerSynchronizerVisibilityUpdateMode) {
	tmp_mode := int64(mode)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_mode)),
	}
	gdextension.CallMethodBindPtrCall(multiplayerSynchronizerMethodSetVisibilityUpdateMode(), self.Ptr(), args[:], nil)
}

// GetVisibilityUpdateMode mirrors the Godot MultiplayerSynchronizer.get_visibility_update_mode method.
func (self *MultiplayerSynchronizer) GetVisibilityUpdateMode() MultiplayerSynchronizerVisibilityUpdateMode {
	var ret int64
	gdextension.CallMethodBindPtrCall(multiplayerSynchronizerMethodGetVisibilityUpdateMode(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return MultiplayerSynchronizerVisibilityUpdateMode(ret)
}

// UpdateVisibility mirrors the Godot MultiplayerSynchronizer.update_visibility method.
func (self *MultiplayerSynchronizer) UpdateVisibility(for_peer int64) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&for_peer)),
	}
	gdextension.CallMethodBindPtrCall(multiplayerSynchronizerMethodUpdateVisibility(), self.Ptr(), args[:], nil)
}

// SetVisibilityPublic mirrors the Godot MultiplayerSynchronizer.set_visibility_public method.
func (self *MultiplayerSynchronizer) SetVisibilityPublic(visible bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&visible)),
	}
	gdextension.CallMethodBindPtrCall(multiplayerSynchronizerMethodSetVisibilityPublic(), self.Ptr(), args[:], nil)
}

// IsVisibilityPublic mirrors the Godot MultiplayerSynchronizer.is_visibility_public method.
func (self *MultiplayerSynchronizer) IsVisibilityPublic() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(multiplayerSynchronizerMethodIsVisibilityPublic(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// AddVisibilityFilter mirrors the Godot MultiplayerSynchronizer.add_visibility_filter method.
func (self *MultiplayerSynchronizer) AddVisibilityFilter(filter variant.Callable) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&filter)),
	}
	gdextension.CallMethodBindPtrCall(multiplayerSynchronizerMethodAddVisibilityFilter(), self.Ptr(), args[:], nil)
}

// RemoveVisibilityFilter mirrors the Godot MultiplayerSynchronizer.remove_visibility_filter method.
func (self *MultiplayerSynchronizer) RemoveVisibilityFilter(filter variant.Callable) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&filter)),
	}
	gdextension.CallMethodBindPtrCall(multiplayerSynchronizerMethodRemoveVisibilityFilter(), self.Ptr(), args[:], nil)
}

// SetVisibilityFor mirrors the Godot MultiplayerSynchronizer.set_visibility_for method.
func (self *MultiplayerSynchronizer) SetVisibilityFor(peer int64, visible bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&peer)),
		gdextension.TypePtr(unsafe.Pointer(&visible)),
	}
	gdextension.CallMethodBindPtrCall(multiplayerSynchronizerMethodSetVisibilityFor(), self.Ptr(), args[:], nil)
}

// GetVisibilityFor mirrors the Godot MultiplayerSynchronizer.get_visibility_for method.
func (self *MultiplayerSynchronizer) GetVisibilityFor(peer int64) bool {
	var ret bool
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&peer)),
	}
	gdextension.CallMethodBindPtrCall(multiplayerSynchronizerMethodGetVisibilityFor(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}
