// Code generated by godot-go-bindgen. DO NOT EDIT.

package core

import (
	"runtime"
	"sync"
	"unsafe"

	"github.com/legendary-code/godot-go/gdextension"
	"github.com/legendary-code/godot-go/variant"
)

// OpenXRSpatialContextPersistenceConfig mirrors the Godot engine class OpenXRSpatialContextPersistenceConfig.
type OpenXRSpatialContextPersistenceConfig struct {
	OpenXRStructureBase
}

// OpenXRSpatialContextPersistenceConfigFromPtr wraps an existing host-allocated GDExtensionObjectPtr in a
// *OpenXRSpatialContextPersistenceConfig. Returns nil on a nil input. OpenXRSpatialContextPersistenceConfig descends from RefCounted, so the
// returned wrapper carries a Go finalizer that drops one engine
// reference (via Unreference, dispatched on the main thread) when
// Go's GC determines the wrapper is unreachable. Users who want
// deterministic free can call ret.Unreference() directly — the
// finalizer is harmless after the refcount hits zero.
func OpenXRSpatialContextPersistenceConfigFromPtr(p gdextension.ObjectPtr) *OpenXRSpatialContextPersistenceConfig {
	if p == nil {
		return nil
	}
	ret := &OpenXRSpatialContextPersistenceConfig{}
	ret.BindPtr(p)
	runtime.SetFinalizer(ret, func(r *OpenXRSpatialContextPersistenceConfig) {
		gdextension.RunOnMain(func() { r.Unreference() })
	})
	return ret
}

var (
	openXRSpatialContextPersistenceConfigMethodAddPersistenceContext = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("OpenXRSpatialContextPersistenceConfig"),
			gdextension.InternStringName("add_persistence_context"),
			2722037293,
		)
	})
	openXRSpatialContextPersistenceConfigMethodRemovePersistenceContext = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("OpenXRSpatialContextPersistenceConfig"),
			gdextension.InternStringName("remove_persistence_context"),
			2722037293,
		)
	})
)

// AddPersistenceContext mirrors the Godot OpenXRSpatialContextPersistenceConfig.add_persistence_context method.
func (self *OpenXRSpatialContextPersistenceConfig) AddPersistenceContext(persistence_context variant.RID) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&persistence_context)),
	}
	gdextension.CallMethodBindPtrCall(openXRSpatialContextPersistenceConfigMethodAddPersistenceContext(), self.Ptr(), args[:], nil)
}

// RemovePersistenceContext mirrors the Godot OpenXRSpatialContextPersistenceConfig.remove_persistence_context method.
func (self *OpenXRSpatialContextPersistenceConfig) RemovePersistenceContext(persistence_context variant.RID) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&persistence_context)),
	}
	gdextension.CallMethodBindPtrCall(openXRSpatialContextPersistenceConfigMethodRemovePersistenceContext(), self.Ptr(), args[:], nil)
}
