// Code generated by godot-go-bindgen. DO NOT EDIT.

package core

import (
	"sync"
	"unsafe"

	"github.com/legendary-code/godot-go/internal/gdextension"
)

// OpenXRStructureBase mirrors the Godot engine class OpenXRStructureBase.
type OpenXRStructureBase struct {
	RefCounted
}

// OpenXRStructureBaseFromPtr wraps an existing host-allocated GDExtensionObjectPtr in a
// *OpenXRStructureBase. Returns nil on a nil input.
func OpenXRStructureBaseFromPtr(p gdextension.ObjectPtr) *OpenXRStructureBase {
	if p == nil {
		return nil
	}
	ret := &OpenXRStructureBase{}
	ret.BindPtr(p)
	return ret
}

var (
	openXRStructureBaseMethodGetStructureType = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("OpenXRStructureBase"),
			gdextension.InternStringName("get_structure_type"),
			2455072627,
		)
	})
	openXRStructureBaseMethodSetNext = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("OpenXRStructureBase"),
			gdextension.InternStringName("set_next"),
			334698771,
		)
	})
	openXRStructureBaseMethodGetNext = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("OpenXRStructureBase"),
			gdextension.InternStringName("get_next"),
			2798796760,
		)
	})
)

// GetStructureType mirrors the Godot OpenXRStructureBase.get_structure_type method.
func (self *OpenXRStructureBase) GetStructureType() int64 {
	var ret int64
	gdextension.CallMethodBindPtrCall(openXRStructureBaseMethodGetStructureType(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetNext mirrors the Godot OpenXRStructureBase.set_next method.
func (self *OpenXRStructureBase) SetNext(entity *OpenXRStructureBase) {
	var tmp_entity gdextension.ObjectPtr
	if entity != nil {
		tmp_entity = entity.Ptr()
	}

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_entity)),
	}
	gdextension.CallMethodBindPtrCall(openXRStructureBaseMethodSetNext(), self.Ptr(), args[:], nil)
}

// GetNext mirrors the Godot OpenXRStructureBase.get_next method.
func (self *OpenXRStructureBase) GetNext() *OpenXRStructureBase {
	var ret gdextension.ObjectPtr
	gdextension.CallMethodBindPtrCall(openXRStructureBaseMethodGetNext(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return OpenXRStructureBaseFromPtr(ret)
}
