// Code generated by godot-go-bindgen. DO NOT EDIT.

package core

import (
	"runtime"
	"sync"
	"unsafe"

	"github.com/legendary-code/godot-go/internal/gdextension"
	"github.com/legendary-code/godot-go/variant"
)

// OpenXRSpatialComponentBounded3DList mirrors the Godot engine class OpenXRSpatialComponentBounded3DList.
type OpenXRSpatialComponentBounded3DList struct {
	OpenXRSpatialComponentData
}

// OpenXRSpatialComponentBounded3DListFromPtr wraps an existing host-allocated GDExtensionObjectPtr in a
// *OpenXRSpatialComponentBounded3DList. Returns nil on a nil input. OpenXRSpatialComponentBounded3DList descends from RefCounted, so the
// returned wrapper carries a Go finalizer that drops one engine
// reference (via Unreference, dispatched on the main thread) when
// Go's GC determines the wrapper is unreachable. Users who want
// deterministic free can call ret.Unreference() directly — the
// finalizer is harmless after the refcount hits zero.
func OpenXRSpatialComponentBounded3DListFromPtr(p gdextension.ObjectPtr) *OpenXRSpatialComponentBounded3DList {
	if p == nil {
		return nil
	}
	ret := &OpenXRSpatialComponentBounded3DList{}
	ret.BindPtr(p)
	runtime.SetFinalizer(ret, func(r *OpenXRSpatialComponentBounded3DList) {
		gdextension.RunOnMain(func() { r.Unreference() })
	})
	return ret
}

var (
	openXRSpatialComponentBounded3DListMethodGetCenterPose = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("OpenXRSpatialComponentBounded3DList"),
			gdextension.InternStringName("get_center_pose"),
			1965739696,
		)
	})
	openXRSpatialComponentBounded3DListMethodGetSize = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("OpenXRSpatialComponentBounded3DList"),
			gdextension.InternStringName("get_size"),
			711720468,
		)
	})
)

// GetCenterPose mirrors the Godot OpenXRSpatialComponentBounded3DList.get_center_pose method.
func (self *OpenXRSpatialComponentBounded3DList) GetCenterPose(index int64) variant.Transform3D {
	var ret variant.Transform3D
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&index)),
	}
	gdextension.CallMethodBindPtrCall(openXRSpatialComponentBounded3DListMethodGetCenterPose(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// GetSize mirrors the Godot OpenXRSpatialComponentBounded3DList.get_size method.
func (self *OpenXRSpatialComponentBounded3DList) GetSize(index int64) variant.Vector3 {
	var ret variant.Vector3
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&index)),
	}
	gdextension.CallMethodBindPtrCall(openXRSpatialComponentBounded3DListMethodGetSize(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}
