// Code generated by godot-go-bindgen. DO NOT EDIT.

package core

import (
	"sync"
	"unsafe"

	"github.com/legendary-code/godot-go/gdextension"
	"github.com/legendary-code/godot-go/variant"
)

// OpenXRRenderModel mirrors the Godot engine class OpenXRRenderModel.
type OpenXRRenderModel struct {
	Node3D
}

// OpenXRRenderModelFromPtr wraps an existing host-allocated GDExtensionObjectPtr in a
// *OpenXRRenderModel. Returns nil on a nil input.
func OpenXRRenderModelFromPtr(p gdextension.ObjectPtr) *OpenXRRenderModel {
	if p == nil {
		return nil
	}
	ret := &OpenXRRenderModel{}
	ret.BindPtr(p)
	return ret
}

var (
	openXRRenderModelMethodGetTopLevelPath = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("OpenXRRenderModel"),
			gdextension.InternStringName("get_top_level_path"),
			201670096,
		)
	})
	openXRRenderModelMethodGetRenderModel = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("OpenXRRenderModel"),
			gdextension.InternStringName("get_render_model"),
			2944877500,
		)
	})
	openXRRenderModelMethodSetRenderModel = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("OpenXRRenderModel"),
			gdextension.InternStringName("set_render_model"),
			2722037293,
		)
	})
)

// GetTopLevelPath mirrors the Godot OpenXRRenderModel.get_top_level_path method.
func (self *OpenXRRenderModel) GetTopLevelPath() string {
	var raw variant.String
	defer raw.Destroy()
	gdextension.CallMethodBindPtrCall(openXRRenderModelMethodGetTopLevelPath(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return variant.StringToGo(&raw)
}

// GetRenderModel mirrors the Godot OpenXRRenderModel.get_render_model method.
func (self *OpenXRRenderModel) GetRenderModel() variant.RID {
	var ret variant.RID
	gdextension.CallMethodBindPtrCall(openXRRenderModelMethodGetRenderModel(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetRenderModel mirrors the Godot OpenXRRenderModel.set_render_model method.
func (self *OpenXRRenderModel) SetRenderModel(render_model variant.RID) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&render_model)),
	}
	gdextension.CallMethodBindPtrCall(openXRRenderModelMethodSetRenderModel(), self.Ptr(), args[:], nil)
}
