// Code generated by godot-go-bindgen. DO NOT EDIT.

package core

import (
	"runtime"

	"github.com/legendary-code/godot-go/gdextension"
)

// PacketPeerExtension mirrors the Godot engine class PacketPeerExtension.
type PacketPeerExtension struct {
	PacketPeer
}

// PacketPeerExtensionFromPtr wraps an existing host-allocated GDExtensionObjectPtr in a
// *PacketPeerExtension. Returns nil on a nil input. PacketPeerExtension descends from RefCounted, so the
// returned wrapper carries a Go finalizer that drops one engine
// reference (via Unreference, dispatched on the main thread) when
// Go's GC determines the wrapper is unreachable. Users who want
// deterministic free can call ret.Unreference() directly — the
// finalizer is harmless after the refcount hits zero.
func PacketPeerExtensionFromPtr(p gdextension.ObjectPtr) *PacketPeerExtension {
	if p == nil {
		return nil
	}
	ret := &PacketPeerExtension{}
	ret.BindPtr(p)
	runtime.SetFinalizer(ret, func(r *PacketPeerExtension) {
		gdextension.RunOnMain(func() { r.Unreference() })
	})
	return ret
}
