// Code generated by godot-go-bindgen. DO NOT EDIT.

package core

import (
	"sync"
	"unsafe"

	"github.com/legendary-code/godot-go/internal/gdextension"
	"github.com/legendary-code/godot-go/variant"
)

// PhysicsShapeQueryParameters3D mirrors the Godot engine class PhysicsShapeQueryParameters3D.
type PhysicsShapeQueryParameters3D struct {
	RefCounted
}

// PhysicsShapeQueryParameters3DFromPtr wraps an existing host-allocated GDExtensionObjectPtr in a
// *PhysicsShapeQueryParameters3D. Returns nil on a nil input.
func PhysicsShapeQueryParameters3DFromPtr(p gdextension.ObjectPtr) *PhysicsShapeQueryParameters3D {
	if p == nil {
		return nil
	}
	ret := &PhysicsShapeQueryParameters3D{}
	ret.BindPtr(p)
	return ret
}

var (
	physicsShapeQueryParameters3DMethodSetShape = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("PhysicsShapeQueryParameters3D"),
			gdextension.InternStringName("set_shape"),
			968641751,
		)
	})
	physicsShapeQueryParameters3DMethodGetShape = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("PhysicsShapeQueryParameters3D"),
			gdextension.InternStringName("get_shape"),
			121922552,
		)
	})
	physicsShapeQueryParameters3DMethodSetShapeRid = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("PhysicsShapeQueryParameters3D"),
			gdextension.InternStringName("set_shape_rid"),
			2722037293,
		)
	})
	physicsShapeQueryParameters3DMethodGetShapeRid = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("PhysicsShapeQueryParameters3D"),
			gdextension.InternStringName("get_shape_rid"),
			2944877500,
		)
	})
	physicsShapeQueryParameters3DMethodSetTransform = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("PhysicsShapeQueryParameters3D"),
			gdextension.InternStringName("set_transform"),
			2952846383,
		)
	})
	physicsShapeQueryParameters3DMethodGetTransform = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("PhysicsShapeQueryParameters3D"),
			gdextension.InternStringName("get_transform"),
			3229777777,
		)
	})
	physicsShapeQueryParameters3DMethodSetMotion = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("PhysicsShapeQueryParameters3D"),
			gdextension.InternStringName("set_motion"),
			3460891852,
		)
	})
	physicsShapeQueryParameters3DMethodGetMotion = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("PhysicsShapeQueryParameters3D"),
			gdextension.InternStringName("get_motion"),
			3360562783,
		)
	})
	physicsShapeQueryParameters3DMethodSetMargin = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("PhysicsShapeQueryParameters3D"),
			gdextension.InternStringName("set_margin"),
			373806689,
		)
	})
	physicsShapeQueryParameters3DMethodGetMargin = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("PhysicsShapeQueryParameters3D"),
			gdextension.InternStringName("get_margin"),
			1740695150,
		)
	})
	physicsShapeQueryParameters3DMethodSetCollisionMask = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("PhysicsShapeQueryParameters3D"),
			gdextension.InternStringName("set_collision_mask"),
			1286410249,
		)
	})
	physicsShapeQueryParameters3DMethodGetCollisionMask = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("PhysicsShapeQueryParameters3D"),
			gdextension.InternStringName("get_collision_mask"),
			3905245786,
		)
	})
	physicsShapeQueryParameters3DMethodSetExclude = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("PhysicsShapeQueryParameters3D"),
			gdextension.InternStringName("set_exclude"),
			381264803,
		)
	})
	physicsShapeQueryParameters3DMethodGetExclude = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("PhysicsShapeQueryParameters3D"),
			gdextension.InternStringName("get_exclude"),
			3995934104,
		)
	})
	physicsShapeQueryParameters3DMethodSetCollideWithBodies = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("PhysicsShapeQueryParameters3D"),
			gdextension.InternStringName("set_collide_with_bodies"),
			2586408642,
		)
	})
	physicsShapeQueryParameters3DMethodIsCollideWithBodiesEnabled = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("PhysicsShapeQueryParameters3D"),
			gdextension.InternStringName("is_collide_with_bodies_enabled"),
			36873697,
		)
	})
	physicsShapeQueryParameters3DMethodSetCollideWithAreas = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("PhysicsShapeQueryParameters3D"),
			gdextension.InternStringName("set_collide_with_areas"),
			2586408642,
		)
	})
	physicsShapeQueryParameters3DMethodIsCollideWithAreasEnabled = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("PhysicsShapeQueryParameters3D"),
			gdextension.InternStringName("is_collide_with_areas_enabled"),
			36873697,
		)
	})
)

// SetShape mirrors the Godot PhysicsShapeQueryParameters3D.set_shape method.
func (self *PhysicsShapeQueryParameters3D) SetShape(shape *Resource) {
	var tmp_shape gdextension.ObjectPtr
	if shape != nil {
		tmp_shape = shape.Ptr()
	}

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_shape)),
	}
	gdextension.CallMethodBindPtrCall(physicsShapeQueryParameters3DMethodSetShape(), self.Ptr(), args[:], nil)
}

// GetShape mirrors the Godot PhysicsShapeQueryParameters3D.get_shape method.
func (self *PhysicsShapeQueryParameters3D) GetShape() *Resource {
	var ret gdextension.ObjectPtr
	gdextension.CallMethodBindPtrCall(physicsShapeQueryParameters3DMethodGetShape(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ResourceFromPtr(ret)
}

// SetShapeRid mirrors the Godot PhysicsShapeQueryParameters3D.set_shape_rid method.
func (self *PhysicsShapeQueryParameters3D) SetShapeRid(shape variant.RID) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&shape)),
	}
	gdextension.CallMethodBindPtrCall(physicsShapeQueryParameters3DMethodSetShapeRid(), self.Ptr(), args[:], nil)
}

// GetShapeRid mirrors the Godot PhysicsShapeQueryParameters3D.get_shape_rid method.
func (self *PhysicsShapeQueryParameters3D) GetShapeRid() variant.RID {
	var ret variant.RID
	gdextension.CallMethodBindPtrCall(physicsShapeQueryParameters3DMethodGetShapeRid(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetTransform mirrors the Godot PhysicsShapeQueryParameters3D.set_transform method.
func (self *PhysicsShapeQueryParameters3D) SetTransform(transform variant.Transform3D) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&transform)),
	}
	gdextension.CallMethodBindPtrCall(physicsShapeQueryParameters3DMethodSetTransform(), self.Ptr(), args[:], nil)
}

// GetTransform mirrors the Godot PhysicsShapeQueryParameters3D.get_transform method.
func (self *PhysicsShapeQueryParameters3D) GetTransform() variant.Transform3D {
	var ret variant.Transform3D
	gdextension.CallMethodBindPtrCall(physicsShapeQueryParameters3DMethodGetTransform(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetMotion mirrors the Godot PhysicsShapeQueryParameters3D.set_motion method.
func (self *PhysicsShapeQueryParameters3D) SetMotion(motion variant.Vector3) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&motion)),
	}
	gdextension.CallMethodBindPtrCall(physicsShapeQueryParameters3DMethodSetMotion(), self.Ptr(), args[:], nil)
}

// GetMotion mirrors the Godot PhysicsShapeQueryParameters3D.get_motion method.
func (self *PhysicsShapeQueryParameters3D) GetMotion() variant.Vector3 {
	var ret variant.Vector3
	gdextension.CallMethodBindPtrCall(physicsShapeQueryParameters3DMethodGetMotion(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetMargin mirrors the Godot PhysicsShapeQueryParameters3D.set_margin method.
func (self *PhysicsShapeQueryParameters3D) SetMargin(margin float32) {
	tmp_margin := float64(margin)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_margin)),
	}
	gdextension.CallMethodBindPtrCall(physicsShapeQueryParameters3DMethodSetMargin(), self.Ptr(), args[:], nil)
}

// GetMargin mirrors the Godot PhysicsShapeQueryParameters3D.get_margin method.
func (self *PhysicsShapeQueryParameters3D) GetMargin() float32 {
	var raw float64
	gdextension.CallMethodBindPtrCall(physicsShapeQueryParameters3DMethodGetMargin(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}

// SetCollisionMask mirrors the Godot PhysicsShapeQueryParameters3D.set_collision_mask method.
func (self *PhysicsShapeQueryParameters3D) SetCollisionMask(collision_mask int64) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&collision_mask)),
	}
	gdextension.CallMethodBindPtrCall(physicsShapeQueryParameters3DMethodSetCollisionMask(), self.Ptr(), args[:], nil)
}

// GetCollisionMask mirrors the Godot PhysicsShapeQueryParameters3D.get_collision_mask method.
func (self *PhysicsShapeQueryParameters3D) GetCollisionMask() int64 {
	var ret int64
	gdextension.CallMethodBindPtrCall(physicsShapeQueryParameters3DMethodGetCollisionMask(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetExclude mirrors the Godot PhysicsShapeQueryParameters3D.set_exclude method.
func (self *PhysicsShapeQueryParameters3D) SetExclude(exclude variant.Array) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&exclude)),
	}
	gdextension.CallMethodBindPtrCall(physicsShapeQueryParameters3DMethodSetExclude(), self.Ptr(), args[:], nil)
}

// GetExclude mirrors the Godot PhysicsShapeQueryParameters3D.get_exclude method.
func (self *PhysicsShapeQueryParameters3D) GetExclude() variant.Array {
	var ret variant.Array
	gdextension.CallMethodBindPtrCall(physicsShapeQueryParameters3DMethodGetExclude(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetCollideWithBodies mirrors the Godot PhysicsShapeQueryParameters3D.set_collide_with_bodies method.
func (self *PhysicsShapeQueryParameters3D) SetCollideWithBodies(enable bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&enable)),
	}
	gdextension.CallMethodBindPtrCall(physicsShapeQueryParameters3DMethodSetCollideWithBodies(), self.Ptr(), args[:], nil)
}

// IsCollideWithBodiesEnabled mirrors the Godot PhysicsShapeQueryParameters3D.is_collide_with_bodies_enabled method.
func (self *PhysicsShapeQueryParameters3D) IsCollideWithBodiesEnabled() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(physicsShapeQueryParameters3DMethodIsCollideWithBodiesEnabled(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetCollideWithAreas mirrors the Godot PhysicsShapeQueryParameters3D.set_collide_with_areas method.
func (self *PhysicsShapeQueryParameters3D) SetCollideWithAreas(enable bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&enable)),
	}
	gdextension.CallMethodBindPtrCall(physicsShapeQueryParameters3DMethodSetCollideWithAreas(), self.Ptr(), args[:], nil)
}

// IsCollideWithAreasEnabled mirrors the Godot PhysicsShapeQueryParameters3D.is_collide_with_areas_enabled method.
func (self *PhysicsShapeQueryParameters3D) IsCollideWithAreasEnabled() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(physicsShapeQueryParameters3DMethodIsCollideWithAreasEnabled(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}
