// Code generated by godot-go-bindgen. DO NOT EDIT.

package core

import (
	"sync"
	"unsafe"

	"github.com/legendary-code/godot-go/internal/gdextension"
	"github.com/legendary-code/godot-go/variant"
)

// PhysicsDirectSpaceState2DExtension mirrors the Godot engine class PhysicsDirectSpaceState2DExtension.
type PhysicsDirectSpaceState2DExtension struct {
	PhysicsDirectSpaceState2D
}

// PhysicsDirectSpaceState2DExtensionFromPtr wraps an existing host-allocated GDExtensionObjectPtr in a
// *PhysicsDirectSpaceState2DExtension. Returns nil on a nil input.
func PhysicsDirectSpaceState2DExtensionFromPtr(p gdextension.ObjectPtr) *PhysicsDirectSpaceState2DExtension {
	if p == nil {
		return nil
	}
	ret := &PhysicsDirectSpaceState2DExtension{}
	ret.BindPtr(p)
	return ret
}

var (
	physicsDirectSpaceState2DExtensionMethodIsBodyExcludedFromQuery = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("PhysicsDirectSpaceState2DExtension"),
			gdextension.InternStringName("is_body_excluded_from_query"),
			4155700596,
		)
	})
)

// IsBodyExcludedFromQuery mirrors the Godot PhysicsDirectSpaceState2DExtension.is_body_excluded_from_query method.
func (self *PhysicsDirectSpaceState2DExtension) IsBodyExcludedFromQuery(body variant.RID) bool {
	var ret bool
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&body)),
	}
	gdextension.CallMethodBindPtrCall(physicsDirectSpaceState2DExtensionMethodIsBodyExcludedFromQuery(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}
