// Code generated by godot-go-bindgen. DO NOT EDIT.

package core

import (
	"sync"
	"unsafe"

	"github.com/legendary-code/godot-go/internal/gdextension"
	"github.com/legendary-code/godot-go/variant"
)

// PhysicsDirectSpaceState3D mirrors the Godot engine class PhysicsDirectSpaceState3D.
type PhysicsDirectSpaceState3D struct {
	Object
}

// PhysicsDirectSpaceState3DFromPtr wraps an existing host-allocated GDExtensionObjectPtr in a
// *PhysicsDirectSpaceState3D. Returns nil on a nil input.
func PhysicsDirectSpaceState3DFromPtr(p gdextension.ObjectPtr) *PhysicsDirectSpaceState3D {
	if p == nil {
		return nil
	}
	ret := &PhysicsDirectSpaceState3D{}
	ret.BindPtr(p)
	return ret
}

var (
	physicsDirectSpaceState3DMethodIntersectPoint = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("PhysicsDirectSpaceState3D"),
			gdextension.InternStringName("intersect_point"),
			975173756,
		)
	})
	physicsDirectSpaceState3DMethodIntersectRay = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("PhysicsDirectSpaceState3D"),
			gdextension.InternStringName("intersect_ray"),
			3957970750,
		)
	})
	physicsDirectSpaceState3DMethodIntersectShape = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("PhysicsDirectSpaceState3D"),
			gdextension.InternStringName("intersect_shape"),
			3762137681,
		)
	})
	physicsDirectSpaceState3DMethodCastMotion = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("PhysicsDirectSpaceState3D"),
			gdextension.InternStringName("cast_motion"),
			1778757334,
		)
	})
	physicsDirectSpaceState3DMethodCollideShape = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("PhysicsDirectSpaceState3D"),
			gdextension.InternStringName("collide_shape"),
			3762137681,
		)
	})
	physicsDirectSpaceState3DMethodGetRestInfo = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("PhysicsDirectSpaceState3D"),
			gdextension.InternStringName("get_rest_info"),
			1376751592,
		)
	})
)

// IntersectPoint mirrors the Godot PhysicsDirectSpaceState3D.intersect_point method.
func (self *PhysicsDirectSpaceState3D) IntersectPoint(parameters *PhysicsPointQueryParameters3D, max_results int64) variant.Array {
	var ret variant.Array
	var tmp_parameters gdextension.ObjectPtr
	if parameters != nil {
		tmp_parameters = parameters.Ptr()
	}

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_parameters)),
		gdextension.TypePtr(unsafe.Pointer(&max_results)),
	}
	gdextension.CallMethodBindPtrCall(physicsDirectSpaceState3DMethodIntersectPoint(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// IntersectRay mirrors the Godot PhysicsDirectSpaceState3D.intersect_ray method.
func (self *PhysicsDirectSpaceState3D) IntersectRay(parameters *PhysicsRayQueryParameters3D) variant.Dictionary {
	var ret variant.Dictionary
	var tmp_parameters gdextension.ObjectPtr
	if parameters != nil {
		tmp_parameters = parameters.Ptr()
	}

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_parameters)),
	}
	gdextension.CallMethodBindPtrCall(physicsDirectSpaceState3DMethodIntersectRay(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// IntersectShape mirrors the Godot PhysicsDirectSpaceState3D.intersect_shape method.
func (self *PhysicsDirectSpaceState3D) IntersectShape(parameters *PhysicsShapeQueryParameters3D, max_results int64) variant.Array {
	var ret variant.Array
	var tmp_parameters gdextension.ObjectPtr
	if parameters != nil {
		tmp_parameters = parameters.Ptr()
	}

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_parameters)),
		gdextension.TypePtr(unsafe.Pointer(&max_results)),
	}
	gdextension.CallMethodBindPtrCall(physicsDirectSpaceState3DMethodIntersectShape(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// CastMotion mirrors the Godot PhysicsDirectSpaceState3D.cast_motion method.
func (self *PhysicsDirectSpaceState3D) CastMotion(parameters *PhysicsShapeQueryParameters3D) variant.PackedFloat32Array {
	var ret variant.PackedFloat32Array
	var tmp_parameters gdextension.ObjectPtr
	if parameters != nil {
		tmp_parameters = parameters.Ptr()
	}

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_parameters)),
	}
	gdextension.CallMethodBindPtrCall(physicsDirectSpaceState3DMethodCastMotion(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// CollideShape mirrors the Godot PhysicsDirectSpaceState3D.collide_shape method.
func (self *PhysicsDirectSpaceState3D) CollideShape(parameters *PhysicsShapeQueryParameters3D, max_results int64) variant.Array {
	var ret variant.Array
	var tmp_parameters gdextension.ObjectPtr
	if parameters != nil {
		tmp_parameters = parameters.Ptr()
	}

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_parameters)),
		gdextension.TypePtr(unsafe.Pointer(&max_results)),
	}
	gdextension.CallMethodBindPtrCall(physicsDirectSpaceState3DMethodCollideShape(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// GetRestInfo mirrors the Godot PhysicsDirectSpaceState3D.get_rest_info method.
func (self *PhysicsDirectSpaceState3D) GetRestInfo(parameters *PhysicsShapeQueryParameters3D) variant.Dictionary {
	var ret variant.Dictionary
	var tmp_parameters gdextension.ObjectPtr
	if parameters != nil {
		tmp_parameters = parameters.Ptr()
	}

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_parameters)),
	}
	gdextension.CallMethodBindPtrCall(physicsDirectSpaceState3DMethodGetRestInfo(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}
