// Code generated by godot-go-bindgen. DO NOT EDIT.

package core

import (
	"runtime"

	"github.com/legendary-code/godot-go/gdextension"
)

// PlaceholderTexture2DArray mirrors the Godot engine class PlaceholderTexture2DArray.
type PlaceholderTexture2DArray struct {
	PlaceholderTextureLayered
}

// PlaceholderTexture2DArrayFromPtr wraps an existing host-allocated GDExtensionObjectPtr in a
// *PlaceholderTexture2DArray. Returns nil on a nil input. PlaceholderTexture2DArray descends from RefCounted, so the
// returned wrapper carries a Go finalizer that drops one engine
// reference (via Unreference, dispatched on the main thread) when
// Go's GC determines the wrapper is unreachable. Users who want
// deterministic free can call ret.Unreference() directly — the
// finalizer is harmless after the refcount hits zero.
func PlaceholderTexture2DArrayFromPtr(p gdextension.ObjectPtr) *PlaceholderTexture2DArray {
	if p == nil {
		return nil
	}
	ret := &PlaceholderTexture2DArray{}
	ret.BindPtr(p)
	runtime.SetFinalizer(ret, func(r *PlaceholderTexture2DArray) {
		gdextension.RunOnMain(func() { r.Unreference() })
	})
	return ret
}
