// Code generated by godot-go-bindgen. DO NOT EDIT.

package core

import (
	"runtime"
	"sync"
	"unsafe"

	"github.com/legendary-code/godot-go/gdextension"
	"github.com/legendary-code/godot-go/variant"
)

// RandomNumberGenerator mirrors the Godot engine class RandomNumberGenerator.
type RandomNumberGenerator struct {
	RefCounted
}

// RandomNumberGeneratorFromPtr wraps an existing host-allocated GDExtensionObjectPtr in a
// *RandomNumberGenerator. Returns nil on a nil input. RandomNumberGenerator descends from RefCounted, so the
// returned wrapper carries a Go finalizer that drops one engine
// reference (via Unreference, dispatched on the main thread) when
// Go's GC determines the wrapper is unreachable. Users who want
// deterministic free can call ret.Unreference() directly — the
// finalizer is harmless after the refcount hits zero.
func RandomNumberGeneratorFromPtr(p gdextension.ObjectPtr) *RandomNumberGenerator {
	if p == nil {
		return nil
	}
	ret := &RandomNumberGenerator{}
	ret.BindPtr(p)
	runtime.SetFinalizer(ret, func(r *RandomNumberGenerator) {
		gdextension.RunOnMain(func() { r.Unreference() })
	})
	return ret
}

var (
	randomNumberGeneratorMethodSetSeed = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("RandomNumberGenerator"),
			gdextension.InternStringName("set_seed"),
			1286410249,
		)
	})
	randomNumberGeneratorMethodGetSeed = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("RandomNumberGenerator"),
			gdextension.InternStringName("get_seed"),
			2455072627,
		)
	})
	randomNumberGeneratorMethodSetState = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("RandomNumberGenerator"),
			gdextension.InternStringName("set_state"),
			1286410249,
		)
	})
	randomNumberGeneratorMethodGetState = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("RandomNumberGenerator"),
			gdextension.InternStringName("get_state"),
			3905245786,
		)
	})
	randomNumberGeneratorMethodRandi = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("RandomNumberGenerator"),
			gdextension.InternStringName("randi"),
			2455072627,
		)
	})
	randomNumberGeneratorMethodRandf = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("RandomNumberGenerator"),
			gdextension.InternStringName("randf"),
			191475506,
		)
	})
	randomNumberGeneratorMethodRandfn = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("RandomNumberGenerator"),
			gdextension.InternStringName("randfn"),
			837325100,
		)
	})
	randomNumberGeneratorMethodRandfRange = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("RandomNumberGenerator"),
			gdextension.InternStringName("randf_range"),
			4269894367,
		)
	})
	randomNumberGeneratorMethodRandiRange = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("RandomNumberGenerator"),
			gdextension.InternStringName("randi_range"),
			50157827,
		)
	})
	randomNumberGeneratorMethodRandWeighted = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("RandomNumberGenerator"),
			gdextension.InternStringName("rand_weighted"),
			4189642986,
		)
	})
	randomNumberGeneratorMethodRandomize = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("RandomNumberGenerator"),
			gdextension.InternStringName("randomize"),
			3218959716,
		)
	})
)

// SetSeed mirrors the Godot RandomNumberGenerator.set_seed method.
func (self *RandomNumberGenerator) SetSeed(seed int64) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&seed)),
	}
	gdextension.CallMethodBindPtrCall(randomNumberGeneratorMethodSetSeed(), self.Ptr(), args[:], nil)
}

// GetSeed mirrors the Godot RandomNumberGenerator.get_seed method.
func (self *RandomNumberGenerator) GetSeed() int64 {
	var ret int64
	gdextension.CallMethodBindPtrCall(randomNumberGeneratorMethodGetSeed(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetState mirrors the Godot RandomNumberGenerator.set_state method.
func (self *RandomNumberGenerator) SetState(state int64) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&state)),
	}
	gdextension.CallMethodBindPtrCall(randomNumberGeneratorMethodSetState(), self.Ptr(), args[:], nil)
}

// GetState mirrors the Godot RandomNumberGenerator.get_state method.
func (self *RandomNumberGenerator) GetState() int64 {
	var ret int64
	gdextension.CallMethodBindPtrCall(randomNumberGeneratorMethodGetState(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// Randi mirrors the Godot RandomNumberGenerator.randi method.
func (self *RandomNumberGenerator) Randi() int64 {
	var ret int64
	gdextension.CallMethodBindPtrCall(randomNumberGeneratorMethodRandi(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// Randf mirrors the Godot RandomNumberGenerator.randf method.
func (self *RandomNumberGenerator) Randf() float32 {
	var raw float64
	gdextension.CallMethodBindPtrCall(randomNumberGeneratorMethodRandf(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}

// Randfn mirrors the Godot RandomNumberGenerator.randfn method.
func (self *RandomNumberGenerator) Randfn(mean float32, deviation float32) float32 {
	var raw float64
	tmp_mean := float64(mean)

	tmp_deviation := float64(deviation)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_mean)),
		gdextension.TypePtr(unsafe.Pointer(&tmp_deviation)),
	}
	gdextension.CallMethodBindPtrCall(randomNumberGeneratorMethodRandfn(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}

// RandfRange mirrors the Godot RandomNumberGenerator.randf_range method.
func (self *RandomNumberGenerator) RandfRange(from float32, to float32) float32 {
	var raw float64
	tmp_from := float64(from)

	tmp_to := float64(to)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_from)),
		gdextension.TypePtr(unsafe.Pointer(&tmp_to)),
	}
	gdextension.CallMethodBindPtrCall(randomNumberGeneratorMethodRandfRange(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}

// RandiRange mirrors the Godot RandomNumberGenerator.randi_range method.
func (self *RandomNumberGenerator) RandiRange(from int64, to int64) int64 {
	var ret int64
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&from)),
		gdextension.TypePtr(unsafe.Pointer(&to)),
	}
	gdextension.CallMethodBindPtrCall(randomNumberGeneratorMethodRandiRange(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// RandWeighted mirrors the Godot RandomNumberGenerator.rand_weighted method.
func (self *RandomNumberGenerator) RandWeighted(weights variant.PackedFloat32Array) int64 {
	var ret int64
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&weights)),
	}
	gdextension.CallMethodBindPtrCall(randomNumberGeneratorMethodRandWeighted(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// Randomize mirrors the Godot RandomNumberGenerator.randomize method.
func (self *RandomNumberGenerator) Randomize() {
	gdextension.CallMethodBindPtrCall(randomNumberGeneratorMethodRandomize(), self.Ptr(), nil, nil)
}
