// Code generated by godot-go-bindgen. DO NOT EDIT.

package core

import (
	"runtime"
	"sync"
	"unsafe"

	"github.com/legendary-code/godot-go/internal/gdextension"
	"github.com/legendary-code/godot-go/variant"
)

// RegEx mirrors the Godot engine class RegEx.
type RegEx struct {
	RefCounted
}

// RegExFromPtr wraps an existing host-allocated GDExtensionObjectPtr in a
// *RegEx. Returns nil on a nil input. RegEx descends from RefCounted, so the
// returned wrapper carries a Go finalizer that drops one engine
// reference (via Unreference, dispatched on the main thread) when
// Go's GC determines the wrapper is unreachable. Users who want
// deterministic free can call ret.Unreference() directly — the
// finalizer is harmless after the refcount hits zero.
func RegExFromPtr(p gdextension.ObjectPtr) *RegEx {
	if p == nil {
		return nil
	}
	ret := &RegEx{}
	ret.BindPtr(p)
	runtime.SetFinalizer(ret, func(r *RegEx) {
		gdextension.RunOnMain(func() { r.Unreference() })
	})
	return ret
}

var (
	regExMethodCreateFromString = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("RegEx"),
			gdextension.InternStringName("create_from_string"),
			4249111514,
		)
	})
	regExMethodClear = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("RegEx"),
			gdextension.InternStringName("clear"),
			3218959716,
		)
	})
	regExMethodCompile = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("RegEx"),
			gdextension.InternStringName("compile"),
			3565188097,
		)
	})
	regExMethodSearch = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("RegEx"),
			gdextension.InternStringName("search"),
			3365977994,
		)
	})
	regExMethodSearchAll = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("RegEx"),
			gdextension.InternStringName("search_all"),
			849021363,
		)
	})
	regExMethodSub = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("RegEx"),
			gdextension.InternStringName("sub"),
			54019702,
		)
	})
	regExMethodIsValid = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("RegEx"),
			gdextension.InternStringName("is_valid"),
			36873697,
		)
	})
	regExMethodGetPattern = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("RegEx"),
			gdextension.InternStringName("get_pattern"),
			201670096,
		)
	})
	regExMethodGetGroupCount = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("RegEx"),
			gdextension.InternStringName("get_group_count"),
			3905245786,
		)
	})
	regExMethodGetNames = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("RegEx"),
			gdextension.InternStringName("get_names"),
			1139954409,
		)
	})
)

// CreateFromString mirrors the Godot RegEx.create_from_string method.
func RegExCreateFromString(pattern string, show_error bool) *RegEx {
	var ret gdextension.ObjectPtr
	tmp_pattern := variant.NewStringFromString(pattern)
	defer tmp_pattern.Destroy()

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_pattern)),
		gdextension.TypePtr(unsafe.Pointer(&show_error)),
	}
	gdextension.CallMethodBindPtrCall(regExMethodCreateFromString(), nil, args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return RegExFromPtr(ret)
}

// Clear mirrors the Godot RegEx.clear method.
func (self *RegEx) Clear() {
	gdextension.CallMethodBindPtrCall(regExMethodClear(), self.Ptr(), nil, nil)
}

// Compile mirrors the Godot RegEx.compile method.
func (self *RegEx) Compile(pattern string, show_error bool) int64 {
	var ret int64
	tmp_pattern := variant.NewStringFromString(pattern)
	defer tmp_pattern.Destroy()

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_pattern)),
		gdextension.TypePtr(unsafe.Pointer(&show_error)),
	}
	gdextension.CallMethodBindPtrCall(regExMethodCompile(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// Search mirrors the Godot RegEx.search method.
func (self *RegEx) Search(subject string, offset int64, end int64) *RegExMatch {
	var ret gdextension.ObjectPtr
	tmp_subject := variant.NewStringFromString(subject)
	defer tmp_subject.Destroy()

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_subject)),
		gdextension.TypePtr(unsafe.Pointer(&offset)),
		gdextension.TypePtr(unsafe.Pointer(&end)),
	}
	gdextension.CallMethodBindPtrCall(regExMethodSearch(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return RegExMatchFromPtr(ret)
}

// SearchAll mirrors the Godot RegEx.search_all method.
func (self *RegEx) SearchAll(subject string, offset int64, end int64) variant.Array {
	var ret variant.Array
	tmp_subject := variant.NewStringFromString(subject)
	defer tmp_subject.Destroy()

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_subject)),
		gdextension.TypePtr(unsafe.Pointer(&offset)),
		gdextension.TypePtr(unsafe.Pointer(&end)),
	}
	gdextension.CallMethodBindPtrCall(regExMethodSearchAll(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// Sub mirrors the Godot RegEx.sub method.
func (self *RegEx) Sub(subject string, replacement string, all bool, offset int64, end int64) string {
	var raw variant.String
	defer raw.Destroy()
	tmp_subject := variant.NewStringFromString(subject)
	defer tmp_subject.Destroy()

	tmp_replacement := variant.NewStringFromString(replacement)
	defer tmp_replacement.Destroy()

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_subject)),
		gdextension.TypePtr(unsafe.Pointer(&tmp_replacement)),
		gdextension.TypePtr(unsafe.Pointer(&all)),
		gdextension.TypePtr(unsafe.Pointer(&offset)),
		gdextension.TypePtr(unsafe.Pointer(&end)),
	}
	gdextension.CallMethodBindPtrCall(regExMethodSub(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&raw)))
	return variant.StringToGo(&raw)
}

// IsValid mirrors the Godot RegEx.is_valid method.
func (self *RegEx) IsValid() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(regExMethodIsValid(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// GetPattern mirrors the Godot RegEx.get_pattern method.
func (self *RegEx) GetPattern() string {
	var raw variant.String
	defer raw.Destroy()
	gdextension.CallMethodBindPtrCall(regExMethodGetPattern(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return variant.StringToGo(&raw)
}

// GetGroupCount mirrors the Godot RegEx.get_group_count method.
func (self *RegEx) GetGroupCount() int64 {
	var ret int64
	gdextension.CallMethodBindPtrCall(regExMethodGetGroupCount(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// GetNames mirrors the Godot RegEx.get_names method.
func (self *RegEx) GetNames() variant.PackedStringArray {
	var ret variant.PackedStringArray
	gdextension.CallMethodBindPtrCall(regExMethodGetNames(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}
