// Code generated by godot-go-bindgen. DO NOT EDIT.

package core

import (
	"runtime"
	"sync"
	"unsafe"

	"github.com/legendary-code/godot-go/internal/gdextension"
	"github.com/legendary-code/godot-go/variant"
)

// SceneReplicationConfig mirrors the Godot engine class SceneReplicationConfig.
type SceneReplicationConfig struct {
	Resource
}

// SceneReplicationConfigFromPtr wraps an existing host-allocated GDExtensionObjectPtr in a
// *SceneReplicationConfig. Returns nil on a nil input. SceneReplicationConfig descends from RefCounted, so the
// returned wrapper carries a Go finalizer that drops one engine
// reference (via Unreference, dispatched on the main thread) when
// Go's GC determines the wrapper is unreachable. Users who want
// deterministic free can call ret.Unreference() directly — the
// finalizer is harmless after the refcount hits zero.
func SceneReplicationConfigFromPtr(p gdextension.ObjectPtr) *SceneReplicationConfig {
	if p == nil {
		return nil
	}
	ret := &SceneReplicationConfig{}
	ret.BindPtr(p)
	runtime.SetFinalizer(ret, func(r *SceneReplicationConfig) {
		gdextension.RunOnMain(func() { r.Unreference() })
	})
	return ret
}

// SceneReplicationConfigReplicationMode is the Godot SceneReplicationConfigReplicationMode enum.
type SceneReplicationConfigReplicationMode int64

const (
	SceneReplicationConfig_REPLICATION_MODE_NEVER     SceneReplicationConfigReplicationMode = 0
	SceneReplicationConfig_REPLICATION_MODE_ALWAYS    SceneReplicationConfigReplicationMode = 1
	SceneReplicationConfig_REPLICATION_MODE_ON_CHANGE SceneReplicationConfigReplicationMode = 2
)

var (
	sceneReplicationConfigMethodGetProperties = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("SceneReplicationConfig"),
			gdextension.InternStringName("get_properties"),
			3995934104,
		)
	})
	sceneReplicationConfigMethodAddProperty = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("SceneReplicationConfig"),
			gdextension.InternStringName("add_property"),
			4094619021,
		)
	})
	sceneReplicationConfigMethodHasProperty = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("SceneReplicationConfig"),
			gdextension.InternStringName("has_property"),
			861721659,
		)
	})
	sceneReplicationConfigMethodRemoveProperty = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("SceneReplicationConfig"),
			gdextension.InternStringName("remove_property"),
			1348162250,
		)
	})
	sceneReplicationConfigMethodPropertyGetIndex = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("SceneReplicationConfig"),
			gdextension.InternStringName("property_get_index"),
			1382022557,
		)
	})
	sceneReplicationConfigMethodPropertyGetSpawn = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("SceneReplicationConfig"),
			gdextension.InternStringName("property_get_spawn"),
			3456846888,
		)
	})
	sceneReplicationConfigMethodPropertySetSpawn = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("SceneReplicationConfig"),
			gdextension.InternStringName("property_set_spawn"),
			3868023870,
		)
	})
	sceneReplicationConfigMethodPropertyGetReplicationMode = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("SceneReplicationConfig"),
			gdextension.InternStringName("property_get_replication_mode"),
			2870606336,
		)
	})
	sceneReplicationConfigMethodPropertySetReplicationMode = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("SceneReplicationConfig"),
			gdextension.InternStringName("property_set_replication_mode"),
			3200083865,
		)
	})
	sceneReplicationConfigMethodPropertyGetSync = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("SceneReplicationConfig"),
			gdextension.InternStringName("property_get_sync"),
			3456846888,
		)
	})
	sceneReplicationConfigMethodPropertySetSync = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("SceneReplicationConfig"),
			gdextension.InternStringName("property_set_sync"),
			3868023870,
		)
	})
	sceneReplicationConfigMethodPropertyGetWatch = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("SceneReplicationConfig"),
			gdextension.InternStringName("property_get_watch"),
			3456846888,
		)
	})
	sceneReplicationConfigMethodPropertySetWatch = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("SceneReplicationConfig"),
			gdextension.InternStringName("property_set_watch"),
			3868023870,
		)
	})
)

// GetProperties mirrors the Godot SceneReplicationConfig.get_properties method.
func (self *SceneReplicationConfig) GetProperties() variant.Array {
	var ret variant.Array
	gdextension.CallMethodBindPtrCall(sceneReplicationConfigMethodGetProperties(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// AddProperty mirrors the Godot SceneReplicationConfig.add_property method.
func (self *SceneReplicationConfig) AddProperty(path string, index int64) {
	tmp_path := variant.NewNodePathFromString(path)
	defer tmp_path.Destroy()

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_path)),
		gdextension.TypePtr(unsafe.Pointer(&index)),
	}
	gdextension.CallMethodBindPtrCall(sceneReplicationConfigMethodAddProperty(), self.Ptr(), args[:], nil)
}

// HasProperty mirrors the Godot SceneReplicationConfig.has_property method.
func (self *SceneReplicationConfig) HasProperty(path string) bool {
	var ret bool
	tmp_path := variant.NewNodePathFromString(path)
	defer tmp_path.Destroy()

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_path)),
	}
	gdextension.CallMethodBindPtrCall(sceneReplicationConfigMethodHasProperty(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// RemoveProperty mirrors the Godot SceneReplicationConfig.remove_property method.
func (self *SceneReplicationConfig) RemoveProperty(path string) {
	tmp_path := variant.NewNodePathFromString(path)
	defer tmp_path.Destroy()

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_path)),
	}
	gdextension.CallMethodBindPtrCall(sceneReplicationConfigMethodRemoveProperty(), self.Ptr(), args[:], nil)
}

// PropertyGetIndex mirrors the Godot SceneReplicationConfig.property_get_index method.
func (self *SceneReplicationConfig) PropertyGetIndex(path string) int64 {
	var ret int64
	tmp_path := variant.NewNodePathFromString(path)
	defer tmp_path.Destroy()

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_path)),
	}
	gdextension.CallMethodBindPtrCall(sceneReplicationConfigMethodPropertyGetIndex(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// PropertyGetSpawn mirrors the Godot SceneReplicationConfig.property_get_spawn method.
func (self *SceneReplicationConfig) PropertyGetSpawn(path string) bool {
	var ret bool
	tmp_path := variant.NewNodePathFromString(path)
	defer tmp_path.Destroy()

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_path)),
	}
	gdextension.CallMethodBindPtrCall(sceneReplicationConfigMethodPropertyGetSpawn(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// PropertySetSpawn mirrors the Godot SceneReplicationConfig.property_set_spawn method.
func (self *SceneReplicationConfig) PropertySetSpawn(path string, enabled bool) {
	tmp_path := variant.NewNodePathFromString(path)
	defer tmp_path.Destroy()

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_path)),
		gdextension.TypePtr(unsafe.Pointer(&enabled)),
	}
	gdextension.CallMethodBindPtrCall(sceneReplicationConfigMethodPropertySetSpawn(), self.Ptr(), args[:], nil)
}

// PropertyGetReplicationMode mirrors the Godot SceneReplicationConfig.property_get_replication_mode method.
func (self *SceneReplicationConfig) PropertyGetReplicationMode(path string) SceneReplicationConfigReplicationMode {
	var ret int64
	tmp_path := variant.NewNodePathFromString(path)
	defer tmp_path.Destroy()

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_path)),
	}
	gdextension.CallMethodBindPtrCall(sceneReplicationConfigMethodPropertyGetReplicationMode(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return SceneReplicationConfigReplicationMode(ret)
}

// PropertySetReplicationMode mirrors the Godot SceneReplicationConfig.property_set_replication_mode method.
func (self *SceneReplicationConfig) PropertySetReplicationMode(path string, mode SceneReplicationConfigReplicationMode) {
	tmp_path := variant.NewNodePathFromString(path)
	defer tmp_path.Destroy()

	tmp_mode := int64(mode)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_path)),
		gdextension.TypePtr(unsafe.Pointer(&tmp_mode)),
	}
	gdextension.CallMethodBindPtrCall(sceneReplicationConfigMethodPropertySetReplicationMode(), self.Ptr(), args[:], nil)
}

// PropertyGetSync mirrors the Godot SceneReplicationConfig.property_get_sync method.
func (self *SceneReplicationConfig) PropertyGetSync(path string) bool {
	var ret bool
	tmp_path := variant.NewNodePathFromString(path)
	defer tmp_path.Destroy()

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_path)),
	}
	gdextension.CallMethodBindPtrCall(sceneReplicationConfigMethodPropertyGetSync(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// PropertySetSync mirrors the Godot SceneReplicationConfig.property_set_sync method.
func (self *SceneReplicationConfig) PropertySetSync(path string, enabled bool) {
	tmp_path := variant.NewNodePathFromString(path)
	defer tmp_path.Destroy()

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_path)),
		gdextension.TypePtr(unsafe.Pointer(&enabled)),
	}
	gdextension.CallMethodBindPtrCall(sceneReplicationConfigMethodPropertySetSync(), self.Ptr(), args[:], nil)
}

// PropertyGetWatch mirrors the Godot SceneReplicationConfig.property_get_watch method.
func (self *SceneReplicationConfig) PropertyGetWatch(path string) bool {
	var ret bool
	tmp_path := variant.NewNodePathFromString(path)
	defer tmp_path.Destroy()

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_path)),
	}
	gdextension.CallMethodBindPtrCall(sceneReplicationConfigMethodPropertyGetWatch(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// PropertySetWatch mirrors the Godot SceneReplicationConfig.property_set_watch method.
func (self *SceneReplicationConfig) PropertySetWatch(path string, enabled bool) {
	tmp_path := variant.NewNodePathFromString(path)
	defer tmp_path.Destroy()

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_path)),
		gdextension.TypePtr(unsafe.Pointer(&enabled)),
	}
	gdextension.CallMethodBindPtrCall(sceneReplicationConfigMethodPropertySetWatch(), self.Ptr(), args[:], nil)
}
