// Code generated by godot-go-bindgen. DO NOT EDIT.

package core

import (
	"github.com/legendary-code/godot-go/internal/gdextension"
)

// ScriptExtension mirrors the Godot engine class ScriptExtension.
type ScriptExtension struct {
	Script
}

// ScriptExtensionFromPtr wraps an existing host-allocated GDExtensionObjectPtr in a
// *ScriptExtension. Returns nil on a nil input.
func ScriptExtensionFromPtr(p gdextension.ObjectPtr) *ScriptExtension {
	if p == nil {
		return nil
	}
	ret := &ScriptExtension{}
	ret.BindPtr(p)
	return ret
}
