// Code generated by godot-go-bindgen. DO NOT EDIT.

package core

import (
	"runtime"
	"sync"
	"unsafe"

	"github.com/legendary-code/godot-go/internal/gdextension"
	"github.com/legendary-code/godot-go/variant"
)

// SkeletonModification2DCCDIK mirrors the Godot engine class SkeletonModification2DCCDIK.
type SkeletonModification2DCCDIK struct {
	SkeletonModification2D
}

// SkeletonModification2DCCDIKFromPtr wraps an existing host-allocated GDExtensionObjectPtr in a
// *SkeletonModification2DCCDIK. Returns nil on a nil input. SkeletonModification2DCCDIK descends from RefCounted, so the
// returned wrapper carries a Go finalizer that drops one engine
// reference (via Unreference, dispatched on the main thread) when
// Go's GC determines the wrapper is unreachable. Users who want
// deterministic free can call ret.Unreference() directly — the
// finalizer is harmless after the refcount hits zero.
func SkeletonModification2DCCDIKFromPtr(p gdextension.ObjectPtr) *SkeletonModification2DCCDIK {
	if p == nil {
		return nil
	}
	ret := &SkeletonModification2DCCDIK{}
	ret.BindPtr(p)
	runtime.SetFinalizer(ret, func(r *SkeletonModification2DCCDIK) {
		gdextension.RunOnMain(func() { r.Unreference() })
	})
	return ret
}

var (
	skeletonModification2DCCDIKMethodSetTargetNode = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("SkeletonModification2DCCDIK"),
			gdextension.InternStringName("set_target_node"),
			1348162250,
		)
	})
	skeletonModification2DCCDIKMethodGetTargetNode = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("SkeletonModification2DCCDIK"),
			gdextension.InternStringName("get_target_node"),
			4075236667,
		)
	})
	skeletonModification2DCCDIKMethodSetTipNode = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("SkeletonModification2DCCDIK"),
			gdextension.InternStringName("set_tip_node"),
			1348162250,
		)
	})
	skeletonModification2DCCDIKMethodGetTipNode = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("SkeletonModification2DCCDIK"),
			gdextension.InternStringName("get_tip_node"),
			4075236667,
		)
	})
	skeletonModification2DCCDIKMethodSetCcdikDataChainLength = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("SkeletonModification2DCCDIK"),
			gdextension.InternStringName("set_ccdik_data_chain_length"),
			1286410249,
		)
	})
	skeletonModification2DCCDIKMethodGetCcdikDataChainLength = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("SkeletonModification2DCCDIK"),
			gdextension.InternStringName("get_ccdik_data_chain_length"),
			2455072627,
		)
	})
	skeletonModification2DCCDIKMethodSetCcdikJointBone2dNode = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("SkeletonModification2DCCDIK"),
			gdextension.InternStringName("set_ccdik_joint_bone2d_node"),
			2761262315,
		)
	})
	skeletonModification2DCCDIKMethodGetCcdikJointBone2dNode = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("SkeletonModification2DCCDIK"),
			gdextension.InternStringName("get_ccdik_joint_bone2d_node"),
			408788394,
		)
	})
	skeletonModification2DCCDIKMethodSetCcdikJointBoneIndex = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("SkeletonModification2DCCDIK"),
			gdextension.InternStringName("set_ccdik_joint_bone_index"),
			3937882851,
		)
	})
	skeletonModification2DCCDIKMethodGetCcdikJointBoneIndex = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("SkeletonModification2DCCDIK"),
			gdextension.InternStringName("get_ccdik_joint_bone_index"),
			923996154,
		)
	})
	skeletonModification2DCCDIKMethodSetCcdikJointRotateFromJoint = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("SkeletonModification2DCCDIK"),
			gdextension.InternStringName("set_ccdik_joint_rotate_from_joint"),
			300928843,
		)
	})
	skeletonModification2DCCDIKMethodGetCcdikJointRotateFromJoint = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("SkeletonModification2DCCDIK"),
			gdextension.InternStringName("get_ccdik_joint_rotate_from_joint"),
			1116898809,
		)
	})
	skeletonModification2DCCDIKMethodSetCcdikJointEnableConstraint = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("SkeletonModification2DCCDIK"),
			gdextension.InternStringName("set_ccdik_joint_enable_constraint"),
			300928843,
		)
	})
	skeletonModification2DCCDIKMethodGetCcdikJointEnableConstraint = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("SkeletonModification2DCCDIK"),
			gdextension.InternStringName("get_ccdik_joint_enable_constraint"),
			1116898809,
		)
	})
	skeletonModification2DCCDIKMethodSetCcdikJointConstraintAngleMin = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("SkeletonModification2DCCDIK"),
			gdextension.InternStringName("set_ccdik_joint_constraint_angle_min"),
			1602489585,
		)
	})
	skeletonModification2DCCDIKMethodGetCcdikJointConstraintAngleMin = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("SkeletonModification2DCCDIK"),
			gdextension.InternStringName("get_ccdik_joint_constraint_angle_min"),
			2339986948,
		)
	})
	skeletonModification2DCCDIKMethodSetCcdikJointConstraintAngleMax = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("SkeletonModification2DCCDIK"),
			gdextension.InternStringName("set_ccdik_joint_constraint_angle_max"),
			1602489585,
		)
	})
	skeletonModification2DCCDIKMethodGetCcdikJointConstraintAngleMax = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("SkeletonModification2DCCDIK"),
			gdextension.InternStringName("get_ccdik_joint_constraint_angle_max"),
			2339986948,
		)
	})
	skeletonModification2DCCDIKMethodSetCcdikJointConstraintAngleInvert = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("SkeletonModification2DCCDIK"),
			gdextension.InternStringName("set_ccdik_joint_constraint_angle_invert"),
			300928843,
		)
	})
	skeletonModification2DCCDIKMethodGetCcdikJointConstraintAngleInvert = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("SkeletonModification2DCCDIK"),
			gdextension.InternStringName("get_ccdik_joint_constraint_angle_invert"),
			1116898809,
		)
	})
)

// SetTargetNode mirrors the Godot SkeletonModification2DCCDIK.set_target_node method.
func (self *SkeletonModification2DCCDIK) SetTargetNode(target_nodepath string) {
	tmp_target_nodepath := variant.NewNodePathFromString(target_nodepath)
	defer tmp_target_nodepath.Destroy()

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_target_nodepath)),
	}
	gdextension.CallMethodBindPtrCall(skeletonModification2DCCDIKMethodSetTargetNode(), self.Ptr(), args[:], nil)
}

// GetTargetNode mirrors the Godot SkeletonModification2DCCDIK.get_target_node method.
func (self *SkeletonModification2DCCDIK) GetTargetNode() string {
	var raw variant.NodePath
	defer raw.Destroy()
	gdextension.CallMethodBindPtrCall(skeletonModification2DCCDIKMethodGetTargetNode(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return variant.NodePathToGo(&raw)
}

// SetTipNode mirrors the Godot SkeletonModification2DCCDIK.set_tip_node method.
func (self *SkeletonModification2DCCDIK) SetTipNode(tip_nodepath string) {
	tmp_tip_nodepath := variant.NewNodePathFromString(tip_nodepath)
	defer tmp_tip_nodepath.Destroy()

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_tip_nodepath)),
	}
	gdextension.CallMethodBindPtrCall(skeletonModification2DCCDIKMethodSetTipNode(), self.Ptr(), args[:], nil)
}

// GetTipNode mirrors the Godot SkeletonModification2DCCDIK.get_tip_node method.
func (self *SkeletonModification2DCCDIK) GetTipNode() string {
	var raw variant.NodePath
	defer raw.Destroy()
	gdextension.CallMethodBindPtrCall(skeletonModification2DCCDIKMethodGetTipNode(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return variant.NodePathToGo(&raw)
}

// SetCcdikDataChainLength mirrors the Godot SkeletonModification2DCCDIK.set_ccdik_data_chain_length method.
func (self *SkeletonModification2DCCDIK) SetCcdikDataChainLength(length int64) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&length)),
	}
	gdextension.CallMethodBindPtrCall(skeletonModification2DCCDIKMethodSetCcdikDataChainLength(), self.Ptr(), args[:], nil)
}

// GetCcdikDataChainLength mirrors the Godot SkeletonModification2DCCDIK.get_ccdik_data_chain_length method.
func (self *SkeletonModification2DCCDIK) GetCcdikDataChainLength() int64 {
	var ret int64
	gdextension.CallMethodBindPtrCall(skeletonModification2DCCDIKMethodGetCcdikDataChainLength(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetCcdikJointBone2dNode mirrors the Godot SkeletonModification2DCCDIK.set_ccdik_joint_bone2d_node method.
func (self *SkeletonModification2DCCDIK) SetCcdikJointBone2dNode(joint_idx int64, bone2d_nodepath string) {
	tmp_bone2d_nodepath := variant.NewNodePathFromString(bone2d_nodepath)
	defer tmp_bone2d_nodepath.Destroy()

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&joint_idx)),
		gdextension.TypePtr(unsafe.Pointer(&tmp_bone2d_nodepath)),
	}
	gdextension.CallMethodBindPtrCall(skeletonModification2DCCDIKMethodSetCcdikJointBone2dNode(), self.Ptr(), args[:], nil)
}

// GetCcdikJointBone2dNode mirrors the Godot SkeletonModification2DCCDIK.get_ccdik_joint_bone2d_node method.
func (self *SkeletonModification2DCCDIK) GetCcdikJointBone2dNode(joint_idx int64) string {
	var raw variant.NodePath
	defer raw.Destroy()
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&joint_idx)),
	}
	gdextension.CallMethodBindPtrCall(skeletonModification2DCCDIKMethodGetCcdikJointBone2dNode(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&raw)))
	return variant.NodePathToGo(&raw)
}

// SetCcdikJointBoneIndex mirrors the Godot SkeletonModification2DCCDIK.set_ccdik_joint_bone_index method.
func (self *SkeletonModification2DCCDIK) SetCcdikJointBoneIndex(joint_idx int64, bone_idx int64) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&joint_idx)),
		gdextension.TypePtr(unsafe.Pointer(&bone_idx)),
	}
	gdextension.CallMethodBindPtrCall(skeletonModification2DCCDIKMethodSetCcdikJointBoneIndex(), self.Ptr(), args[:], nil)
}

// GetCcdikJointBoneIndex mirrors the Godot SkeletonModification2DCCDIK.get_ccdik_joint_bone_index method.
func (self *SkeletonModification2DCCDIK) GetCcdikJointBoneIndex(joint_idx int64) int64 {
	var ret int64
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&joint_idx)),
	}
	gdextension.CallMethodBindPtrCall(skeletonModification2DCCDIKMethodGetCcdikJointBoneIndex(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetCcdikJointRotateFromJoint mirrors the Godot SkeletonModification2DCCDIK.set_ccdik_joint_rotate_from_joint method.
func (self *SkeletonModification2DCCDIK) SetCcdikJointRotateFromJoint(joint_idx int64, rotate_from_joint bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&joint_idx)),
		gdextension.TypePtr(unsafe.Pointer(&rotate_from_joint)),
	}
	gdextension.CallMethodBindPtrCall(skeletonModification2DCCDIKMethodSetCcdikJointRotateFromJoint(), self.Ptr(), args[:], nil)
}

// GetCcdikJointRotateFromJoint mirrors the Godot SkeletonModification2DCCDIK.get_ccdik_joint_rotate_from_joint method.
func (self *SkeletonModification2DCCDIK) GetCcdikJointRotateFromJoint(joint_idx int64) bool {
	var ret bool
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&joint_idx)),
	}
	gdextension.CallMethodBindPtrCall(skeletonModification2DCCDIKMethodGetCcdikJointRotateFromJoint(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetCcdikJointEnableConstraint mirrors the Godot SkeletonModification2DCCDIK.set_ccdik_joint_enable_constraint method.
func (self *SkeletonModification2DCCDIK) SetCcdikJointEnableConstraint(joint_idx int64, enable_constraint bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&joint_idx)),
		gdextension.TypePtr(unsafe.Pointer(&enable_constraint)),
	}
	gdextension.CallMethodBindPtrCall(skeletonModification2DCCDIKMethodSetCcdikJointEnableConstraint(), self.Ptr(), args[:], nil)
}

// GetCcdikJointEnableConstraint mirrors the Godot SkeletonModification2DCCDIK.get_ccdik_joint_enable_constraint method.
func (self *SkeletonModification2DCCDIK) GetCcdikJointEnableConstraint(joint_idx int64) bool {
	var ret bool
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&joint_idx)),
	}
	gdextension.CallMethodBindPtrCall(skeletonModification2DCCDIKMethodGetCcdikJointEnableConstraint(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetCcdikJointConstraintAngleMin mirrors the Godot SkeletonModification2DCCDIK.set_ccdik_joint_constraint_angle_min method.
func (self *SkeletonModification2DCCDIK) SetCcdikJointConstraintAngleMin(joint_idx int64, angle_min float32) {
	tmp_angle_min := float64(angle_min)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&joint_idx)),
		gdextension.TypePtr(unsafe.Pointer(&tmp_angle_min)),
	}
	gdextension.CallMethodBindPtrCall(skeletonModification2DCCDIKMethodSetCcdikJointConstraintAngleMin(), self.Ptr(), args[:], nil)
}

// GetCcdikJointConstraintAngleMin mirrors the Godot SkeletonModification2DCCDIK.get_ccdik_joint_constraint_angle_min method.
func (self *SkeletonModification2DCCDIK) GetCcdikJointConstraintAngleMin(joint_idx int64) float32 {
	var raw float64
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&joint_idx)),
	}
	gdextension.CallMethodBindPtrCall(skeletonModification2DCCDIKMethodGetCcdikJointConstraintAngleMin(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}

// SetCcdikJointConstraintAngleMax mirrors the Godot SkeletonModification2DCCDIK.set_ccdik_joint_constraint_angle_max method.
func (self *SkeletonModification2DCCDIK) SetCcdikJointConstraintAngleMax(joint_idx int64, angle_max float32) {
	tmp_angle_max := float64(angle_max)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&joint_idx)),
		gdextension.TypePtr(unsafe.Pointer(&tmp_angle_max)),
	}
	gdextension.CallMethodBindPtrCall(skeletonModification2DCCDIKMethodSetCcdikJointConstraintAngleMax(), self.Ptr(), args[:], nil)
}

// GetCcdikJointConstraintAngleMax mirrors the Godot SkeletonModification2DCCDIK.get_ccdik_joint_constraint_angle_max method.
func (self *SkeletonModification2DCCDIK) GetCcdikJointConstraintAngleMax(joint_idx int64) float32 {
	var raw float64
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&joint_idx)),
	}
	gdextension.CallMethodBindPtrCall(skeletonModification2DCCDIKMethodGetCcdikJointConstraintAngleMax(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}

// SetCcdikJointConstraintAngleInvert mirrors the Godot SkeletonModification2DCCDIK.set_ccdik_joint_constraint_angle_invert method.
func (self *SkeletonModification2DCCDIK) SetCcdikJointConstraintAngleInvert(joint_idx int64, invert bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&joint_idx)),
		gdextension.TypePtr(unsafe.Pointer(&invert)),
	}
	gdextension.CallMethodBindPtrCall(skeletonModification2DCCDIKMethodSetCcdikJointConstraintAngleInvert(), self.Ptr(), args[:], nil)
}

// GetCcdikJointConstraintAngleInvert mirrors the Godot SkeletonModification2DCCDIK.get_ccdik_joint_constraint_angle_invert method.
func (self *SkeletonModification2DCCDIK) GetCcdikJointConstraintAngleInvert(joint_idx int64) bool {
	var ret bool
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&joint_idx)),
	}
	gdextension.CallMethodBindPtrCall(skeletonModification2DCCDIKMethodGetCcdikJointConstraintAngleInvert(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}
