// Code generated by godot-go-bindgen. DO NOT EDIT.

package core

import (
	"runtime"
	"sync"
	"unsafe"

	"github.com/legendary-code/godot-go/gdextension"
)

// SphereShape3D mirrors the Godot engine class SphereShape3D.
type SphereShape3D struct {
	Shape3D
}

// SphereShape3DFromPtr wraps an existing host-allocated GDExtensionObjectPtr in a
// *SphereShape3D. Returns nil on a nil input. SphereShape3D descends from RefCounted, so the
// returned wrapper carries a Go finalizer that drops one engine
// reference (via Unreference, dispatched on the main thread) when
// Go's GC determines the wrapper is unreachable. Users who want
// deterministic free can call ret.Unreference() directly — the
// finalizer is harmless after the refcount hits zero.
func SphereShape3DFromPtr(p gdextension.ObjectPtr) *SphereShape3D {
	if p == nil {
		return nil
	}
	ret := &SphereShape3D{}
	ret.BindPtr(p)
	runtime.SetFinalizer(ret, func(r *SphereShape3D) {
		gdextension.RunOnMain(func() { r.Unreference() })
	})
	return ret
}

var (
	sphereShape3DMethodSetRadius = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("SphereShape3D"),
			gdextension.InternStringName("set_radius"),
			373806689,
		)
	})
	sphereShape3DMethodGetRadius = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("SphereShape3D"),
			gdextension.InternStringName("get_radius"),
			1740695150,
		)
	})
)

// SetRadius mirrors the Godot SphereShape3D.set_radius method.
func (self *SphereShape3D) SetRadius(radius float32) {
	tmp_radius := float64(radius)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_radius)),
	}
	gdextension.CallMethodBindPtrCall(sphereShape3DMethodSetRadius(), self.Ptr(), args[:], nil)
}

// GetRadius mirrors the Godot SphereShape3D.get_radius method.
func (self *SphereShape3D) GetRadius() float32 {
	var raw float64
	gdextension.CallMethodBindPtrCall(sphereShape3DMethodGetRadius(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}
