// Code generated by godot-go-bindgen. DO NOT EDIT.

package core

import (
	"github.com/legendary-code/godot-go/internal/gdextension"
)

// StandardMaterial3D mirrors the Godot engine class StandardMaterial3D.
type StandardMaterial3D struct {
	BaseMaterial3D
}

// StandardMaterial3DFromPtr wraps an existing host-allocated GDExtensionObjectPtr in a
// *StandardMaterial3D. Returns nil on a nil input.
func StandardMaterial3DFromPtr(p gdextension.ObjectPtr) *StandardMaterial3D {
	if p == nil {
		return nil
	}
	ret := &StandardMaterial3D{}
	ret.BindPtr(p)
	return ret
}
