// Code generated by godot-go-bindgen. DO NOT EDIT.

package core

import (
	"runtime"
	"sync"
	"unsafe"

	"github.com/legendary-code/godot-go/gdextension"
	"github.com/legendary-code/godot-go/variant"
)

// StreamPeerTCP mirrors the Godot engine class StreamPeerTCP.
type StreamPeerTCP struct {
	StreamPeerSocket
}

// StreamPeerTCPFromPtr wraps an existing host-allocated GDExtensionObjectPtr in a
// *StreamPeerTCP. Returns nil on a nil input. StreamPeerTCP descends from RefCounted, so the
// returned wrapper carries a Go finalizer that drops one engine
// reference (via Unreference, dispatched on the main thread) when
// Go's GC determines the wrapper is unreachable. Users who want
// deterministic free can call ret.Unreference() directly — the
// finalizer is harmless after the refcount hits zero.
func StreamPeerTCPFromPtr(p gdextension.ObjectPtr) *StreamPeerTCP {
	if p == nil {
		return nil
	}
	ret := &StreamPeerTCP{}
	ret.BindPtr(p)
	runtime.SetFinalizer(ret, func(r *StreamPeerTCP) {
		gdextension.RunOnMain(func() { r.Unreference() })
	})
	return ret
}

var (
	streamPeerTCPMethodBind = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("StreamPeerTCP"),
			gdextension.InternStringName("bind"),
			3167955072,
		)
	})
	streamPeerTCPMethodConnectToHost = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("StreamPeerTCP"),
			gdextension.InternStringName("connect_to_host"),
			993915709,
		)
	})
	streamPeerTCPMethodGetConnectedHost = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("StreamPeerTCP"),
			gdextension.InternStringName("get_connected_host"),
			201670096,
		)
	})
	streamPeerTCPMethodGetConnectedPort = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("StreamPeerTCP"),
			gdextension.InternStringName("get_connected_port"),
			3905245786,
		)
	})
	streamPeerTCPMethodGetLocalPort = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("StreamPeerTCP"),
			gdextension.InternStringName("get_local_port"),
			3905245786,
		)
	})
	streamPeerTCPMethodSetNoDelay = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("StreamPeerTCP"),
			gdextension.InternStringName("set_no_delay"),
			2586408642,
		)
	})
)

// Bind mirrors the Godot StreamPeerTCP.bind method.
func (self *StreamPeerTCP) Bind(port int64, host string) int64 {
	var ret int64
	tmp_host := variant.NewStringFromString(host)
	defer tmp_host.Destroy()

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&port)),
		gdextension.TypePtr(unsafe.Pointer(&tmp_host)),
	}
	gdextension.CallMethodBindPtrCall(streamPeerTCPMethodBind(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// ConnectToHost mirrors the Godot StreamPeerTCP.connect_to_host method.
func (self *StreamPeerTCP) ConnectToHost(host string, port int64) int64 {
	var ret int64
	tmp_host := variant.NewStringFromString(host)
	defer tmp_host.Destroy()

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_host)),
		gdextension.TypePtr(unsafe.Pointer(&port)),
	}
	gdextension.CallMethodBindPtrCall(streamPeerTCPMethodConnectToHost(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// GetConnectedHost mirrors the Godot StreamPeerTCP.get_connected_host method.
func (self *StreamPeerTCP) GetConnectedHost() string {
	var raw variant.String
	defer raw.Destroy()
	gdextension.CallMethodBindPtrCall(streamPeerTCPMethodGetConnectedHost(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return variant.StringToGo(&raw)
}

// GetConnectedPort mirrors the Godot StreamPeerTCP.get_connected_port method.
func (self *StreamPeerTCP) GetConnectedPort() int64 {
	var ret int64
	gdextension.CallMethodBindPtrCall(streamPeerTCPMethodGetConnectedPort(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// GetLocalPort mirrors the Godot StreamPeerTCP.get_local_port method.
func (self *StreamPeerTCP) GetLocalPort() int64 {
	var ret int64
	gdextension.CallMethodBindPtrCall(streamPeerTCPMethodGetLocalPort(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetNoDelay mirrors the Godot StreamPeerTCP.set_no_delay method.
func (self *StreamPeerTCP) SetNoDelay(enabled bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&enabled)),
	}
	gdextension.CallMethodBindPtrCall(streamPeerTCPMethodSetNoDelay(), self.Ptr(), args[:], nil)
}
