// Code generated by godot-go-bindgen. DO NOT EDIT.

package core

import (
	"runtime"
	"sync"
	"unsafe"

	"github.com/legendary-code/godot-go/internal/gdextension"
	"github.com/legendary-code/godot-go/variant"
)

// TextMesh mirrors the Godot engine class TextMesh.
type TextMesh struct {
	PrimitiveMesh
}

// TextMeshFromPtr wraps an existing host-allocated GDExtensionObjectPtr in a
// *TextMesh. Returns nil on a nil input. TextMesh descends from RefCounted, so the
// returned wrapper carries a Go finalizer that drops one engine
// reference (via Unreference, dispatched on the main thread) when
// Go's GC determines the wrapper is unreachable. Users who want
// deterministic free can call ret.Unreference() directly — the
// finalizer is harmless after the refcount hits zero.
func TextMeshFromPtr(p gdextension.ObjectPtr) *TextMesh {
	if p == nil {
		return nil
	}
	ret := &TextMesh{}
	ret.BindPtr(p)
	runtime.SetFinalizer(ret, func(r *TextMesh) {
		gdextension.RunOnMain(func() { r.Unreference() })
	})
	return ret
}

var (
	textMeshMethodSetHorizontalAlignment = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("TextMesh"),
			gdextension.InternStringName("set_horizontal_alignment"),
			2312603777,
		)
	})
	textMeshMethodGetHorizontalAlignment = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("TextMesh"),
			gdextension.InternStringName("get_horizontal_alignment"),
			341400642,
		)
	})
	textMeshMethodSetVerticalAlignment = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("TextMesh"),
			gdextension.InternStringName("set_vertical_alignment"),
			1796458609,
		)
	})
	textMeshMethodGetVerticalAlignment = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("TextMesh"),
			gdextension.InternStringName("get_vertical_alignment"),
			3274884059,
		)
	})
	textMeshMethodSetText = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("TextMesh"),
			gdextension.InternStringName("set_text"),
			83702148,
		)
	})
	textMeshMethodGetText = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("TextMesh"),
			gdextension.InternStringName("get_text"),
			201670096,
		)
	})
	textMeshMethodSetFont = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("TextMesh"),
			gdextension.InternStringName("set_font"),
			1262170328,
		)
	})
	textMeshMethodGetFont = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("TextMesh"),
			gdextension.InternStringName("get_font"),
			3229501585,
		)
	})
	textMeshMethodSetFontSize = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("TextMesh"),
			gdextension.InternStringName("set_font_size"),
			1286410249,
		)
	})
	textMeshMethodGetFontSize = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("TextMesh"),
			gdextension.InternStringName("get_font_size"),
			3905245786,
		)
	})
	textMeshMethodSetLineSpacing = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("TextMesh"),
			gdextension.InternStringName("set_line_spacing"),
			373806689,
		)
	})
	textMeshMethodGetLineSpacing = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("TextMesh"),
			gdextension.InternStringName("get_line_spacing"),
			1740695150,
		)
	})
	textMeshMethodSetAutowrapMode = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("TextMesh"),
			gdextension.InternStringName("set_autowrap_mode"),
			3289138044,
		)
	})
	textMeshMethodGetAutowrapMode = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("TextMesh"),
			gdextension.InternStringName("get_autowrap_mode"),
			1549071663,
		)
	})
	textMeshMethodSetJustificationFlags = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("TextMesh"),
			gdextension.InternStringName("set_justification_flags"),
			2877345813,
		)
	})
	textMeshMethodGetJustificationFlags = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("TextMesh"),
			gdextension.InternStringName("get_justification_flags"),
			1583363614,
		)
	})
	textMeshMethodSetDepth = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("TextMesh"),
			gdextension.InternStringName("set_depth"),
			373806689,
		)
	})
	textMeshMethodGetDepth = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("TextMesh"),
			gdextension.InternStringName("get_depth"),
			1740695150,
		)
	})
	textMeshMethodSetWidth = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("TextMesh"),
			gdextension.InternStringName("set_width"),
			373806689,
		)
	})
	textMeshMethodGetWidth = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("TextMesh"),
			gdextension.InternStringName("get_width"),
			1740695150,
		)
	})
	textMeshMethodSetPixelSize = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("TextMesh"),
			gdextension.InternStringName("set_pixel_size"),
			373806689,
		)
	})
	textMeshMethodGetPixelSize = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("TextMesh"),
			gdextension.InternStringName("get_pixel_size"),
			1740695150,
		)
	})
	textMeshMethodSetOffset = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("TextMesh"),
			gdextension.InternStringName("set_offset"),
			743155724,
		)
	})
	textMeshMethodGetOffset = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("TextMesh"),
			gdextension.InternStringName("get_offset"),
			3341600327,
		)
	})
	textMeshMethodSetCurveStep = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("TextMesh"),
			gdextension.InternStringName("set_curve_step"),
			373806689,
		)
	})
	textMeshMethodGetCurveStep = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("TextMesh"),
			gdextension.InternStringName("get_curve_step"),
			1740695150,
		)
	})
	textMeshMethodSetTextDirection = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("TextMesh"),
			gdextension.InternStringName("set_text_direction"),
			1418190634,
		)
	})
	textMeshMethodGetTextDirection = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("TextMesh"),
			gdextension.InternStringName("get_text_direction"),
			2516697328,
		)
	})
	textMeshMethodSetLanguage = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("TextMesh"),
			gdextension.InternStringName("set_language"),
			83702148,
		)
	})
	textMeshMethodGetLanguage = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("TextMesh"),
			gdextension.InternStringName("get_language"),
			201670096,
		)
	})
	textMeshMethodSetStructuredTextBidiOverride = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("TextMesh"),
			gdextension.InternStringName("set_structured_text_bidi_override"),
			55961453,
		)
	})
	textMeshMethodGetStructuredTextBidiOverride = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("TextMesh"),
			gdextension.InternStringName("get_structured_text_bidi_override"),
			3385126229,
		)
	})
	textMeshMethodSetStructuredTextBidiOverrideOptions = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("TextMesh"),
			gdextension.InternStringName("set_structured_text_bidi_override_options"),
			381264803,
		)
	})
	textMeshMethodGetStructuredTextBidiOverrideOptions = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("TextMesh"),
			gdextension.InternStringName("get_structured_text_bidi_override_options"),
			3995934104,
		)
	})
	textMeshMethodSetUppercase = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("TextMesh"),
			gdextension.InternStringName("set_uppercase"),
			2586408642,
		)
	})
	textMeshMethodIsUppercase = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("TextMesh"),
			gdextension.InternStringName("is_uppercase"),
			36873697,
		)
	})
)

// SetHorizontalAlignment mirrors the Godot TextMesh.set_horizontal_alignment method.
func (self *TextMesh) SetHorizontalAlignment(alignment int64) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&alignment)),
	}
	gdextension.CallMethodBindPtrCall(textMeshMethodSetHorizontalAlignment(), self.Ptr(), args[:], nil)
}

// GetHorizontalAlignment mirrors the Godot TextMesh.get_horizontal_alignment method.
func (self *TextMesh) GetHorizontalAlignment() int64 {
	var ret int64
	gdextension.CallMethodBindPtrCall(textMeshMethodGetHorizontalAlignment(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetVerticalAlignment mirrors the Godot TextMesh.set_vertical_alignment method.
func (self *TextMesh) SetVerticalAlignment(alignment int64) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&alignment)),
	}
	gdextension.CallMethodBindPtrCall(textMeshMethodSetVerticalAlignment(), self.Ptr(), args[:], nil)
}

// GetVerticalAlignment mirrors the Godot TextMesh.get_vertical_alignment method.
func (self *TextMesh) GetVerticalAlignment() int64 {
	var ret int64
	gdextension.CallMethodBindPtrCall(textMeshMethodGetVerticalAlignment(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetText mirrors the Godot TextMesh.set_text method.
func (self *TextMesh) SetText(text string) {
	tmp_text := variant.NewStringFromString(text)
	defer tmp_text.Destroy()

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_text)),
	}
	gdextension.CallMethodBindPtrCall(textMeshMethodSetText(), self.Ptr(), args[:], nil)
}

// GetText mirrors the Godot TextMesh.get_text method.
func (self *TextMesh) GetText() string {
	var raw variant.String
	defer raw.Destroy()
	gdextension.CallMethodBindPtrCall(textMeshMethodGetText(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return variant.StringToGo(&raw)
}

// SetFont mirrors the Godot TextMesh.set_font method.
func (self *TextMesh) SetFont(font *Font) {
	var tmp_font gdextension.ObjectPtr
	if font != nil {
		tmp_font = font.Ptr()
	}

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_font)),
	}
	gdextension.CallMethodBindPtrCall(textMeshMethodSetFont(), self.Ptr(), args[:], nil)
}

// GetFont mirrors the Godot TextMesh.get_font method.
func (self *TextMesh) GetFont() *Font {
	var ret gdextension.ObjectPtr
	gdextension.CallMethodBindPtrCall(textMeshMethodGetFont(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return FontFromPtr(ret)
}

// SetFontSize mirrors the Godot TextMesh.set_font_size method.
func (self *TextMesh) SetFontSize(font_size int64) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&font_size)),
	}
	gdextension.CallMethodBindPtrCall(textMeshMethodSetFontSize(), self.Ptr(), args[:], nil)
}

// GetFontSize mirrors the Godot TextMesh.get_font_size method.
func (self *TextMesh) GetFontSize() int64 {
	var ret int64
	gdextension.CallMethodBindPtrCall(textMeshMethodGetFontSize(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetLineSpacing mirrors the Godot TextMesh.set_line_spacing method.
func (self *TextMesh) SetLineSpacing(line_spacing float32) {
	tmp_line_spacing := float64(line_spacing)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_line_spacing)),
	}
	gdextension.CallMethodBindPtrCall(textMeshMethodSetLineSpacing(), self.Ptr(), args[:], nil)
}

// GetLineSpacing mirrors the Godot TextMesh.get_line_spacing method.
func (self *TextMesh) GetLineSpacing() float32 {
	var raw float64
	gdextension.CallMethodBindPtrCall(textMeshMethodGetLineSpacing(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}

// SetAutowrapMode mirrors the Godot TextMesh.set_autowrap_mode method.
func (self *TextMesh) SetAutowrapMode(autowrap_mode TextServerAutowrapMode) {
	tmp_autowrap_mode := int64(autowrap_mode)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_autowrap_mode)),
	}
	gdextension.CallMethodBindPtrCall(textMeshMethodSetAutowrapMode(), self.Ptr(), args[:], nil)
}

// GetAutowrapMode mirrors the Godot TextMesh.get_autowrap_mode method.
func (self *TextMesh) GetAutowrapMode() TextServerAutowrapMode {
	var ret int64
	gdextension.CallMethodBindPtrCall(textMeshMethodGetAutowrapMode(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return TextServerAutowrapMode(ret)
}

// SetJustificationFlags mirrors the Godot TextMesh.set_justification_flags method.
func (self *TextMesh) SetJustificationFlags(justification_flags TextServerJustificationFlag) {
	tmp_justification_flags := int64(justification_flags)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_justification_flags)),
	}
	gdextension.CallMethodBindPtrCall(textMeshMethodSetJustificationFlags(), self.Ptr(), args[:], nil)
}

// GetJustificationFlags mirrors the Godot TextMesh.get_justification_flags method.
func (self *TextMesh) GetJustificationFlags() TextServerJustificationFlag {
	var ret int64
	gdextension.CallMethodBindPtrCall(textMeshMethodGetJustificationFlags(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return TextServerJustificationFlag(ret)
}

// SetDepth mirrors the Godot TextMesh.set_depth method.
func (self *TextMesh) SetDepth(depth float32) {
	tmp_depth := float64(depth)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_depth)),
	}
	gdextension.CallMethodBindPtrCall(textMeshMethodSetDepth(), self.Ptr(), args[:], nil)
}

// GetDepth mirrors the Godot TextMesh.get_depth method.
func (self *TextMesh) GetDepth() float32 {
	var raw float64
	gdextension.CallMethodBindPtrCall(textMeshMethodGetDepth(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}

// SetWidth mirrors the Godot TextMesh.set_width method.
func (self *TextMesh) SetWidth(width float32) {
	tmp_width := float64(width)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_width)),
	}
	gdextension.CallMethodBindPtrCall(textMeshMethodSetWidth(), self.Ptr(), args[:], nil)
}

// GetWidth mirrors the Godot TextMesh.get_width method.
func (self *TextMesh) GetWidth() float32 {
	var raw float64
	gdextension.CallMethodBindPtrCall(textMeshMethodGetWidth(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}

// SetPixelSize mirrors the Godot TextMesh.set_pixel_size method.
func (self *TextMesh) SetPixelSize(pixel_size float32) {
	tmp_pixel_size := float64(pixel_size)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_pixel_size)),
	}
	gdextension.CallMethodBindPtrCall(textMeshMethodSetPixelSize(), self.Ptr(), args[:], nil)
}

// GetPixelSize mirrors the Godot TextMesh.get_pixel_size method.
func (self *TextMesh) GetPixelSize() float32 {
	var raw float64
	gdextension.CallMethodBindPtrCall(textMeshMethodGetPixelSize(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}

// SetOffset mirrors the Godot TextMesh.set_offset method.
func (self *TextMesh) SetOffset(offset variant.Vector2) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&offset)),
	}
	gdextension.CallMethodBindPtrCall(textMeshMethodSetOffset(), self.Ptr(), args[:], nil)
}

// GetOffset mirrors the Godot TextMesh.get_offset method.
func (self *TextMesh) GetOffset() variant.Vector2 {
	var ret variant.Vector2
	gdextension.CallMethodBindPtrCall(textMeshMethodGetOffset(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetCurveStep mirrors the Godot TextMesh.set_curve_step method.
func (self *TextMesh) SetCurveStep(curve_step float32) {
	tmp_curve_step := float64(curve_step)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_curve_step)),
	}
	gdextension.CallMethodBindPtrCall(textMeshMethodSetCurveStep(), self.Ptr(), args[:], nil)
}

// GetCurveStep mirrors the Godot TextMesh.get_curve_step method.
func (self *TextMesh) GetCurveStep() float32 {
	var raw float64
	gdextension.CallMethodBindPtrCall(textMeshMethodGetCurveStep(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return float32(raw)
}

// SetTextDirection mirrors the Godot TextMesh.set_text_direction method.
func (self *TextMesh) SetTextDirection(direction TextServerDirection) {
	tmp_direction := int64(direction)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_direction)),
	}
	gdextension.CallMethodBindPtrCall(textMeshMethodSetTextDirection(), self.Ptr(), args[:], nil)
}

// GetTextDirection mirrors the Godot TextMesh.get_text_direction method.
func (self *TextMesh) GetTextDirection() TextServerDirection {
	var ret int64
	gdextension.CallMethodBindPtrCall(textMeshMethodGetTextDirection(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return TextServerDirection(ret)
}

// SetLanguage mirrors the Godot TextMesh.set_language method.
func (self *TextMesh) SetLanguage(language string) {
	tmp_language := variant.NewStringFromString(language)
	defer tmp_language.Destroy()

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_language)),
	}
	gdextension.CallMethodBindPtrCall(textMeshMethodSetLanguage(), self.Ptr(), args[:], nil)
}

// GetLanguage mirrors the Godot TextMesh.get_language method.
func (self *TextMesh) GetLanguage() string {
	var raw variant.String
	defer raw.Destroy()
	gdextension.CallMethodBindPtrCall(textMeshMethodGetLanguage(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return variant.StringToGo(&raw)
}

// SetStructuredTextBidiOverride mirrors the Godot TextMesh.set_structured_text_bidi_override method.
func (self *TextMesh) SetStructuredTextBidiOverride(parser TextServerStructuredTextParser) {
	tmp_parser := int64(parser)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_parser)),
	}
	gdextension.CallMethodBindPtrCall(textMeshMethodSetStructuredTextBidiOverride(), self.Ptr(), args[:], nil)
}

// GetStructuredTextBidiOverride mirrors the Godot TextMesh.get_structured_text_bidi_override method.
func (self *TextMesh) GetStructuredTextBidiOverride() TextServerStructuredTextParser {
	var ret int64
	gdextension.CallMethodBindPtrCall(textMeshMethodGetStructuredTextBidiOverride(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return TextServerStructuredTextParser(ret)
}

// SetStructuredTextBidiOverrideOptions mirrors the Godot TextMesh.set_structured_text_bidi_override_options method.
func (self *TextMesh) SetStructuredTextBidiOverrideOptions(a variant.Array) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&a)),
	}
	gdextension.CallMethodBindPtrCall(textMeshMethodSetStructuredTextBidiOverrideOptions(), self.Ptr(), args[:], nil)
}

// GetStructuredTextBidiOverrideOptions mirrors the Godot TextMesh.get_structured_text_bidi_override_options method.
func (self *TextMesh) GetStructuredTextBidiOverrideOptions() variant.Array {
	var ret variant.Array
	gdextension.CallMethodBindPtrCall(textMeshMethodGetStructuredTextBidiOverrideOptions(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetUppercase mirrors the Godot TextMesh.set_uppercase method.
func (self *TextMesh) SetUppercase(enable bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&enable)),
	}
	gdextension.CallMethodBindPtrCall(textMeshMethodSetUppercase(), self.Ptr(), args[:], nil)
}

// IsUppercase mirrors the Godot TextMesh.is_uppercase method.
func (self *TextMesh) IsUppercase() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(textMeshMethodIsUppercase(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}
