// Code generated by godot-go-bindgen. DO NOT EDIT.

package core

import (
	"sync"
	"unsafe"

	"github.com/legendary-code/godot-go/gdextension"
	"github.com/legendary-code/godot-go/variant"
)

// TextServerManager mirrors the Godot engine class TextServerManager.
type TextServerManager struct {
	Object
}

// TextServerManagerFromPtr wraps an existing host-allocated GDExtensionObjectPtr in a
// *TextServerManager. Returns nil on a nil input.
func TextServerManagerFromPtr(p gdextension.ObjectPtr) *TextServerManager {
	if p == nil {
		return nil
	}
	ret := &TextServerManager{}
	ret.BindPtr(p)
	return ret
}

var (
	textServerManagerMethodAddInterface = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("TextServerManager"),
			gdextension.InternStringName("add_interface"),
			1799689403,
		)
	})
	textServerManagerMethodGetInterfaceCount = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("TextServerManager"),
			gdextension.InternStringName("get_interface_count"),
			3905245786,
		)
	})
	textServerManagerMethodRemoveInterface = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("TextServerManager"),
			gdextension.InternStringName("remove_interface"),
			1799689403,
		)
	})
	textServerManagerMethodGetInterface = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("TextServerManager"),
			gdextension.InternStringName("get_interface"),
			1672475555,
		)
	})
	textServerManagerMethodGetInterfaces = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("TextServerManager"),
			gdextension.InternStringName("get_interfaces"),
			3995934104,
		)
	})
	textServerManagerMethodFindInterface = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("TextServerManager"),
			gdextension.InternStringName("find_interface"),
			2240905781,
		)
	})
	textServerManagerMethodSetPrimaryInterface = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("TextServerManager"),
			gdextension.InternStringName("set_primary_interface"),
			1799689403,
		)
	})
	textServerManagerMethodGetPrimaryInterface = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("TextServerManager"),
			gdextension.InternStringName("get_primary_interface"),
			905850878,
		)
	})
)

// TextServerManagerSingleton returns the global TextServerManager singleton registered under "TextServerManager".
// The host owns the lifetime; do not call any destructor on it.
var TextServerManagerSingleton = sync.OnceValue(func() *TextServerManager {
	return TextServerManagerFromPtr(gdextension.GetSingleton(gdextension.InternStringName("TextServerManager")))
})

// AddInterface mirrors the Godot TextServerManager.add_interface method.
func (self *TextServerManager) AddInterface(iface *TextServer) {
	var tmp_iface gdextension.ObjectPtr
	if iface != nil {
		tmp_iface = iface.Ptr()
	}

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_iface)),
	}
	gdextension.CallMethodBindPtrCall(textServerManagerMethodAddInterface(), self.Ptr(), args[:], nil)
}

// GetInterfaceCount mirrors the Godot TextServerManager.get_interface_count method.
func (self *TextServerManager) GetInterfaceCount() int64 {
	var ret int64
	gdextension.CallMethodBindPtrCall(textServerManagerMethodGetInterfaceCount(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// RemoveInterface mirrors the Godot TextServerManager.remove_interface method.
func (self *TextServerManager) RemoveInterface(iface *TextServer) {
	var tmp_iface gdextension.ObjectPtr
	if iface != nil {
		tmp_iface = iface.Ptr()
	}

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_iface)),
	}
	gdextension.CallMethodBindPtrCall(textServerManagerMethodRemoveInterface(), self.Ptr(), args[:], nil)
}

// GetInterface mirrors the Godot TextServerManager.get_interface method.
func (self *TextServerManager) GetInterface(idx int64) *TextServer {
	var ret gdextension.ObjectPtr
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&idx)),
	}
	gdextension.CallMethodBindPtrCall(textServerManagerMethodGetInterface(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return TextServerFromPtr(ret)
}

// GetInterfaces mirrors the Godot TextServerManager.get_interfaces method.
func (self *TextServerManager) GetInterfaces() variant.Array {
	var ret variant.Array
	gdextension.CallMethodBindPtrCall(textServerManagerMethodGetInterfaces(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// FindInterface mirrors the Godot TextServerManager.find_interface method.
func (self *TextServerManager) FindInterface(name string) *TextServer {
	var ret gdextension.ObjectPtr
	tmp_name := variant.NewStringFromString(name)
	defer tmp_name.Destroy()

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_name)),
	}
	gdextension.CallMethodBindPtrCall(textServerManagerMethodFindInterface(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return TextServerFromPtr(ret)
}

// SetPrimaryInterface mirrors the Godot TextServerManager.set_primary_interface method.
func (self *TextServerManager) SetPrimaryInterface(index *TextServer) {
	var tmp_index gdextension.ObjectPtr
	if index != nil {
		tmp_index = index.Ptr()
	}

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_index)),
	}
	gdextension.CallMethodBindPtrCall(textServerManagerMethodSetPrimaryInterface(), self.Ptr(), args[:], nil)
}

// GetPrimaryInterface mirrors the Godot TextServerManager.get_primary_interface method.
func (self *TextServerManager) GetPrimaryInterface() *TextServer {
	var ret gdextension.ObjectPtr
	gdextension.CallMethodBindPtrCall(textServerManagerMethodGetPrimaryInterface(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return TextServerFromPtr(ret)
}
