// Code generated by godot-go-bindgen. DO NOT EDIT.

package core

import (
	"sync"
	"unsafe"

	"github.com/legendary-code/godot-go/internal/gdextension"
	"github.com/legendary-code/godot-go/variant"
)

// Thread mirrors the Godot engine class Thread.
type Thread struct {
	RefCounted
}

// ThreadFromPtr wraps an existing host-allocated GDExtensionObjectPtr in a
// *Thread. Returns nil on a nil input.
func ThreadFromPtr(p gdextension.ObjectPtr) *Thread {
	if p == nil {
		return nil
	}
	ret := &Thread{}
	ret.BindPtr(p)
	return ret
}

// ThreadPriority is the Godot ThreadPriority enum.
type ThreadPriority int64

const (
	Thread_PRIORITY_LOW    ThreadPriority = 0
	Thread_PRIORITY_NORMAL ThreadPriority = 1
	Thread_PRIORITY_HIGH   ThreadPriority = 2
)

var (
	threadMethodStart = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("Thread"),
			gdextension.InternStringName("start"),
			1327203254,
		)
	})
	threadMethodGetId = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("Thread"),
			gdextension.InternStringName("get_id"),
			201670096,
		)
	})
	threadMethodIsStarted = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("Thread"),
			gdextension.InternStringName("is_started"),
			36873697,
		)
	})
	threadMethodIsAlive = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("Thread"),
			gdextension.InternStringName("is_alive"),
			36873697,
		)
	})
	threadMethodWaitToFinish = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("Thread"),
			gdextension.InternStringName("wait_to_finish"),
			1460262497,
		)
	})
	threadMethodSetThreadSafetyChecksEnabled = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("Thread"),
			gdextension.InternStringName("set_thread_safety_checks_enabled"),
			2586408642,
		)
	})
	threadMethodIsMainThread = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("Thread"),
			gdextension.InternStringName("is_main_thread"),
			2240911060,
		)
	})
)

// Start mirrors the Godot Thread.start method.
func (self *Thread) Start(callable variant.Callable, priority ThreadPriority) int64 {
	var ret int64
	tmp_priority := int64(priority)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&callable)),
		gdextension.TypePtr(unsafe.Pointer(&tmp_priority)),
	}
	gdextension.CallMethodBindPtrCall(threadMethodStart(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// GetId mirrors the Godot Thread.get_id method.
func (self *Thread) GetId() string {
	var raw variant.String
	defer raw.Destroy()
	gdextension.CallMethodBindPtrCall(threadMethodGetId(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return variant.StringToGo(&raw)
}

// IsStarted mirrors the Godot Thread.is_started method.
func (self *Thread) IsStarted() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(threadMethodIsStarted(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// IsAlive mirrors the Godot Thread.is_alive method.
func (self *Thread) IsAlive() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(threadMethodIsAlive(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// WaitToFinish mirrors the Godot Thread.wait_to_finish method.
func (self *Thread) WaitToFinish() variant.Variant {
	var ret variant.Variant
	gdextension.CallMethodBindPtrCall(threadMethodWaitToFinish(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetThreadSafetyChecksEnabled mirrors the Godot Thread.set_thread_safety_checks_enabled method.
func ThreadSetThreadSafetyChecksEnabled(enabled bool) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&enabled)),
	}
	gdextension.CallMethodBindPtrCall(threadMethodSetThreadSafetyChecksEnabled(), nil, args[:], nil)
}

// IsMainThread mirrors the Godot Thread.is_main_thread method.
func ThreadIsMainThread() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(threadMethodIsMainThread(), nil, nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}
