// Code generated by godot-go-bindgen. DO NOT EDIT.

package core

import (
	"github.com/legendary-code/godot-go/internal/gdextension"
)

// VideoStreamTheora mirrors the Godot engine class VideoStreamTheora.
type VideoStreamTheora struct {
	VideoStream
}

// VideoStreamTheoraFromPtr wraps an existing host-allocated GDExtensionObjectPtr in a
// *VideoStreamTheora. Returns nil on a nil input.
func VideoStreamTheoraFromPtr(p gdextension.ObjectPtr) *VideoStreamTheora {
	if p == nil {
		return nil
	}
	ret := &VideoStreamTheora{}
	ret.BindPtr(p)
	return ret
}
