// Code generated by godot-go-bindgen. DO NOT EDIT.

package core

import (
	"github.com/legendary-code/godot-go/internal/gdextension"
)

// VisualShaderNodeTextureSDFNormal mirrors the Godot engine class VisualShaderNodeTextureSDFNormal.
type VisualShaderNodeTextureSDFNormal struct {
	VisualShaderNode
}

// VisualShaderNodeTextureSDFNormalFromPtr wraps an existing host-allocated GDExtensionObjectPtr in a
// *VisualShaderNodeTextureSDFNormal. Returns nil on a nil input.
func VisualShaderNodeTextureSDFNormalFromPtr(p gdextension.ObjectPtr) *VisualShaderNodeTextureSDFNormal {
	if p == nil {
		return nil
	}
	ret := &VisualShaderNodeTextureSDFNormal{}
	ret.BindPtr(p)
	return ret
}
