// Code generated by godot-go-bindgen. DO NOT EDIT.

package core

import (
	"runtime"

	"github.com/legendary-code/godot-go/gdextension"
)

// VisualShaderNodeConstant mirrors the Godot engine class VisualShaderNodeConstant.
type VisualShaderNodeConstant struct {
	VisualShaderNode
}

// VisualShaderNodeConstantFromPtr wraps an existing host-allocated GDExtensionObjectPtr in a
// *VisualShaderNodeConstant. Returns nil on a nil input. VisualShaderNodeConstant descends from RefCounted, so the
// returned wrapper carries a Go finalizer that drops one engine
// reference (via Unreference, dispatched on the main thread) when
// Go's GC determines the wrapper is unreachable. Users who want
// deterministic free can call ret.Unreference() directly — the
// finalizer is harmless after the refcount hits zero.
func VisualShaderNodeConstantFromPtr(p gdextension.ObjectPtr) *VisualShaderNodeConstant {
	if p == nil {
		return nil
	}
	ret := &VisualShaderNodeConstant{}
	ret.BindPtr(p)
	runtime.SetFinalizer(ret, func(r *VisualShaderNodeConstant) {
		gdextension.RunOnMain(func() { r.Unreference() })
	})
	return ret
}
