// Code generated by godot-go-bindgen. DO NOT EDIT.

package core

import (
	"sync"
	"unsafe"

	"github.com/legendary-code/godot-go/internal/gdextension"
	"github.com/legendary-code/godot-go/variant"
)

// WebRTCDataChannel mirrors the Godot engine class WebRTCDataChannel.
type WebRTCDataChannel struct {
	PacketPeer
}

// WebRTCDataChannelFromPtr wraps an existing host-allocated GDExtensionObjectPtr in a
// *WebRTCDataChannel. Returns nil on a nil input.
func WebRTCDataChannelFromPtr(p gdextension.ObjectPtr) *WebRTCDataChannel {
	if p == nil {
		return nil
	}
	ret := &WebRTCDataChannel{}
	ret.BindPtr(p)
	return ret
}

// WebRTCDataChannelWriteMode is the Godot WebRTCDataChannelWriteMode enum.
type WebRTCDataChannelWriteMode int64

const (
	WebRTCDataChannel_WRITE_MODE_TEXT   WebRTCDataChannelWriteMode = 0
	WebRTCDataChannel_WRITE_MODE_BINARY WebRTCDataChannelWriteMode = 1
)

// WebRTCDataChannelChannelState is the Godot WebRTCDataChannelChannelState enum.
type WebRTCDataChannelChannelState int64

const (
	WebRTCDataChannel_STATE_CONNECTING WebRTCDataChannelChannelState = 0
	WebRTCDataChannel_STATE_OPEN       WebRTCDataChannelChannelState = 1
	WebRTCDataChannel_STATE_CLOSING    WebRTCDataChannelChannelState = 2
	WebRTCDataChannel_STATE_CLOSED     WebRTCDataChannelChannelState = 3
)

var (
	webRTCDataChannelMethodPoll = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("WebRTCDataChannel"),
			gdextension.InternStringName("poll"),
			166280745,
		)
	})
	webRTCDataChannelMethodClose = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("WebRTCDataChannel"),
			gdextension.InternStringName("close"),
			3218959716,
		)
	})
	webRTCDataChannelMethodWasStringPacket = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("WebRTCDataChannel"),
			gdextension.InternStringName("was_string_packet"),
			36873697,
		)
	})
	webRTCDataChannelMethodSetWriteMode = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("WebRTCDataChannel"),
			gdextension.InternStringName("set_write_mode"),
			1999768052,
		)
	})
	webRTCDataChannelMethodGetWriteMode = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("WebRTCDataChannel"),
			gdextension.InternStringName("get_write_mode"),
			2848495172,
		)
	})
	webRTCDataChannelMethodGetReadyState = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("WebRTCDataChannel"),
			gdextension.InternStringName("get_ready_state"),
			3501143017,
		)
	})
	webRTCDataChannelMethodGetLabel = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("WebRTCDataChannel"),
			gdextension.InternStringName("get_label"),
			201670096,
		)
	})
	webRTCDataChannelMethodIsOrdered = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("WebRTCDataChannel"),
			gdextension.InternStringName("is_ordered"),
			36873697,
		)
	})
	webRTCDataChannelMethodGetId = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("WebRTCDataChannel"),
			gdextension.InternStringName("get_id"),
			3905245786,
		)
	})
	webRTCDataChannelMethodGetMaxPacketLifeTime = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("WebRTCDataChannel"),
			gdextension.InternStringName("get_max_packet_life_time"),
			3905245786,
		)
	})
	webRTCDataChannelMethodGetMaxRetransmits = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("WebRTCDataChannel"),
			gdextension.InternStringName("get_max_retransmits"),
			3905245786,
		)
	})
	webRTCDataChannelMethodGetProtocol = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("WebRTCDataChannel"),
			gdextension.InternStringName("get_protocol"),
			201670096,
		)
	})
	webRTCDataChannelMethodIsNegotiated = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("WebRTCDataChannel"),
			gdextension.InternStringName("is_negotiated"),
			36873697,
		)
	})
	webRTCDataChannelMethodGetBufferedAmount = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("WebRTCDataChannel"),
			gdextension.InternStringName("get_buffered_amount"),
			3905245786,
		)
	})
)

// Poll mirrors the Godot WebRTCDataChannel.poll method.
func (self *WebRTCDataChannel) Poll() int64 {
	var ret int64
	gdextension.CallMethodBindPtrCall(webRTCDataChannelMethodPoll(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// Close mirrors the Godot WebRTCDataChannel.close method.
func (self *WebRTCDataChannel) Close() {
	gdextension.CallMethodBindPtrCall(webRTCDataChannelMethodClose(), self.Ptr(), nil, nil)
}

// WasStringPacket mirrors the Godot WebRTCDataChannel.was_string_packet method.
func (self *WebRTCDataChannel) WasStringPacket() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(webRTCDataChannelMethodWasStringPacket(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetWriteMode mirrors the Godot WebRTCDataChannel.set_write_mode method.
func (self *WebRTCDataChannel) SetWriteMode(write_mode WebRTCDataChannelWriteMode) {
	tmp_write_mode := int64(write_mode)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_write_mode)),
	}
	gdextension.CallMethodBindPtrCall(webRTCDataChannelMethodSetWriteMode(), self.Ptr(), args[:], nil)
}

// GetWriteMode mirrors the Godot WebRTCDataChannel.get_write_mode method.
func (self *WebRTCDataChannel) GetWriteMode() WebRTCDataChannelWriteMode {
	var ret int64
	gdextension.CallMethodBindPtrCall(webRTCDataChannelMethodGetWriteMode(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return WebRTCDataChannelWriteMode(ret)
}

// GetReadyState mirrors the Godot WebRTCDataChannel.get_ready_state method.
func (self *WebRTCDataChannel) GetReadyState() WebRTCDataChannelChannelState {
	var ret int64
	gdextension.CallMethodBindPtrCall(webRTCDataChannelMethodGetReadyState(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return WebRTCDataChannelChannelState(ret)
}

// GetLabel mirrors the Godot WebRTCDataChannel.get_label method.
func (self *WebRTCDataChannel) GetLabel() string {
	var raw variant.String
	defer raw.Destroy()
	gdextension.CallMethodBindPtrCall(webRTCDataChannelMethodGetLabel(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return variant.StringToGo(&raw)
}

// IsOrdered mirrors the Godot WebRTCDataChannel.is_ordered method.
func (self *WebRTCDataChannel) IsOrdered() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(webRTCDataChannelMethodIsOrdered(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// GetId mirrors the Godot WebRTCDataChannel.get_id method.
func (self *WebRTCDataChannel) GetId() int64 {
	var ret int64
	gdextension.CallMethodBindPtrCall(webRTCDataChannelMethodGetId(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// GetMaxPacketLifeTime mirrors the Godot WebRTCDataChannel.get_max_packet_life_time method.
func (self *WebRTCDataChannel) GetMaxPacketLifeTime() int64 {
	var ret int64
	gdextension.CallMethodBindPtrCall(webRTCDataChannelMethodGetMaxPacketLifeTime(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// GetMaxRetransmits mirrors the Godot WebRTCDataChannel.get_max_retransmits method.
func (self *WebRTCDataChannel) GetMaxRetransmits() int64 {
	var ret int64
	gdextension.CallMethodBindPtrCall(webRTCDataChannelMethodGetMaxRetransmits(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// GetProtocol mirrors the Godot WebRTCDataChannel.get_protocol method.
func (self *WebRTCDataChannel) GetProtocol() string {
	var raw variant.String
	defer raw.Destroy()
	gdextension.CallMethodBindPtrCall(webRTCDataChannelMethodGetProtocol(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&raw)))
	return variant.StringToGo(&raw)
}

// IsNegotiated mirrors the Godot WebRTCDataChannel.is_negotiated method.
func (self *WebRTCDataChannel) IsNegotiated() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(webRTCDataChannelMethodIsNegotiated(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// GetBufferedAmount mirrors the Godot WebRTCDataChannel.get_buffered_amount method.
func (self *WebRTCDataChannel) GetBufferedAmount() int64 {
	var ret int64
	gdextension.CallMethodBindPtrCall(webRTCDataChannelMethodGetBufferedAmount(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}
