// Code generated by godot-go-bindgen. DO NOT EDIT.

package core

import (
	"runtime"
	"sync"
	"unsafe"

	"github.com/legendary-code/godot-go/internal/gdextension"
	"github.com/legendary-code/godot-go/variant"
)

// World2D mirrors the Godot engine class World2D.
type World2D struct {
	Resource
}

// World2DFromPtr wraps an existing host-allocated GDExtensionObjectPtr in a
// *World2D. Returns nil on a nil input. World2D descends from RefCounted, so the
// returned wrapper carries a Go finalizer that drops one engine
// reference (via Unreference, dispatched on the main thread) when
// Go's GC determines the wrapper is unreachable. Users who want
// deterministic free can call ret.Unreference() directly — the
// finalizer is harmless after the refcount hits zero.
func World2DFromPtr(p gdextension.ObjectPtr) *World2D {
	if p == nil {
		return nil
	}
	ret := &World2D{}
	ret.BindPtr(p)
	runtime.SetFinalizer(ret, func(r *World2D) {
		gdextension.RunOnMain(func() { r.Unreference() })
	})
	return ret
}

var (
	world2DMethodGetCanvas = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("World2D"),
			gdextension.InternStringName("get_canvas"),
			2944877500,
		)
	})
	world2DMethodGetNavigationMap = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("World2D"),
			gdextension.InternStringName("get_navigation_map"),
			2944877500,
		)
	})
	world2DMethodGetSpace = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("World2D"),
			gdextension.InternStringName("get_space"),
			2944877500,
		)
	})
	world2DMethodGetDirectSpaceState = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("World2D"),
			gdextension.InternStringName("get_direct_space_state"),
			2506717822,
		)
	})
)

// GetCanvas mirrors the Godot World2D.get_canvas method.
func (self *World2D) GetCanvas() variant.RID {
	var ret variant.RID
	gdextension.CallMethodBindPtrCall(world2DMethodGetCanvas(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// GetNavigationMap mirrors the Godot World2D.get_navigation_map method.
func (self *World2D) GetNavigationMap() variant.RID {
	var ret variant.RID
	gdextension.CallMethodBindPtrCall(world2DMethodGetNavigationMap(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// GetSpace mirrors the Godot World2D.get_space method.
func (self *World2D) GetSpace() variant.RID {
	var ret variant.RID
	gdextension.CallMethodBindPtrCall(world2DMethodGetSpace(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// GetDirectSpaceState mirrors the Godot World2D.get_direct_space_state method.
func (self *World2D) GetDirectSpaceState() *PhysicsDirectSpaceState2D {
	var ret gdextension.ObjectPtr
	gdextension.CallMethodBindPtrCall(world2DMethodGetDirectSpaceState(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return PhysicsDirectSpaceState2DFromPtr(ret)
}
