// Code generated by godot-go-bindgen. DO NOT EDIT.

package editor

import (
	"github.com/legendary-code/godot-go/internal/gdextension"
)

// EditorExportPlatformIOS mirrors the Godot engine class EditorExportPlatformIOS.
type EditorExportPlatformIOS struct {
	EditorExportPlatformAppleEmbedded
}

// EditorExportPlatformIOSFromPtr wraps an existing host-allocated GDExtensionObjectPtr in a
// *EditorExportPlatformIOS. Returns nil on a nil input.
func EditorExportPlatformIOSFromPtr(p gdextension.ObjectPtr) *EditorExportPlatformIOS {
	if p == nil {
		return nil
	}
	ret := &EditorExportPlatformIOS{}
	ret.BindPtr(p)
	return ret
}
