// Code generated by godot-go-bindgen. DO NOT EDIT.

package editor

import (
	"sync"
	"unsafe"

	"github.com/legendary-code/godot-go/core"
	"github.com/legendary-code/godot-go/internal/gdextension"
	"github.com/legendary-code/godot-go/variant"
)

// EditorVCSInterface mirrors the Godot engine class EditorVCSInterface.
type EditorVCSInterface struct {
	core.Object
}

// EditorVCSInterfaceFromPtr wraps an existing host-allocated GDExtensionObjectPtr in a
// *EditorVCSInterface. Returns nil on a nil input.
func EditorVCSInterfaceFromPtr(p gdextension.ObjectPtr) *EditorVCSInterface {
	if p == nil {
		return nil
	}
	ret := &EditorVCSInterface{}
	ret.BindPtr(p)
	return ret
}

// EditorVCSInterfaceChangeType is the Godot EditorVCSInterfaceChangeType enum.
type EditorVCSInterfaceChangeType int64

const (
	EditorVCSInterface_CHANGE_TYPE_NEW        EditorVCSInterfaceChangeType = 0
	EditorVCSInterface_CHANGE_TYPE_MODIFIED   EditorVCSInterfaceChangeType = 1
	EditorVCSInterface_CHANGE_TYPE_RENAMED    EditorVCSInterfaceChangeType = 2
	EditorVCSInterface_CHANGE_TYPE_DELETED    EditorVCSInterfaceChangeType = 3
	EditorVCSInterface_CHANGE_TYPE_TYPECHANGE EditorVCSInterfaceChangeType = 4
	EditorVCSInterface_CHANGE_TYPE_UNMERGED   EditorVCSInterfaceChangeType = 5
)

// EditorVCSInterfaceTreeArea is the Godot EditorVCSInterfaceTreeArea enum.
type EditorVCSInterfaceTreeArea int64

const (
	EditorVCSInterface_TREE_AREA_COMMIT   EditorVCSInterfaceTreeArea = 0
	EditorVCSInterface_TREE_AREA_STAGED   EditorVCSInterfaceTreeArea = 1
	EditorVCSInterface_TREE_AREA_UNSTAGED EditorVCSInterfaceTreeArea = 2
)

var (
	editorVCSInterfaceMethodCreateDiffLine = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("EditorVCSInterface"),
			gdextension.InternStringName("create_diff_line"),
			2901184053,
		)
	})
	editorVCSInterfaceMethodCreateDiffHunk = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("EditorVCSInterface"),
			gdextension.InternStringName("create_diff_hunk"),
			3784842090,
		)
	})
	editorVCSInterfaceMethodCreateDiffFile = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("EditorVCSInterface"),
			gdextension.InternStringName("create_diff_file"),
			2723227684,
		)
	})
	editorVCSInterfaceMethodCreateCommit = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("EditorVCSInterface"),
			gdextension.InternStringName("create_commit"),
			1075983584,
		)
	})
	editorVCSInterfaceMethodCreateStatusFile = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("EditorVCSInterface"),
			gdextension.InternStringName("create_status_file"),
			1083471673,
		)
	})
	editorVCSInterfaceMethodAddDiffHunksIntoDiffFile = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("EditorVCSInterface"),
			gdextension.InternStringName("add_diff_hunks_into_diff_file"),
			4015243225,
		)
	})
	editorVCSInterfaceMethodAddLineDiffsIntoDiffHunk = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("EditorVCSInterface"),
			gdextension.InternStringName("add_line_diffs_into_diff_hunk"),
			4015243225,
		)
	})
	editorVCSInterfaceMethodPopupError = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("EditorVCSInterface"),
			gdextension.InternStringName("popup_error"),
			83702148,
		)
	})
)

// CreateDiffLine mirrors the Godot EditorVCSInterface.create_diff_line method.
func (self *EditorVCSInterface) CreateDiffLine(new_line_no int64, old_line_no int64, content string, status string) variant.Dictionary {
	var ret variant.Dictionary
	tmp_content := variant.NewStringFromString(content)
	defer tmp_content.Destroy()

	tmp_status := variant.NewStringFromString(status)
	defer tmp_status.Destroy()

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&new_line_no)),
		gdextension.TypePtr(unsafe.Pointer(&old_line_no)),
		gdextension.TypePtr(unsafe.Pointer(&tmp_content)),
		gdextension.TypePtr(unsafe.Pointer(&tmp_status)),
	}
	gdextension.CallMethodBindPtrCall(editorVCSInterfaceMethodCreateDiffLine(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// CreateDiffHunk mirrors the Godot EditorVCSInterface.create_diff_hunk method.
func (self *EditorVCSInterface) CreateDiffHunk(old_start int64, new_start int64, old_lines int64, new_lines int64) variant.Dictionary {
	var ret variant.Dictionary
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&old_start)),
		gdextension.TypePtr(unsafe.Pointer(&new_start)),
		gdextension.TypePtr(unsafe.Pointer(&old_lines)),
		gdextension.TypePtr(unsafe.Pointer(&new_lines)),
	}
	gdextension.CallMethodBindPtrCall(editorVCSInterfaceMethodCreateDiffHunk(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// CreateDiffFile mirrors the Godot EditorVCSInterface.create_diff_file method.
func (self *EditorVCSInterface) CreateDiffFile(new_file string, old_file string) variant.Dictionary {
	var ret variant.Dictionary
	tmp_new_file := variant.NewStringFromString(new_file)
	defer tmp_new_file.Destroy()

	tmp_old_file := variant.NewStringFromString(old_file)
	defer tmp_old_file.Destroy()

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_new_file)),
		gdextension.TypePtr(unsafe.Pointer(&tmp_old_file)),
	}
	gdextension.CallMethodBindPtrCall(editorVCSInterfaceMethodCreateDiffFile(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// CreateCommit mirrors the Godot EditorVCSInterface.create_commit method.
func (self *EditorVCSInterface) CreateCommit(msg string, author string, id string, unix_timestamp int64, offset_minutes int64) variant.Dictionary {
	var ret variant.Dictionary
	tmp_msg := variant.NewStringFromString(msg)
	defer tmp_msg.Destroy()

	tmp_author := variant.NewStringFromString(author)
	defer tmp_author.Destroy()

	tmp_id := variant.NewStringFromString(id)
	defer tmp_id.Destroy()

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_msg)),
		gdextension.TypePtr(unsafe.Pointer(&tmp_author)),
		gdextension.TypePtr(unsafe.Pointer(&tmp_id)),
		gdextension.TypePtr(unsafe.Pointer(&unix_timestamp)),
		gdextension.TypePtr(unsafe.Pointer(&offset_minutes)),
	}
	gdextension.CallMethodBindPtrCall(editorVCSInterfaceMethodCreateCommit(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// CreateStatusFile mirrors the Godot EditorVCSInterface.create_status_file method.
func (self *EditorVCSInterface) CreateStatusFile(file_path string, change_type EditorVCSInterfaceChangeType, area EditorVCSInterfaceTreeArea) variant.Dictionary {
	var ret variant.Dictionary
	tmp_file_path := variant.NewStringFromString(file_path)
	defer tmp_file_path.Destroy()

	tmp_change_type := int64(change_type)

	tmp_area := int64(area)

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_file_path)),
		gdextension.TypePtr(unsafe.Pointer(&tmp_change_type)),
		gdextension.TypePtr(unsafe.Pointer(&tmp_area)),
	}
	gdextension.CallMethodBindPtrCall(editorVCSInterfaceMethodCreateStatusFile(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// AddDiffHunksIntoDiffFile mirrors the Godot EditorVCSInterface.add_diff_hunks_into_diff_file method.
func (self *EditorVCSInterface) AddDiffHunksIntoDiffFile(diff_file variant.Dictionary, diff_hunks variant.Array) variant.Dictionary {
	var ret variant.Dictionary
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&diff_file)),
		gdextension.TypePtr(unsafe.Pointer(&diff_hunks)),
	}
	gdextension.CallMethodBindPtrCall(editorVCSInterfaceMethodAddDiffHunksIntoDiffFile(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// AddLineDiffsIntoDiffHunk mirrors the Godot EditorVCSInterface.add_line_diffs_into_diff_hunk method.
func (self *EditorVCSInterface) AddLineDiffsIntoDiffHunk(diff_hunk variant.Dictionary, line_diffs variant.Array) variant.Dictionary {
	var ret variant.Dictionary
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&diff_hunk)),
		gdextension.TypePtr(unsafe.Pointer(&line_diffs)),
	}
	gdextension.CallMethodBindPtrCall(editorVCSInterfaceMethodAddLineDiffsIntoDiffHunk(), self.Ptr(), args[:], gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// PopupError mirrors the Godot EditorVCSInterface.popup_error method.
func (self *EditorVCSInterface) PopupError(msg string) {
	tmp_msg := variant.NewStringFromString(msg)
	defer tmp_msg.Destroy()

	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&tmp_msg)),
	}
	gdextension.CallMethodBindPtrCall(editorVCSInterfaceMethodPopupError(), self.Ptr(), args[:], nil)
}
