// Code generated by godot-go-bindgen. DO NOT EDIT.

package editor

import (
	"sync"
	"unsafe"

	"github.com/legendary-code/godot-go/core"
	"github.com/legendary-code/godot-go/internal/gdextension"
	"github.com/legendary-code/godot-go/variant"
)

// GridMapEditorPlugin mirrors the Godot engine class GridMapEditorPlugin.
type GridMapEditorPlugin struct {
	EditorPlugin
}

// GridMapEditorPluginFromPtr wraps an existing host-allocated GDExtensionObjectPtr in a
// *GridMapEditorPlugin. Returns nil on a nil input.
func GridMapEditorPluginFromPtr(p gdextension.ObjectPtr) *GridMapEditorPlugin {
	if p == nil {
		return nil
	}
	ret := &GridMapEditorPlugin{}
	ret.BindPtr(p)
	return ret
}

var (
	gridMapEditorPluginMethodGetCurrentGridMap = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("GridMapEditorPlugin"),
			gdextension.InternStringName("get_current_grid_map"),
			1184264483,
		)
	})
	gridMapEditorPluginMethodSetSelection = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("GridMapEditorPlugin"),
			gdextension.InternStringName("set_selection"),
			3659408297,
		)
	})
	gridMapEditorPluginMethodClearSelection = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("GridMapEditorPlugin"),
			gdextension.InternStringName("clear_selection"),
			3218959716,
		)
	})
	gridMapEditorPluginMethodGetSelection = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("GridMapEditorPlugin"),
			gdextension.InternStringName("get_selection"),
			1068685055,
		)
	})
	gridMapEditorPluginMethodHasSelection = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("GridMapEditorPlugin"),
			gdextension.InternStringName("has_selection"),
			36873697,
		)
	})
	gridMapEditorPluginMethodGetSelectedCells = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("GridMapEditorPlugin"),
			gdextension.InternStringName("get_selected_cells"),
			3995934104,
		)
	})
	gridMapEditorPluginMethodSetSelectedPaletteItem = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("GridMapEditorPlugin"),
			gdextension.InternStringName("set_selected_palette_item"),
			998575451,
		)
	})
	gridMapEditorPluginMethodGetSelectedPaletteItem = sync.OnceValue(func() gdextension.MethodBindPtr {
		return gdextension.GetMethodBind(
			gdextension.InternStringName("GridMapEditorPlugin"),
			gdextension.InternStringName("get_selected_palette_item"),
			3905245786,
		)
	})
)

// GetCurrentGridMap mirrors the Godot GridMapEditorPlugin.get_current_grid_map method.
func (self *GridMapEditorPlugin) GetCurrentGridMap() *core.GridMap {
	var ret gdextension.ObjectPtr
	gdextension.CallMethodBindPtrCall(gridMapEditorPluginMethodGetCurrentGridMap(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return core.GridMapFromPtr(ret)
}

// SetSelection mirrors the Godot GridMapEditorPlugin.set_selection method.
func (self *GridMapEditorPlugin) SetSelection(begin variant.Vector3i, end variant.Vector3i) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&begin)),
		gdextension.TypePtr(unsafe.Pointer(&end)),
	}
	gdextension.CallMethodBindPtrCall(gridMapEditorPluginMethodSetSelection(), self.Ptr(), args[:], nil)
}

// ClearSelection mirrors the Godot GridMapEditorPlugin.clear_selection method.
func (self *GridMapEditorPlugin) ClearSelection() {
	gdextension.CallMethodBindPtrCall(gridMapEditorPluginMethodClearSelection(), self.Ptr(), nil, nil)
}

// GetSelection mirrors the Godot GridMapEditorPlugin.get_selection method.
func (self *GridMapEditorPlugin) GetSelection() variant.AABB {
	var ret variant.AABB
	gdextension.CallMethodBindPtrCall(gridMapEditorPluginMethodGetSelection(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// HasSelection mirrors the Godot GridMapEditorPlugin.has_selection method.
func (self *GridMapEditorPlugin) HasSelection() bool {
	var ret bool
	gdextension.CallMethodBindPtrCall(gridMapEditorPluginMethodHasSelection(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// GetSelectedCells mirrors the Godot GridMapEditorPlugin.get_selected_cells method.
func (self *GridMapEditorPlugin) GetSelectedCells() variant.Array {
	var ret variant.Array
	gdextension.CallMethodBindPtrCall(gridMapEditorPluginMethodGetSelectedCells(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}

// SetSelectedPaletteItem mirrors the Godot GridMapEditorPlugin.set_selected_palette_item method.
func (self *GridMapEditorPlugin) SetSelectedPaletteItem(item int64) {
	args := [...]gdextension.TypePtr{
		gdextension.TypePtr(unsafe.Pointer(&item)),
	}
	gdextension.CallMethodBindPtrCall(gridMapEditorPluginMethodSetSelectedPaletteItem(), self.Ptr(), args[:], nil)
}

// GetSelectedPaletteItem mirrors the Godot GridMapEditorPlugin.get_selected_palette_item method.
func (self *GridMapEditorPlugin) GetSelectedPaletteItem() int64 {
	var ret int64
	gdextension.CallMethodBindPtrCall(gridMapEditorPluginMethodGetSelectedPaletteItem(), self.Ptr(), nil, gdextension.TypePtr(unsafe.Pointer(&ret)))
	return ret
}
