package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
)

// emitAliases writes <godotDir>/aliases.gen.go, a small re-export shim that
// promotes the high-traffic builtin types onto the top-level `godot` package.
// Users typically import "godot" and reach for `godot.Vector2` rather than
// fishing through `variant`.
func emitAliases(builtins []string, godotDir string) error {
	// Restrict to the names we actually emitted, in the listed canonical order.
	want := []string{
		"Variant",
		"String", "StringName", "NodePath",
		"Vector2", "Vector2i", "Vector3", "Vector3i", "Vector4", "Vector4i",
		"Rect2", "Rect2i",
		"Transform2D", "Transform3D",
		"Plane", "Quaternion", "AABB", "Basis", "Projection",
		"Color",
		"RID",
		"Callable", "Signal",
		"Dictionary", "Array",
		"PackedByteArray", "PackedInt32Array", "PackedInt64Array",
		"PackedFloat32Array", "PackedFloat64Array",
		"PackedStringArray",
		"PackedVector2Array", "PackedVector3Array", "PackedVector4Array",
		"PackedColorArray",
	}
	have := map[string]bool{"Variant": true} // hand-written, always present
	for _, b := range builtins {
		have[b] = true
	}

	var b bytes.Buffer
	b.WriteString(`// Code generated by godot-go-bindgen. DO NOT EDIT.

// Package godot is the public facade for godot-go users. It re-exports the
// high-traffic builtin types from variant/ so user code can `+"`import \"github.com/legendary-code/godot-go/godot\"`"+`
// and reach for godot.Vector2 directly.
package godot

import (
	"github.com/legendary-code/godot-go/variant"
)

`)
	b.WriteString("type (\n")
	for _, name := range want {
		if !have[name] {
			continue
		}
		fmt.Fprintf(&b, "\t%s = variant.%s\n", name, name)
	}
	b.WriteString(")\n")

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		_ = os.WriteFile(filepath.Join(godotDir, "aliases.gen.go.broken"), b.Bytes(), 0o644)
		return fmt.Errorf("gofmt: %w\n%s", err, b.String())
	}

	out := filepath.Join(godotDir, "aliases.gen.go")
	return os.WriteFile(out, formatted, 0o644)
}
